









LivingWorldPlayerArmy
	Name = AragornPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorAragornEntwicklung1
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GandalfPlayerArmy
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorGandalf
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_StartingArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorSpearmanHorde
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = TheodenPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = EomerPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanEomer
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GamlingPlayerArmy
	DisplayNameTag = LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate = RohanGamling
		Quantity = 1
	End
End


LivingWorldPlayerArmy
	Name = Rohan_StartingArmy
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = RohanArcherHorde_mod
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanSpeerwerferHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End




LivingWorldPlayerArmy
	Name = ThranduilPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = ElvenThranduil_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = CelebornPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = LothlorienCeleborn
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GaladrielPlayerArmy
	DisplayNameTag = LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate = LothlorienGaladriel
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Elven_StartingArmy
	DisplayNameTag = LWA:ElvesGarrison
	ArmyEntry
		ThingTemplate = ElvenLorienWarriorHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenLorienPikemanHorde
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = ElrondPlayerArmy
	DisplayNameTag = LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate = ImladrisElrond
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GlorfindelPlayerArmy
	DisplayNameTag = LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate = ImladrisGlorfindel
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = LothlorienCirdanArmy
	DisplayNameTag = LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate = LothlorienCirdan
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Imladris_StartingArmy
	DisplayNameTag = LWA:ImladrisGarrison
	ArmyEntry
		ThingTemplate = ImladrisSwordManHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = BruchtalBogenschuetzenHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ElvenRivendellLancerHordeMod
		Quantity = 1
	End
End





LivingWorldPlayerArmy
	Name = DwarvenThorinArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenThorinIII
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DainPlayerArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenDainErebor
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DwarvenBalinArmy
	DisplayNameTag = LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate = DwarvenBalin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Dwarven_StartingArmy
	DisplayNameTag = LWA:DwarvesGarrison
	ArmyEntry
		ThingTemplate = DwarvenGuardianEreborHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = DwarvenAxeThrowerHorde
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = GroﬂorkPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGreatGoblin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = DrogothPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = Drogoth
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GorkilPlayerArmy
	DisplayNameTag = LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate = WildGoblinKing_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = CorruptedWild_StartingArmy
	DisplayNameTag = LWA:WildGarrison
	ArmyEntry
		ThingTemplate = GoblinFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GoblinCaveTroll
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKing
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = GothmogPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGothmog_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MordorNekromantPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorGorthaur
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Mordor_StartingArmy
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = SarumanPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSaruman_Mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = LurtzPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardLurtz_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = SharkuPlayerArmy
	DisplayNameTag = LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate = IsengardSharku_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Isengard_StartingArmy
	DisplayNameTag = LWA:IsengardGarrison
	ArmyEntry
		ThingTemplate = IsengardFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardUrukCrossbowHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = IsengardSharkuswargreiterHorde
		Quantity = 1
	End
End





LivingWorldPlayerArmy
	Name = MorgramirPlayerArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarMorgramir_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WitchKingArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarWitchking_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = HwaldarPlayerArmy
	DisplayNameTag = LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate = AngmarHwaldar_mod
		Quantity = 1
	End
End


LivingWorldPlayerArmy
	Name = Angmar_StartingArmy
	DisplayNameTag = LWA:AngmarGarrison
        ArmyEntry
                ThingTemplate = AngmarThrallMaster
                Quantity = 1
        End
	ArmyEntry
		ThingTemplate = AngmarDarkDunedainHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = AngmarDarkRangerHorde
		Quantity = 1
	End
End






LivingWorldPlayerArmy
	Name = TheodenPlayerArmy_Tutorial
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = RohanTheoden
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = AragornPlayerArmy_Tutorial
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorAragorn
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorRangerHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = RohanRohirrimHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = BoromirPlayerArmy_Tutorial
	DisplayNameTag = LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate = GondorBoromir
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorFighterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = MenOfTheWest_Garrison1_Tutorial
	DisplayNameTag = LWA:MenOfTheWestGarrison
	ArmyEntry
		ThingTemplate = GondorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorTowerShieldGuardHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = GondorKnightHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = WitchKingPlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorWitchKingOnFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = FellBeast1PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = FellBeast2PlayerArmy_Tutorial
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorFellBeast
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorAttackTroll
		Quantity = 2
	End
	ArmyEntry
		ThingTemplate = MordorCorsairsOfUmbarHorde
		Quantity = 2
	End
End

LivingWorldPlayerArmy
	Name = Mordor_Garrison1_Tutorial
	DisplayNameTag = LWA:MordorGarrison
	ArmyEntry
		ThingTemplate = MordorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorMountainTroll
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = MordorDrummerTroll
		Quantity = 1
	End
End












LivingWorldPlayerArmy
	Name = ArnorArveduiArmy
	DisplayNameTag = LWA:ArnorHeroArmy
	ArmyEntry
		ThingTemplate = GondorArvedui
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorAranarthArmy
	DisplayNameTag = LWA:ArnorHeroArmy
	ArmyEntry
		ThingTemplate = ArnorAranarth
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorEarnurArmy
	DisplayNameTag = LWA:ArnorHeroArmy
	ArmyEntry
		ThingTemplate = GondorEarnur
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorCartheanArmy
	DisplayNameTag = LWA:ArnorHeroArmy
	ArmyEntry
		ThingTemplate = ArnorCaptainStealthless_mod
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = Arnor_StartingArmy
	DisplayNameTag = LWA:ArnorGarrison
	ArmyEntry
		ThingTemplate = ArnorFighterHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorArcherHorde
		Quantity = 1
	End
	ArmyEntry
		ThingTemplate = ArnorKnightHorde
		Quantity = 1
	End
End


