








SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerMen
	HeroTemplateName = GondorAragornEntwicklung1
	PlayerArmy = AragornPlayerArmy
	Icon = HeroAragornIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerMen
	HeroTemplateName = GondorBoromir
	PlayerArmy = BoromirPlayerArmy
	Icon = HeroBoromirIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = HeroArmy4
	SpawnForTemplates = PlayerMen
	HeroTemplateName = GondorGandalf
	PlayerArmy = GandalfPlayerArmy
	Icon = HeroFaramirIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerMen
	PlayerArmy = MenOfTheWest_StartingArmy
	Icon = MoWArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1

	SpawnForTemplates = PlayerRohan
	HeroTemplateName = RohanTheoden
	PlayerArmy = TheodenPlayerArmy
	Icon = HeroTheodenIcon

	Banner = BannerRohan
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerRohan
	HeroTemplateName = RohanEomer
	PlayerArmy = EomerPlayerArmy
	Icon = HeroEomerIcon
	Banner = BannerRohan
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerRohan
	HeroTemplateName = RohanGamling
	PlayerArmy = GamlingPlayerArmy
	Icon = HeroGamlingIcon
	Banner = BannerRohan
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerRohan
	PlayerArmy = Rohan_StartingArmy
	Icon = RohanArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerElves
	HeroTemplateName = ElvenThranduil_mod
	PlayerArmy = ThranduilPlayerArmy
	Icon = HeroThranduilIcon
	Banner = BannerElves
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerElves
	HeroTemplateName = LothlorienCeleborn
	PlayerArmy = CelebornPlayerArmy
	Icon = HeroCelebornIcon
	Banner = BannerElves
End

SpawnArmy
	ScriptingName = HeroArmy4
	SpawnForTemplates = PlayerElves
	HeroTemplateName = LothlorienGaladriel
	PlayerArmy = GaladrielPlayerArmy
	Icon = HeroGaladrielIcon
	Banner = BannerElves
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerElves
	PlayerArmy = Elven_StartingArmy
	Icon = ElfArmyIcon
End







SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerImladris
	HeroTemplateName = ImladrisElrond
	PlayerArmy = ElrondPlayerArmy
	Icon = HeroElrondIcon
	Banner = BannerImladris
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerImladris
	HeroTemplateName = ImladrisGlorfindel
	PlayerArmy = GlorfindelPlayerArmy
	Icon = HeroGlorfindelIcon
	Banner = BannerImladris
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerImladris
	HeroTemplateName = LothlorienCirdan
	PlayerArmy = LothlorienCirdanArmy
	Icon = HeroArwenIcon
	Banner = BannerImladris
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerImladris
	PlayerArmy = Imladris_StartingArmy
	Icon = ImladrisArmyIcon
End







SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerDwarves
	HeroTemplateName = DwarvenThorinIII
	PlayerArmy = DwarvenThorinArmy
	Icon = HeroThorinIcon
	Banner = BannerDwarves
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerDwarves
	HeroTemplateName = DwarvenDainErebor
	PlayerArmy = DainPlayerArmy
	Icon = HeroDainIcon
	Banner = BannerDwarves
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerDwarves
	HeroTemplateName = DwarvenBalin
	PlayerArmy = DwarvenBalinArmy
	Icon = HeroBalinIcon
	Banner = BannerDwarves
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerDwarves
	PlayerArmy = Dwarven_StartingArmy
	Icon = DwarfArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerMordor
	HeroTemplateName = MordorWitchKing
	PlayerArmy = WitchKingPlayerArmy
	Icon = HeroWitchKingIcon
	Banner = BannerMordor
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerMordor
	HeroTemplateName = MordorGothmog_mod
	PlayerArmy = GothmogPlayerArmy
	Icon = HeroGothmogIcon
	Banner = BannerMordor
End

SpawnArmy
	ScriptingName = HeroArmy4
	SpawnForTemplates = PlayerMordor
	HeroTemplateName = MordorGorthaur
	PlayerArmy = MordorNekromantPlayerArmy
	Icon = HeroNekromantIcon
	Banner = BannerMordor
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerMordor
	PlayerArmy = Mordor_StartingArmy
	Icon = MordorArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerIsengard
	HeroTemplateName = IsengardSaruman_Mod
	PlayerArmy = SarumanPlayerArmy
	Icon = HeroSarumanIcon
	Banner = BannerIsengard
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerIsengard
	HeroTemplateName = IsengardLurtz_mod
	PlayerArmy = LurtzPlayerArmy
	Icon = HeroLurtzIcon
	Banner = BannerIsengard
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerIsengard
	HeroTemplateName = IsengardSharku_mod
	PlayerArmy = SharkuPlayerArmy
	Icon = HeroSharkuIcon
	Banner = BannerIsengard
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerIsengard
	PlayerArmy = Isengard_StartingArmy
	Icon = IsengardArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerWild
	HeroTemplateName = Drogoth
	PlayerArmy = DrogothPlayerArmy
	Icon = HeroDrogothIcon
	Banner = BannerWild
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerWild
	HeroTemplateName = WildGreatGoblin
	PlayerArmy = GroﬂorkPlayerArmy
	Icon = HeroGroﬂorkIcon
	Banner = BannerWild
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerWild
	HeroTemplateName = WildGoblinKing_mod
	PlayerArmy = GorkilPlayerArmy
	Icon = HeroGorkilIcon
	Banner = BannerWild
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerWild
	PlayerArmy = CorruptedWild_StartingArmy
	Icon = WildArmyIcon
End





SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerAngmar
	HeroTemplateName = AngmarMorgramir_mod
	PlayerArmy = MorgramirPlayerArmy
	Icon = HeroMorgramirIcon
	Banner = BannerAngmar
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerAngmar
	HeroTemplateName = AngmarWitchking_mod
	PlayerArmy = WitchKingArmy
	Icon = HeroAngmarWitchkingIcon
	Banner = BannerAngmar
End

SpawnArmy
	ScriptingName = HeroArmy4
	SpawnForTemplates = PlayerAngmar
	HeroTemplateName = AngmarHwaldar_mod
	PlayerArmy = HwaldarPlayerArmy
	Icon = HeroHwaldarIcon
	Banner = BannerAngmar
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerAngmar
	PlayerArmy = Angmar_StartingArmy
	Icon = AngmarArmyIcon
End






SpawnArmy
	ScriptingName = HeroArmy1
	SpawnForTemplates = PlayerArnor
	HeroTemplateName = GondorArvedui
	PlayerArmy = ArnorArveduiArmy
	Icon = HeroArveduiIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = HeroArmy2
	SpawnForTemplates = PlayerArnor
	HeroTemplateName = ArnorAranarth
	PlayerArmy = ArnorAranarthArmy
	Icon = HeroAranarthIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = HeroArmy3
	SpawnForTemplates = PlayerArnor
	HeroTemplateName = GondorEarnur
	PlayerArmy = ArnorEarnurArmy
	Icon = HeroEarnurIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = HeroArmy4
	SpawnForTemplates = PlayerArnor
	HeroTemplateName = ArnorCaptainStealthless_mod
	PlayerArmy = ArnorCartheanArmy
	Icon = HeroCartheanIcon
	Banner = BannerMen
End

SpawnArmy
	ScriptingName = GarrisonArmy1
	SpawnForTemplates = PlayerArnor
	PlayerArmy = Arnor_StartingArmy
	Icon = ArnorArmyIcon
End


