LivingWorldPlayerArmy
	Name 			= PippinArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= RohanPippin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorBeregondArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorBeregond
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorFaramirArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorFaramir
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BoromirPlayerArmy
	DisplayNameTag 		= LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate 	= GondorBoromir
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GandalfPlayerArmy
	DisplayNameTag 		= LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate 	= GondorGandalf
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AragornPlayerArmy
	DisplayNameTag 		= LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate 	= GondorAragornEntwicklung1
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorImrahilArmy
	DisplayNameTag 		= LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate 	= GondorImrahil
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorDamrodArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorDamrod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EdainBerenArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= EdainBeren
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DoriathLuthienArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= DoriathLuthien
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorThorondorArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= ValinorThorondor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NargothrondFinrodArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= NargothrondFinrod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorManweArmy
	DisplayNameTag 		= LWA:MenHeroArmy
	ArmyEntry
		ThingTemplate 	= ValinorManwe_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= GondorFighterArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorSpearmanArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorSpearmanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorTowerShieldGuardArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorTowerShieldGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorWachterderVesteArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorWachterderVesteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorBoromirGuardArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorBoromirGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorArcherArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorRangerArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorRangerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorKnightArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorKnightHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LehenDolsoldatenHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= LehenDolsoldatenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorKnightsofDolHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorKnightsofDolHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MorthondBowmenHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= MorthondBowmenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LehenLossarnachAxteHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= LehenLossarnachAxteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= PelegirSpearmenHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= PelegirSpearmenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RingValeSwordsmanHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= RingValeSwordsmanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IthilienSchwertkampferHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= IthilienSchwertkampferHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IthilienSpeertragerHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= IthilienSpeertragerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EdainOutlawBarahirHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= EdainOutlawBarahirHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EdainOutlawBarahirEliteHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= EdainOutlawBarahirEliteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorEagleArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= ValinorEagle
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NargothrondHammerHordeArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= NargothrondHammerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondorTrebuchetArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= GondorTrebuchet
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= MerryArmy
	DisplayNameTag 		= LWA:MenOfTheWest
	ArmyEntry
		ThingTemplate 	= RohanMerry_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GamlingPlayerArmy
	DisplayNameTag 		= LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate 	= RohanGamling
		Quantity 		= 1
	End
End

LivingWorldPlayerArmy
	Name 			= HamaArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanHama
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EowynArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanEowyn_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TheodredPlayerArmy
	DisplayNameTag 		= LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate 	= RohanTheodred
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TheodenPlayerArmy
	DisplayNameTag 		= LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate 	= RohanTheoden
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EomerPlayerArmy
	DisplayNameTag 		= LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate 	= RohanEomer
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanErkenbrandArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanErkenbrand
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanHelmHammerHandArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanHelmHammerHand
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanGhanArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= GasthausGhanBuriGhan
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= VanyarIngweArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= VanyarIngwe
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EdainTurinArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= EdainTurin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorEonweArmy
	DisplayNameTag 		= LWA:RohanHeroArmy
	ArmyEntry
		ThingTemplate 	= ValinorEonwe_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= RohanPeasantArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanPeasantHorde_modneu
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanFighterHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanAxeFighterHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanAxeFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanWachterMeduseldsHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanLancerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanAxeFighterHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanAxeFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= RohanHauptmannArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanCaptain
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= GetreueSpeerHordeHauptmannArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= GetreueSpeerHordeHauptmann
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= GetreueSchwertHordeHauptmannArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= GetreueSchwertHordeHauptmann
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= GetreueReiterHordeHauptmannArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= GetreueReiterHordeHauptmann
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanBatteringRamArmy
	DisplayNameTag	 	= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanBatteringRam
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanTrebuchetArmy
	DisplayNameTag	 	= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanTrebuchet
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanArcherArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanArcherHorde_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= RohanSpeerwerferArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanSpeerwerferHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanRohirrimHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanRohirrimHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanAxtrohirrimArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanAxtrohirrimHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanRohirrimArcherArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanRohirrimArcherHordeMod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanRoyalGuardArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanRoyalGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name			= RohanRoyalGuardInfantryHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanRoyalGuardInfantryHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TaniquetilGuardHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= TaniquetilGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TaniquetilWatcherHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= TaniquetilWatcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TaniquetilCaptianArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= TaniquetilCaptian
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= RohanHelmAxeGuardHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= RohanHelmAxeGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DruedainKriegerHordeArmy
	DisplayNameTag 		= LWA:Rohan
	ArmyEntry
		ThingTemplate 	= DruedainKriegerHorde
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= RumilOrophinArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienRumil
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= HaldirPlayerArmy
	DisplayNameTag 		= LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate 	= LothlorienHaldir
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= CelebornPlayerArmy
	DisplayNameTag 		= LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate 	= LothlorienCeleborn
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GaladrielPlayerArmy
	DisplayNameTag 		= LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate 	= LothlorienGaladriel
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LothlorienTaurielrmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienTauriel
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LegolasArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienLegolas
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThranduilPlayerArmy
	DisplayNameTag 		= LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate 	= ElvenThranduil_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TreeBerdArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ImladrisTreeBerd
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= FangornFlinkbaumArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= FangornFlinkbaum
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GasthausGrimbeornArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= GasthausGrimbeorn
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DoriathBelegArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= DoriathBeleg
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DoriathMablungArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= DoriathMablung
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DoriathThingolArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= DoriathThingol
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AlqualondOlweArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= AlqualondOlwe
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DoriathMelianArmy
	DisplayNameTag 		= LWA:ElvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DoriathMelian_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= ElvenLorienArcherArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ElvenLorienArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenLorienWarriorArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ElvenLorienWarriorHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenLorienPikemanHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ElvenLorienPikemanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LothlorienSangerinnenArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienSangerinnen1
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LothlorienGrenzwaechterArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienGrenzwachterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LothlorienGaladhrimArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienGaladhrimHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DorwinionWinzerArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= DorwinionWinzer
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenMirkwoodArcherHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ElvenMirkwoodArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MirkwoodWarriorHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MirkwoodWarriorHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MirkwoodSpearmenHordeeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MirkwoodSpearmenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MirkwoodWachterPfadeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MirkwoodArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MirkwoodPalaceGuardHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= LothlorienMirkwoodPalaceGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MirkwoodElkriderHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MirkwoodElkriderHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenEntArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ImladrisEntFir
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenEntAshArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= ImladrisEntAsh
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MenegrothGuardHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MenegrothGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MenegrothEliteHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MenegrothEliteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MenegrothCavalaryHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= MenegrothCavalaryHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AlqualondeGuardianHordeArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= AlqualondeGuardianHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GasthausBeorningerArmy
	DisplayNameTag 		= LWA:Elves
	ArmyEntry
		ThingTemplate 	= GasthausBeorninger_Lorien
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= ImladrisErestorArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisErestor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ArwenPlayerArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisArwen
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ZwillingePlayerArmy
	DisplayNameTag 		= LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate 	= ImladrisZwillingeEdain
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElrondPlayerArmy
	DisplayNameTag 		= LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate 	= ImladrisElrond
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GlorfindelPlayerArmy
	DisplayNameTag 		= LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate 	= ImladrisGlorfindel
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ImladrisGildorArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisGildor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LothlorienCirdanArmy
	DisplayNameTag 		= LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate 	= LothlorienCirdan
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DunedainHalbaradArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= DunedainHalbarad
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ImladrisGwaihirArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisGwaihir_WOTR
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NoldorFeanorArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= NoldorFeanor
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= NoldorFingolfinArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= NoldorFingolfin
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorTulkasArmy
	DisplayNameTag 		= LWA:ImladrisHeroArmy
	ArmyEntry
		ThingTemplate 	= ValinorTulkas_WOR
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondolinTurgonArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= GondolinTurgon
		Quantity = 1
	End
End




LivingWorldPlayerArmy
	Name 			= BruchtalSchwertkaempferArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisSwordManHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalLancerArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalLancerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalBogenschuetzenArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalBogenschuetzenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ImladrisWaffenmeisterArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisWaffenmeisterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ImladrisElbenfuerstArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ImladrisElbenfuerst
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ElvenRivendellLancerArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ElvenRivendellLancerHordeMod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name	 		= ElvenKnightHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= ElvenKnightHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LindonWachterHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= LindonWachterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DunedainRangerModHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= DunedainRangerModHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= FormenosArcherHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= FormenosArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= FormenosGuardHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= FormenosGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= FormenosEliteSwordHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= FormenosEliteSwordHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondolinArcherHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= GondolinArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondolinGuardHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= GondolinGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GondolinWarriorHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= GondolinWarriorHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalLichtbringerFeuerHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalLichtbringerFeuerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalLichtbringerWasserHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalLichtbringerWasserHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalLichtbringerErdeHordeArmy
	DisplayNameTag 		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalLichtbringerErdeHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BruchtalLichtbringerLuftHordeArmy
	DisplayNameTag		= LWA:Imladris
	ArmyEntry
		ThingTemplate 	= BruchtalLichtbringerLuftHorde
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name 			= DwarvenNarinArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenNarin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GimliPlayerArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenGimliMod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GloinPlayerArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenGloin_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenBalinArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DwarvenBalin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NoriEreborArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DwarvenNoriErebor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenThorinArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DwarvenThorinIII
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DainPlayerArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DwarvenDainErebor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= CaptainofDalePlayerArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= DwarvenBrand
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BelegostAzaghalArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= BelegostAzaghal
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NogrodTelcharArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= NogrodTelchar
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ValinorAuleArmy
	DisplayNameTag 		= LWA:DwarvesHeroArmy
	ArmyEntry
		ThingTemplate 	= ValinorAule_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= DwarvenGuardianEreborArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenGuardianEreborHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenAxeThrowerArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenAxeThrowerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenArkenguardArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenArkenguardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenThalSwordmanHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenThalSwordmanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenThalBowmanHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenThalBowmanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenThalPikemanHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenThalPikemanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenOrocarniHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenOrocarniHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenKhazadVeteranenArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenKhazadVeteranenHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AglarondHunterHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= AglarondHunterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AglarondPikeHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= AglarondPikeHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AglarondCavalaryHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= AglarondCavalaryHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= NogrodSmiteArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= NogrodSmite
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= BelegostRiderHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= BelegostRiderHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BelegostEliteHordeArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= BelegostEliteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenBattleWagonArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenBattleWagon
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenDemolisherArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenDemolisher_Erebor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DwarvenCatapultArmy
	DisplayNameTag 		= LWA:Dwarves
	ArmyEntry
		ThingTemplate 	= DwarvenCatapult
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name 			= MordorNekromantPlayerArmy
	DisplayNameTag 		= LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate 	= MordorGorthaur
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorNazgulToggleHordeArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorNazgulToggleHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorNazgulArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorNazgul_CGmod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorNazgul2Army
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorNazgul_CGmod2
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GasthausKhamulArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= GasthausKhamul
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WitchKingPlayerArmy
	DisplayNameTag 		= LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate 	= MordorWitchKing
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MouthOfSauronArmy
	DisplayNameTag 		= LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate 	= MordorMouthOfSauron_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GothmogPlayerArmy
	DisplayNameTag 		= LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate 	= MordorGothmog_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorMollokArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= Wildmollok_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= HaradSuladanArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= HaradSuladan
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorCastamir Army
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorCastamir
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name 			= EvilmenSalemeArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= EvilmenSalemeAlternative
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandCarcharothArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= AngbandCarcharoth
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandGlaurungArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= AngbandGlaurung
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandMelkorArmy
	DisplayNameTag 		= LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate 	= AngbandMelkor_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name = MordorSauronPlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = MordorSauron_mod
		Quantity = 1
	End
End
LivingWorldPlayerArmy
	Name = FellBeast2PlayerArmy
	DisplayNameTag = LWA:Mordor
	ArmyEntry
		ThingTemplate = MorgomirFellBeast
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = FellBeast1PlayerArmy
	DisplayNameTag = LWA:MordorHeroArmy
	ArmyEntry
		ThingTemplate = KhamulFellBeast
		Quantity = 1
	End
End




LivingWorldPlayerArmy
	Name 			= MordorFighterArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorArcherArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorPikemanArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorPikemanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorDrummerTrollArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorDrummerTroll
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorMountainTrollArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate	= MordorMountainTroll
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorBlackUrukArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorBlackUrukHorde_Limit
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorBlackUrukBowArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorBlackUrukBowHorde_Limit
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorMorgulriderArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorMorgulriderHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorKastellanArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorKastellan
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorEasterlingArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= HaradHaradrimLancerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorHaradrimArcherArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= HaradHaradrimArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EasterlingGuardArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= EasterlingGuardHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= EasterlingKataphrakArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= EasterlingKataphraktHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorMumakilArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorMumakil
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandIronWormArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= AngbandIronWorm
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandFireDrakeArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= AngbandFireDrake
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandDragonArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= AngbandDragon
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorCatapultArmy
	DisplayNameTag 		= LWA:Mordor
	ArmyEntry
		ThingTemplate 	= MordorCatapult
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name 			= WormTongueArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardWormTongue_Mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= SarumanPlayerArmy
	DisplayNameTag 		= LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate 	= IsengardSaruman_Mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MauhurArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardMauhur
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UglukArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate	= IsengardUgluk_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= LurtzPlayerArmy
	DisplayNameTag 		= LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate 	= IsengardLurtz_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= SharkuPlayerArmy
	DisplayNameTag 		= LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate 	= IsengardSharku_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WulfgarPlayerArmy
	DisplayNameTag 		= LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate 	= IsengardWulfgar
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AlatarPlayerArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= GasthausAlatar
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MordorGrishnakArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= MordorGrishnak_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= PalandoPlayerArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= GasthausPalando
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThargelionUldorArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= ThargelionUldor
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothDraugluinArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= TolinGaurhothDraugluin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothThuringwethilArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= TolinGaurhothThuringwethil
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothTarMaironArmy
	DisplayNameTag 		= LWA:IsengardHeroArmy
	ArmyEntry
		ThingTemplate 	= TolinGaurhothTarMairon_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= IsengardUrukScoutArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardUrukScoutHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardFighterArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardUrukCrossbowArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardUrukCrossbowHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardPikemanArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardPikemanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardShieldurukArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardShieldurukHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardBeserkerArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardBeserker
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardWargRiderArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardSharkuswargreiterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardWildmanArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardWildmanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardWildmanAxeArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardWildmanAxeHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardWildeliteArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardWildeliteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardWargBowArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardWargBowHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThargelionCavalaryArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= ThargelionCavalaryHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThargelionMumakilArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= ThargelionMumakil
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothVampiresHordeArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= TolinGaurhothVampires
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothWolfHordeArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= TolinGaurhothWolfHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= TolinGaurhothWereWolfArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= TolinGaurhothWereWolf
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardUrukHauptmann1Army
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardUrukHauptmann1
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardUrukHauptmann2Army
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardUrukHauptmann2
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardUrukHauptmann3Army
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardUrukHauptmann3
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= IsengardBallistaArmy
	DisplayNameTag 		= LWA:Isengard
	ArmyEntry
		ThingTemplate 	= IsengardBallista
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name 			= WildShelobArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildShelob
		Quantity	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GroﬂorkPlayerArmy
	DisplayNameTag 		= LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate 	= WildGreatGoblin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GorkilPlayerArmy
	DisplayNameTag 		= LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate 	= WildGoblinKing_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BolgPlayerArmy
	DisplayNameTag 		= LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate 	= WildDurburz
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildAzogArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildAzog
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GundabadBolgArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GundabadBolg
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildDuhrburArmy
	DisplayNameTag		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildDuhrbur
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DrogothPlayerArmy
	DisplayNameTag 		= LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate 	= Drogoth
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildSmaugArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildSmaug_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandScathaArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= AngbandScatha
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandGothmogArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= AngbandGothmog
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandAncalagonArmy
	DisplayNameTag 		= LWA:WildHeroArmy
	ArmyEntry
		ThingTemplate 	= AngbandAncalagon_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= GoblinFighterArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinFighterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GoblinArcherArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GoblinSpearArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinSpearHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildDrummerOrcArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildDrummerOrc
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GoblinRiderArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinRiderHorde
		Quantity	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GundabadWargPackArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GundabadWargPackHorde
		Quantity	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GundabadWargRiderArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GundabadWargRiderHorde
		Quantity	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildMaraudersArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildMarauderHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildMarauderSwordArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildMarauderSwordHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GoblinCaveTrollArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinCaveTroll
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildSpiderlingArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildSpiderlingHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GoblinSpiderRidersArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= GoblinSpiderRiderHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildMountianGiantArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildMountainGiantMod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= WildCatapultArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= WildCatapult
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandBabyDrakeHordeArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= AngbandBabyDrakeHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngbandBalrogArmy
	DisplayNameTag 		= LWA:CorruptedWild
	ArmyEntry
		ThingTemplate 	= AngbandBalrog
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name 			= WitchKingArmy
	DisplayNameTag 		= LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate 	= AngmarWitchking_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AndrolArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarAndrol
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= DurmarthArmy
	DisplayNameTag 		= LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate 	= AngmarDurmarth
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= MorgramirArmy
	DisplayNameTag 		= LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate 	= AngmarMorgramir_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarHelegwenArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarHelegwen
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= GulzarArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarGulzarHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarKarshArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarKarsh_mod_AI
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarRogash_modArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarRogash_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarDrauglinArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarDrauglin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= HwaldarArmy
	DisplayNameTag 		= LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate 	= AngmarHwaldar_mod
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThlimDoldronMaeglinArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= ThlimDoldronMaeglin
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UnderworldOverlordArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= UnderworldOverlord
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UnderworldWizardArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= UnderworldWizard
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AvatharUngoliantArmy
	DisplayNameTag 		= LWA:AngmarHeroArmy
	ArmyEntry
		ThingTemplate 	= AvatharUngoliant_WOR
		Quantity 	= 1
	End
End




LivingWorldPlayerArmy
	Name 			= AngmarThrallmasterArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarThrallMaster
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarDarkDunedainArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarDarkDunedainHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarDarkRangerArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarDarkRangerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarDunedainPikemanArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarDunedainPikemanHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarNumEliteHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarNumEliteHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarSchwarzeRitterHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarSchwarzeRitterHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarDireWolfArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarDireWolfHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarSnowTrollHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarSnowTrollHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarHillTrollHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarHillTrollHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= BarrowWightArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarGrabunhold
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarNecromancerArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarNecromancerHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThlimDoldronArcherHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= ThlimDoldronArcherHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= ThlimDoldronAxeHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= ThlimDoldronAxeHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= AngmarTrollSlingArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= AngmarTrollSling
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UnderworldSoulCollectorHordeArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= UnderworldSoulCollectorHorde
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UnderworldDragonArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= UnderworldDragon
		Quantity 	= 1
	End
End

LivingWorldPlayerArmy
	Name 			= UnderworldDeamonArmy
	DisplayNameTag 		= LWA:Angmar
	ArmyEntry
		ThingTemplate 	= UnderworldDeamon
		Quantity 	= 1
	End
End



LivingWorldPlayerArmy
	Name = ArnorFighterArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorFighterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorArcherArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorArcherHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorRangerArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorRangerHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorTowerShieldGuardArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorTowerShieldGuardHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorKnightArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorKnightHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorTrebuchetArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorTrebuchet
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorHueterHordeArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorHueterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorPalantirwachterHordeArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorPalantirwachterHorde
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorAraphantArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorAraphant
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorGandalfArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = GondorGandalf_forFornost
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorArveduiArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = GondorArvedui
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorAranarthArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorAranarth
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorEarnurArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = GondorEarnur
		Quantity = 1
	End
End

LivingWorldPlayerArmy
	Name = ArnorCartheanArmy
	DisplayNameTag = LWA:Arnor
	ArmyEntry
		ThingTemplate = ArnorCaptainStealthless_mod
		Quantity = 1
	End
End

