ModifierList ExpandableHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList ExpandableHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList ExpandableHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList ExpandableHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End
;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList CheapHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList BasicHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList Regular15HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Regular15HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Regular15HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Regular15HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList AdvancedHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList Advanced8HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Advanced8HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Advanced8HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Advanced8HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList EliteHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList EliteHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList EliteHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList EliteHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList EliteHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList EliteHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList EliteHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList EliteHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList EliteHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList Elite3HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Elite3HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Elite3HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Elite3HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList Elite3HordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList Elite3HordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList Elite3HordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList Elite3HordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList Elite3HordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_RegularInfantryHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_EliteInfantryHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList BasicCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList AdvancedCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList EliteCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList EliteCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList EliteCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList EliteCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList EliteCavHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList EliteCavHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList EliteCavHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList EliteCavHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList EliteCavHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList CheapBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList BasicBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

