
	Behavior = SpecialAbilityUpdate ModuleTag_ChargeUpdate
		SpecialPowerTemplate		= SpecialAbilityDwarvenCharge
		StartAbilityRange			= 150.0
		AbilityAbortRange			= 50.0
		PreparationTime				= 0
		PackTime					= 3000
		TriggerSound				= DwarfBullRushMS
		TriggerAttributeModifier	= DwarvenChargeBonus
		AttributeModifierDuration	= 10000
		ChargeAttackSpeedBoost		= Yes
		IgnoreFacingCheck			= Yes
	End


