   	Behavior = LargeGroupBonusUpdate ModuleTag_PopCenter1
		UpdateRate		= 1000
		HordeMemberFilter	= NONE +DEPRECATED
		Count			= 2
		Radius			= 500
		RubOffRadius		= 50
		AlliesOnly		= Yes
		AttributeModifier	= PopCenterBonus1
    End

    Behavior = LargeGroupBonusUpdate ModuleTag_PopCenter2
		UpdateRate		= 1000
		HordeMemberFilter	= NONE +DEPRECATED
		Count			= 4
		Radius			= 500
		RubOffRadius		= 50
		AlliesOnly		= Yes
		AttributeModifier	= PopCenterBonus2
    End

    Behavior = LargeGroupBonusUpdate ModuleTag_PopCenter3
		UpdateRate		= 1000
		HordeMemberFilter	= NONE +DEPRECATED
		Count			= 6
		Radius			= 500
		RubOffRadius		= 50
		AlliesOnly		= Yes
		AttributeModifier	= PopCenterBonus3
    End

    Behavior = LargeGroupBonusUpdate ModuleTag_PopCenter4
		UpdateRate		= 1000
		HordeMemberFilter	= NONE +DEPRECATED
		Count			= 8
		Radius			= 500
		RubOffRadius		= 50
		AlliesOnly		= Yes
		AttributeModifier	= PopCenterBonus4
    End

    Behavior = LargeGroupBonusUpdate ModuleTag_PopCenter5
		UpdateRate		= 1000
		HordeMemberFilter	= NONE +DEPRECATED
		Count			= 10
		Radius			= 500
		RubOffRadius		= 50
		AlliesOnly		= Yes
		AttributeModifier	= PopCenterBonus2
    End

    ;#include"..\..\..\Includes\Populationcenter.inc"