

	EvaEventDamagedOwner	= UnitUnderAttack
	EvaEventDamagedFromShroudedSourceOwner = UnitUnderAttackFromShroudedUnit
	EvaEventDamagedByFireOwner  = GenericUnitBeingBurned
	EvaEventAmbushed = UnitAmbushed
	EvaEventSecondDamageFarFromFirstOwner = UnitUnderAttackAgain


	EvaEventSecondDamageFarFromFirstScanRange = 600
	EvaEventSecondDamageFarFromFirstTimeoutMS = 31000

    EvaEnemyObjectSightedEvent	= GenericEnemyUnitSighted


