ModifierList ExpandableHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList ExpandableHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList ExpandableHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList ExpandableHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH EXPANDABLE_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD EXPANDABLE_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End
;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList CheapHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAP_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAP_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList BasicHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASIC_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASIC_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList Basic10HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASIC10_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASIC10_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Basic10HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASIC10_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASIC10_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Basic10HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASIC10_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASIC10_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Basic10HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASIC10_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASIC10_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList Regular15HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Regular15HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Regular15HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Regular15HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR15_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR15_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularImladrisHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL2 ImladrisFighterRank2 ImladrisBannerLeadership
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularImladrisHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularImladrisHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularImladrisHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList AdvancedHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList AdvancedImladrisHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED5_HORDE_HP_ADD_LVL2 ImladrisLancerRank2 ImladrisArcherRank2 ImladrisBannerLeadership
    Modifier = DAMAGE_ADD ADVANCED5_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedImladrisHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED5_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED5_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedImladrisHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED5_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED5_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedImladrisHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED5_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED5_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList AdvancedImladrisMagesHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED3_HORDE_HP_ADD_LVL2 ImladrisLancerRank2 ImladrisArcherRank2 ImladrisBannerLeadership
    Modifier = DAMAGE_ADD ADVANCED3_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedImladrisMagesHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED3_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED3_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedImladrisMagesHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED3_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED3_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedImladrisMagesHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED3_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED3_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList Advanced8HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Advanced8HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Advanced8HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Advanced8HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCED8_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCED8_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList EliteHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList EliteHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList EliteHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList EliteHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList EliteHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList EliteHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList EliteHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList EliteHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList EliteHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList Elite10HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Elite10HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Elite10HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Elite10HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList Elite10HordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList Elite10HordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList Elite10HordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList Elite10HordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList Elite10HordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE_10_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE_10_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList VeteransHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList VeteransHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList VeteransHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList VeteransHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList VeteransHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList VeteransHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList VeteransHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList VeteransHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList VeteransHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End
ModifierList VeteransHordeBonusRank11
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL11
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL11
    Duration = 0
End
ModifierList VeteransHordeBonusRank12
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL12
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL12
    Duration = 0
End
ModifierList VeteransHordeBonusRank13
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL13
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL13
    Duration = 0
End
ModifierList VeteransHordeBonusRank14
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL14
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL14
    Duration = 0
End
ModifierList VeteransHordeBonusRank15
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL15
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL15
    Duration = 0
End
ModifierList VeteransHordeBonusRank16
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL16
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL16
    Duration = 0
End
ModifierList VeteransHordeBonusRank17
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL17
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL17
    Duration = 0
End
ModifierList VeteransHordeBonusRank18
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL18
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL18
    Duration = 0
End
ModifierList VeteransHordeBonusRank19
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL19
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL19
    Duration = 0
End
ModifierList VeteransHordeBonusRank20
    Category = LEVEL
    Modifier = HEALTH VETERANS_HORDE_HP_ADD_LVL20
    Modifier = DAMAGE_ADD VETERANS_HORDE_DAMAGE_ADD_LVL20
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList Elite3HordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Elite3HordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Elite3HordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Elite3HordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList Elite3HordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList Elite3HordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList Elite3HordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList Elite3HordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList Elite3HordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE3_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE3_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList CheapChamponHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAP_CHAMPION_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapChamponHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAP_CHAMPION_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapChamponHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAP_CHAMPION_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapChamponHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAP_CHAMPION_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularChamponHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULAR_CHAMPION_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularChamponHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULAR_CHAMPION_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularChamponHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULAR_CHAMPION_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularChamponHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULAR_CHAMPION_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_RegularInfantryHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_RegularInfantryHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_EliteInfantryHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_EliteInfantryHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_RegularFlyingHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_RegularFlyingHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList First_Age_BetterFlyingHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_BetterFlyingHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList First_Age_LegendaryFlyingHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_LegendaryFlyingHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList First_Age_EliteMontserHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_EliteMontserHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList First_Age_LegendaryMontserHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_LegendaryMontserHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList First_Age_RegularBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_RegularBeastsHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList First_Age_BestBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank3
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank4
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank5
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank6
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank7
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank8
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank9
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList First_Age_BestBeastsHordeBonusBonusRank10
    Category = LEVEL
    Modifier = HEALTH FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList BasicCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList RegularCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList RegularCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList RegularCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList RegularCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH REGULARCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD REGULARCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


ModifierList AdvancedCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL2 ImladrisCavalryRank2 ImladrisBannerLeadership
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList Advanced5CavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV5_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList Advanced5CavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV5_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList Advanced5CavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV5_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList Advanced5CavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCEDCAV5_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList EliteCavHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList EliteCavHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList EliteCavHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList EliteCavHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

ModifierList EliteCavHordeBonusRank6
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL6
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL6
    Duration = 0
End

ModifierList EliteCavHordeBonusRank7
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL7
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL7
    Duration = 0
End

ModifierList EliteCavHordeBonusRank8
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL8
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL8
    Duration = 0
End

ModifierList EliteCavHordeBonusRank9
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL9
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL9
    Duration = 0
End

ModifierList EliteCavHordeBonusRank10
    Category = LEVEL
    Modifier = HEALTH ELITE_CAVALRY_HORDE_HP_ADD_LVL10
    Modifier = DAMAGE_ADD ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL10
    Duration = 0
End


;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList CheapBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapBeastsHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAPBEASTS_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList BasicBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICBEASTS_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICBEASTS_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End


;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ModifierList BasicBeastsHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicBeastsHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList CheapMonsterHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH CHEAPMONSTER_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList CheapMonsterHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH CHEAPMONSTER_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList CheapMonsterHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH CHEAPMONSTER_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList CheapMonsterHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH CHEAPMONSTER_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList BasicMonsterHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList BasicMonsterHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList BasicMonsterHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList BasicMonsterHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH BASICMONSTER_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD BASICMONSTER_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



ModifierList AdvancedMonsterHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ADVANCEDMONSTER_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList AdvancedMonsterHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ADVANCEDMONSTER_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList AdvancedMonsterHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ADVANCEDMONSTER_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList AdvancedMonsterHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ADVANCEDMONSTER_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------




ModifierList EliteMonsterHordeBonusRank2
    Category = LEVEL
    Modifier = HEALTH ELITEMONSTER_HORDE_HP_ADD_LVL2
    Modifier = DAMAGE_ADD ELITEMONSTER_HORDE_DAMAGE_ADD_LVL2
    Duration = 0
End

ModifierList EliteMonsterHordeBonusRank3
    Category = LEVEL
    Modifier = HEALTH ELITEMONSTER_HORDE_HP_ADD_LVL3
    Modifier = DAMAGE_ADD ELITEMONSTER_HORDE_DAMAGE_ADD_LVL3
    Duration = 0
End

ModifierList EliteMonsterHordeBonusRank4
    Category = LEVEL
    Modifier = HEALTH ELITEMONSTER_HORDE_HP_ADD_LVL4
    Modifier = DAMAGE_ADD ELITEMONSTER_HORDE_DAMAGE_ADD_LVL4
    Duration = 0
End

ModifierList EliteMonsterHordeBonusRank5
    Category = LEVEL
    Modifier = HEALTH ELITEMONSTER_HORDE_HP_ADD_LVL5
    Modifier = DAMAGE_ADD ELITEMONSTER_HORDE_DAMAGE_ADD_LVL5
    Duration = 0
End

;----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
















