ModifierList HandicapPercent5
    Category = LEVEL
    Modifier = DAMAGE_MULT 95%
    Modifier = SPELL_DAMAGE 95%
    Modifier = HEALTH_MULT 95%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent10
    Category = LEVEL
    Modifier = DAMAGE_MULT 90%
    Modifier = SPELL_DAMAGE 90%
    Modifier = HEALTH_MULT 90%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent15
    Category = LEVEL
    Modifier = DAMAGE_MULT 85%
    Modifier = SPELL_DAMAGE 85%
    Modifier = HEALTH_MULT 85%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent20
    Category = LEVEL
    Modifier = DAMAGE_MULT 80%
    Modifier = SPELL_DAMAGE 80%
    Modifier = HEALTH_MULT 80%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent25
    Category = LEVEL
    Modifier = DAMAGE_MULT 75%
    Modifier = SPELL_DAMAGE 75%
    Modifier = HEALTH_MULT 75%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent30
    Category = LEVEL
    Modifier = DAMAGE_MULT 70%
    Modifier = SPELL_DAMAGE 70%
    Modifier = HEALTH_MULT 70%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent35
    Category = LEVEL
    Modifier = DAMAGE_MULT 65%
    Modifier = SPELL_DAMAGE 65%
    Modifier = HEALTH_MULT 65%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent40
    Category = LEVEL
    Modifier = DAMAGE_MULT 60%
    Modifier = SPELL_DAMAGE 60%
    Modifier = HEALTH_MULT 60%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent45
    Category = LEVEL
    Modifier = DAMAGE_MULT 55%
    Modifier = SPELL_DAMAGE 55%
    Modifier = HEALTH_MULT 55%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent50
    Category = LEVEL
    Modifier = DAMAGE_MULT 50%
    Modifier = SPELL_DAMAGE 50%
    Modifier = HEALTH_MULT 50%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent55
    Category = LEVEL
    Modifier = DAMAGE_MULT 45%
    Modifier = SPELL_DAMAGE 45%
    Modifier = HEALTH_MULT 45%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent60
    Category = LEVEL
    Modifier = DAMAGE_MULT 40%
    Modifier = SPELL_DAMAGE 40%
    Modifier = HEALTH_MULT 40%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent65
    Category = LEVEL
    Modifier = DAMAGE_MULT 35%
    Modifier = SPELL_DAMAGE 35%
    Modifier = HEALTH_MULT 35%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent70
    Category = LEVEL
    Modifier = DAMAGE_MULT 30%
    Modifier = SPELL_DAMAGE 30%
    Modifier = HEALTH_MULT 30%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent75
    Category = LEVEL
    Modifier = DAMAGE_MULT 25%
    Modifier = SPELL_DAMAGE 25%
    Modifier = HEALTH_MULT 25%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent80
    Category = LEVEL
    Modifier = DAMAGE_MULT 20%
    Modifier = SPELL_DAMAGE 20%
    Modifier = HEALTH_MULT 20%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent85
    Category = LEVEL
    Modifier = DAMAGE_MULT 15%
    Modifier = SPELL_DAMAGE 15%
    Modifier = HEALTH_MULT 15%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent90
    Category = LEVEL
    Modifier = DAMAGE_MULT 10%
    Modifier = SPELL_DAMAGE 10%
    Modifier = HEALTH_MULT 10%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent95
    Category = LEVEL
    Modifier = DAMAGE_MULT 5%
    Modifier = SPELL_DAMAGE 5%
    Modifier = HEALTH_MULT 5%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End

ModifierList HandicapPercent100
    Category = LEVEL
    Modifier = DAMAGE_MULT 1%
    Modifier = SPELL_DAMAGE 1%
    Modifier = HEALTH_MULT 1%
    Modifier = RECHARGE_TIME 100%
    Duration = 0
End