CommandSet BalcmegCommandSet
	1    = Command_ToggleStance
    2      = Command_BalcmegLeadershipButton
    3      = Command_SpecialAbilityBalcmegCarnage
    4      = Command_SpecialAbilityHeartOfEvil
    5      = Command_SpecialAbilityBalcmegImmortal
    6      = Command_SpecialAbilityDestructionMark
	7	   = Command_SpecialAbilityBalcmegXPPassive
    12   = Command_CaptureBuilding
    13   = Command_AttackMove
    14   = Command_Stop
    16   = Command_SetStanceBattle
    17   = Command_SetStanceAggressive
    18   = Command_SetStanceHoldGround
End





CommandSet ImladrisFortressCommandset
    InitialVisible = 2
	1    = Command_PurchaseHouseofElrond
	2    = Command_PurchaseHouseofGilgalad
End

CommandSet ImladrisFortressCommandset2
    InitialVisible = 2
	1    = Command_PurchaseHouseofTheGoldenFlowerElrond
	2    = Command_PurchaseHouseofTheSilverFountElrond
End

CommandSet ImladrisFortressCommandset3
    InitialVisible = 2
	1    = Command_PurchaseHouseofTheGoldenFlowerGilgalad
	2    = Command_PurchaseHouseofTheSilverFountGilgalad
End


CommandSet HouseofTheGoldenFlowerElrondCommandSet
    InitialVisible = 6

    1    = Command_RingMechanikImladris
    2    = Command_SpielsystemImladris
    3    = Command_SelectUpgradesImladrisFaction
    4    = Command_SelectRevivablesImladrisFortress
    6    = Command_Sell

    7     = Command_ConstructImladrisPorter
    8     = Command_PurchaseUpgradeElvenFortressEnchantedAnvil
    9     = Command_PurchaseUpgradeElvenFortressBlessedMist
    10    = Command_PurchaseUpgradeElvenFortressCrystalMoat
    11    = Command_PurchaseUpgradeElvenFortressMysticFountains
    12    = Command_PurchaseUpgradeElvenFortressEaglesNest
    13    = Command_RadialBack

       14    = Command_FakeRingHeroReviveSlot
       15    = Command_FakeCreateAHeroReviveSlot
       16    = Command_GenericReviveSlot1
       17    = Command_GenericReviveSlot2
       18    = Command_GenericReviveSlot3
       19    = Command_GenericReviveSlot4
       20    = Command_GenericReviveSlot5
       21    = Command_FakeHeroReviveSlot6
       22    = Command_GenericReviveSlot7
       23    = Command_FakeHeroReviveSlot8
       24    = Command_FakeHeroReviveSlot9
       25    = Command_GwaihirReviveSlot
       26    = Command_FakeHeroReviveSlot11
       27    = Command_FakeHeroReviveSlot12
	   28    = Command_FakeHeroReviveSlot13
       29    = Command_RadialBack
End

CommandSet HouseofTheSilverFountElrondCommandSet
    InitialVisible = 6

    1    = Command_RingMechanikImladris
    2    = Command_SpielsystemImladris
    3    = Command_SelectUpgradesImladrisFaction
    4    = Command_SelectRevivablesImladrisFortress
    6    = Command_Sell

    7     = Command_ConstructImladrisPorter
    8     = Command_PurchaseUpgradeElvenFortressEnchantedAnvil
    9     = Command_PurchaseUpgradeElvenFortressBlessedMist
    10    = Command_PurchaseUpgradeElvenFortressCrystalMoat
    11    = Command_PurchaseUpgradeElvenFortressMysticFountains
    12    = Command_PurchaseUpgradeElvenFortressEaglesNest
    13    = Command_RadialBack

       14    = Command_FakeRingHeroReviveSlot
       15    = Command_FakeCreateAHeroReviveSlot
       16    = Command_GenericReviveSlot1
       17    = Command_GenericReviveSlot2
       18    = Command_GenericReviveSlot3
       19    = Command_GenericReviveSlot4
       20    = Command_FakeHeroReviveSlot5
       21    = Command_FakeHeroReviveSlot6
       22    = Command_GenericReviveSlot7
       23    = Command_FakeHeroReviveSlot8
       24    = Command_FakeHeroReviveSlot9
       25    = Command_GwaihirReviveSlot
       26    = Command_FakeHeroReviveSlot11
       27    = Command_FakeHeroReviveSlot12
	   28    = Command_GenericReviveSlot13
       29    = Command_RadialBack
End


CommandSet HouseofTheGoldenFlowerGilgaladCommandSet
    InitialVisible = 6

    1    = Command_RingMechanikImladris
    2    = Command_SpielsystemImladris
    3    = Command_SelectUpgradesImladrisFaction
    4    = Command_SelectRevivablesImladrisFortress
    6    = Command_Sell

    7     = Command_ConstructImladrisPorter
    8     = Command_PurchaseUpgradeElvenFortressEnchantedAnvil
    9     = Command_PurchaseUpgradeElvenFortressBlessedMist
    10    = Command_PurchaseUpgradeElvenFortressCrystalMoat
    11    = Command_PurchaseUpgradeElvenFortressMysticFountains
    12    = Command_PurchaseUpgradeElvenFortressEaglesNest
    13    = Command_RadialBack

       14    = Command_FakeRingHeroReviveSlot
       15    = Command_FakeCreateAHeroReviveSlot
       16    = Command_FakeHeroReviveSlot1
       17    = Command_GenericReviveSlot2
       18    = Command_GenericReviveSlot3
       19    = Command_GenericReviveSlot4
       20    = Command_GenericReviveSlot5
       21    = Command_FakeHeroReviveSlot6
       22    = Command_GenericReviveSlot7
       23    = Command_FakeHeroReviveSlot8
       24    = Command_FakeHeroReviveSlot9
       25    = Command_GwaihirReviveSlot
       26    = Command_FakeHeroReviveSlot11
       27    = Command_GenericReviveSlot12
	   28    = Command_FakeHeroReviveSlot13
       29    = Command_RadialBack
End

CommandSet HouseofTheSilverFountGilgaladCommandSet
    InitialVisible = 6

    1    = Command_RingMechanikImladris
    2    = Command_SpielsystemImladris
    3    = Command_SelectUpgradesImladrisFaction
    4    = Command_SelectRevivablesImladrisFortress
    6    = Command_Sell

    7     = Command_ConstructImladrisPorter
    8     = Command_PurchaseUpgradeElvenFortressEnchantedAnvil
    9     = Command_PurchaseUpgradeElvenFortressBlessedMist
    10    = Command_PurchaseUpgradeElvenFortressCrystalMoat
    11    = Command_PurchaseUpgradeElvenFortressMysticFountains
    12    = Command_PurchaseUpgradeElvenFortressEaglesNest
    13    = Command_RadialBack

       14    = Command_FakeRingHeroReviveSlot
       15    = Command_FakeCreateAHeroReviveSlot
       16    = Command_FakeHeroReviveSlot1
       17    = Command_GenericReviveSlot2
       18    = Command_GenericReviveSlot3
       19    = Command_GenericReviveSlot4
       20    = Command_FakeHeroReviveSlot5
       21    = Command_FakeHeroReviveSlot6
       22    = Command_GenericReviveSlot7
       23    = Command_FakeHeroReviveSlot8
       24    = Command_FakeHeroReviveSlot9
       25    = Command_GwaihirReviveSlot
       26    = Command_FakeHeroReviveSlot11
       27    = Command_GenericReviveSlot12
	   28    = Command_GenericReviveSlot13
       29    = Command_RadialBack
End

CommandSet BelegostFortressCommandSet
    InitialVisible = 4
    1    = Command_SelectPowerfulSummonDwarves
    2    = Command_SelectRevivablesBelegostFortress
    3    = Command_SelectUnitsBelegostFortress
    4    = Command_UpgradeBelegostFortressLevel2

    5    = Command_ConstructNogrodSmite
    6    = Command_ConstructBelegostRiderHorde
    7    = Command_ConstructBelegostEliteHorde
    8    = Command_RadialBack

        9      = Command_FakeRingHeroReviveSlot
       10      = Command_FakeCreateAHeroReviveSlot
       11      = Command_FakeHeroReviveSlot1
       12      = Command_FakeHeroReviveSlot2
       13      = Command_FakeHeroReviveSlot3
       14      = Command_FakeHeroReviveSlot4
       15      = Command_FakeHeroReviveSlot5
       16      = Command_FakeHeroReviveSlot6
       17      = Command_FakeHeroReviveSlot7
       18      = Command_FakeHeroReviveSlot8
       19      = Command_FakeHeroReviveSlot9
       20      = Command_FakeHeroReviveSlot10
       21      = Command_FakeHeroReviveSlot11
       22      = Command_FakeHeroReviveSlot12
       23      = Command_FakeHeroReviveSlot13
       24      = Command_FakeHeroReviveSlot14
       25      = Command_GenericReviveSlot15
       26      = Command_GenericReviveSlot16
       27      = Command_FakeHeroReviveSlot9
       28      = Command_FakeHeroReviveSlot18
       29      = Command_FakeHeroReviveSlot19
       30      = Command_FakeHeroReviveSlot20
       31      = Command_GenericReviveSlot21

    32  = Command_SummonValinorAule
    33  = Command_RadialBack
End

CommandSet BelegostFortressCommandSetLevel2
    InitialVisible = 4
    1    = Command_SelectPowerfulSummonDwarves
    2    = Command_SelectRevivablesBelegostFortress
    3    = Command_SelectUnitsBelegostFortress
    4    = Command_UpgradeBelegostFortressLevel3

    5    = Command_ConstructNogrodSmite
    6    = Command_ConstructBelegostRiderHorde
    7    = Command_ConstructBelegostEliteHorde
    8    = Command_RadialBack

        9      = Command_FakeRingHeroReviveSlot
       10      = Command_FakeCreateAHeroReviveSlot
       11      = Command_FakeHeroReviveSlot1
       12      = Command_FakeHeroReviveSlot2
       13      = Command_FakeHeroReviveSlot3
       14      = Command_FakeHeroReviveSlot4
       15      = Command_FakeHeroReviveSlot5
       16      = Command_FakeHeroReviveSlot6
       17      = Command_FakeHeroReviveSlot7
       18      = Command_FakeHeroReviveSlot8
       19      = Command_FakeHeroReviveSlot9
       20      = Command_FakeHeroReviveSlot10
       21      = Command_FakeHeroReviveSlot11
       22      = Command_FakeHeroReviveSlot12
       23      = Command_FakeHeroReviveSlot13
       24      = Command_FakeHeroReviveSlot14
       25      = Command_GenericReviveSlot15
       26      = Command_GenericReviveSlot16
       27      = Command_FakeHeroReviveSlot9
       28      = Command_FakeHeroReviveSlot18
       29      = Command_FakeHeroReviveSlot19
       30      = Command_FakeHeroReviveSlot20
       31      = Command_GenericReviveSlot21
       
    32  = Command_SummonValinorAule
    33  = Command_RadialBack
End

CommandSet BelegostFortressCommandSetLevel3
InitialVisible = 4
    1    = Command_SelectPowerfulSummonDwarves
    2    = Command_SelectRevivablesBelegostFortress
    3    = Command_SelectUnitsBelegostFortress
    4    = Command_UpgradeBelegostFortressLevel4

    5    = Command_ConstructNogrodSmite
    6    = Command_ConstructBelegostRiderHorde
    7    = Command_ConstructBelegostEliteHorde
    8    = Command_RadialBack

        9      = Command_FakeRingHeroReviveSlot
       10      = Command_FakeCreateAHeroReviveSlot
       11      = Command_FakeHeroReviveSlot1
       12      = Command_FakeHeroReviveSlot2
       13      = Command_FakeHeroReviveSlot3
       14      = Command_FakeHeroReviveSlot4
       15      = Command_FakeHeroReviveSlot5
       16      = Command_FakeHeroReviveSlot6
       17      = Command_FakeHeroReviveSlot7
       18      = Command_FakeHeroReviveSlot8
       19      = Command_FakeHeroReviveSlot9
       20      = Command_FakeHeroReviveSlot10
       21      = Command_FakeHeroReviveSlot11
       22      = Command_FakeHeroReviveSlot12
       23      = Command_FakeHeroReviveSlot13
       24      = Command_FakeHeroReviveSlot14
       25      = Command_GenericReviveSlot15
       26      = Command_GenericReviveSlot16
       27      = Command_FakeHeroReviveSlot9
       28      = Command_FakeHeroReviveSlot18
       29      = Command_FakeHeroReviveSlot19
       30      = Command_FakeHeroReviveSlot20
       31      = Command_GenericReviveSlot21
       
    32  = Command_SummonValinorAule
    33  = Command_RadialBack
End

CommandSet BelegostFortressCommandSetLevel4
InitialVisible = 4
    1    = Command_SelectPowerfulSummonDwarves
    2    = Command_SelectRevivablesBelegostFortress
    3    = Command_SelectUnitsBelegostFortress
    4    = Command_UpgradeBelegostFortressLevel5

    5    = Command_ConstructNogrodSmite
    6    = Command_ConstructBelegostRiderHorde
    7    = Command_ConstructBelegostEliteHorde
    8    = Command_RadialBack

        9      = Command_FakeRingHeroReviveSlot
       10      = Command_FakeCreateAHeroReviveSlot
       11      = Command_FakeHeroReviveSlot1
       12      = Command_FakeHeroReviveSlot2
       13      = Command_FakeHeroReviveSlot3
       14      = Command_FakeHeroReviveSlot4
       15      = Command_FakeHeroReviveSlot5
       16      = Command_FakeHeroReviveSlot6
       17      = Command_FakeHeroReviveSlot7
       18      = Command_FakeHeroReviveSlot8
       19      = Command_FakeHeroReviveSlot9
       20      = Command_FakeHeroReviveSlot10
       21      = Command_FakeHeroReviveSlot11
       22      = Command_FakeHeroReviveSlot12
       23      = Command_FakeHeroReviveSlot13
       24      = Command_FakeHeroReviveSlot14
       25      = Command_GenericReviveSlot15
       26      = Command_GenericReviveSlot16
       27      = Command_FakeHeroReviveSlot9
       28      = Command_FakeHeroReviveSlot18
       29      = Command_FakeHeroReviveSlot19
       30      = Command_FakeHeroReviveSlot20
       31      = Command_GenericReviveSlot21
       
    32  = Command_SummonValinorAule
    33  = Command_RadialBack
End

CommandSet BelegostFortressCommandSetLevel5
    InitialVisible = 4
    1    = Command_SelectPowerfulSummonDwarves
    2    = Command_SelectRevivablesBelegostFortress
    3    = Command_SelectUnitsBelegostFortress
    4    = Command_BelegostFortressRebuild

    5    = Command_ConstructNogrodSmite
    6    = Command_ConstructBelegostRiderHorde
    7    = Command_ConstructBelegostEliteHorde
    8    = Command_RadialBack

        9      = Command_FakeRingHeroReviveSlot
       10      = Command_FakeCreateAHeroReviveSlot
       11      = Command_FakeHeroReviveSlot1
       12      = Command_FakeHeroReviveSlot2
       13      = Command_FakeHeroReviveSlot3
       14      = Command_FakeHeroReviveSlot4
       15      = Command_FakeHeroReviveSlot5
       16      = Command_FakeHeroReviveSlot6
       17      = Command_FakeHeroReviveSlot7
       18      = Command_FakeHeroReviveSlot8
       19      = Command_FakeHeroReviveSlot9
       20      = Command_FakeHeroReviveSlot10
       21      = Command_FakeHeroReviveSlot11
       22      = Command_FakeHeroReviveSlot12
       23      = Command_FakeHeroReviveSlot13
       24      = Command_FakeHeroReviveSlot14
       25      = Command_GenericReviveSlot15
       26      = Command_GenericReviveSlot16
       27      = Command_FakeHeroReviveSlot9
       28      = Command_FakeHeroReviveSlot18
       29      = Command_FakeHeroReviveSlot19
       30      = Command_FakeHeroReviveSlot20
       31      = Command_GenericReviveSlot21
       
    32  = Command_SummonValinorAule
    33  = Command_RadialBack
End


CommandSet ArmenelosFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonArnor
    2    = Command_SelectRevivablesArmenelosFortress
    3    = Command_SelectSpellArmenelosFortress
    4    = Command_SelectUnitsArmenelosFortress
    5    = Command_UpgradeFirstAgeFortressLevel2_Arnor
    6    = Command_SummonNumenorArmy

    7    = Command_RadialBack
    8    = Command_ArmenelosFortressLeadership
    9    = Command_ArmenelosFortressBanner
   10    = Command_ArmenelosFortressFountein
   11    = Command_ArmenelosFortressFire
   12    = Command_ArmenelosFortressWhiteTree

   13    = Command_ConstructNumenorCrossbowHorde
   14    = Command_ConstructNumenorGuardHorde
   15    = Command_ConstructNumenorWarriorHorde
   16    = Command_RadialBack

   17    = Command_FakeRingHeroReviveSlot
   18    = Command_FakeCreateAHeroReviveSlot
   19    = Command_FakeHeroReviveSlot1
   20    = Command_FakeHeroReviveSlot2
   21    = Command_FakeHeroReviveSlot3
   22    = Command_GenericReviveSlot4
   23    = Command_FakeHeroReviveSlot5
   24    = Command_FakeHeroReviveSlot6
   25    = Command_FakeHeroReviveSlot7
   26    = Command_GenericReviveSlot8
   27    = Command_GenericReviveSlot9
   28    = Command_FakeHeroReviveSlot10
   29    = Command_FakeHeroReviveSlot11
   30    = Command_FakeHeroReviveSlot12
   31    = Command_FakeGilGaladReviveSlot
   32    = Command_RadialBack
     
End

CommandSet ArmenelosFortressCommandSetLevel2
     InitialVisible = 5
    1    = Command_SelectPowerfulSummonArnor
    2    = Command_SelectRevivablesArmenelosFortress
    3    = Command_SelectSpellArmenelosFortress
    4    = Command_SelectUnitsArmenelosFortress
    5    = Command_UpgradeFirstAgeFortressLevel3_Arnor
    6    = Command_SummonNumenorArmy

    7    = Command_RadialBack
    8    = Command_ArmenelosFortressLeadership
    9    = Command_ArmenelosFortressBanner
   10    = Command_ArmenelosFortressFountein
   11    = Command_ArmenelosFortressFire
   12    = Command_ArmenelosFortressWhiteTree

   13    = Command_ConstructNumenorCrossbowHorde
   14    = Command_ConstructNumenorGuardHorde
   15    = Command_ConstructNumenorWarriorHorde
   16    = Command_RadialBack

   17    = Command_FakeRingHeroReviveSlot
   18    = Command_FakeCreateAHeroReviveSlot
   19    = Command_FakeHeroReviveSlot1
   20    = Command_FakeHeroReviveSlot2
   21    = Command_FakeHeroReviveSlot3
   22    = Command_GenericReviveSlot4
   23    = Command_FakeHeroReviveSlot5
   24    = Command_FakeHeroReviveSlot6
   25    = Command_FakeHeroReviveSlot7
   26    = Command_GenericReviveSlot8
   27    = Command_GenericReviveSlot9
   28    = Command_FakeHeroReviveSlot10
   29    = Command_FakeHeroReviveSlot11
   30    = Command_FakeHeroReviveSlot12
   31    = Command_FakeGilGaladReviveSlot
   32    = Command_RadialBack
End

CommandSet ArmenelosFortressCommandSetLevel3
     InitialVisible = 5
    1    = Command_SelectPowerfulSummonArnor
    2    = Command_SelectRevivablesArmenelosFortress
    3    = Command_SelectSpellArmenelosFortress
    4    = Command_SelectUnitsArmenelosFortress
    5    = Command_UpgradeFirstAgeFortressLevel4_Arnor
    6    = Command_SummonNumenorArmy

    7    = Command_RadialBack
    8    = Command_ArmenelosFortressLeadership
    9    = Command_ArmenelosFortressBanner
   10    = Command_ArmenelosFortressFountein
   11    = Command_ArmenelosFortressFire
   12    = Command_ArmenelosFortressWhiteTree

   13    = Command_ConstructNumenorCrossbowHorde
   14    = Command_ConstructNumenorGuardHorde
   15    = Command_ConstructNumenorWarriorHorde
   16    = Command_RadialBack

   17    = Command_FakeRingHeroReviveSlot
   18    = Command_FakeCreateAHeroReviveSlot
   19    = Command_FakeHeroReviveSlot1
   20    = Command_FakeHeroReviveSlot2
   21    = Command_FakeHeroReviveSlot3
   22    = Command_GenericReviveSlot4
   23    = Command_FakeHeroReviveSlot5
   24    = Command_FakeHeroReviveSlot6
   25    = Command_FakeHeroReviveSlot7
   26    = Command_GenericReviveSlot8
   27    = Command_GenericReviveSlot9
   28    = Command_FakeHeroReviveSlot10
   29    = Command_FakeHeroReviveSlot11
   30    = Command_FakeHeroReviveSlot12
   31    = Command_FakeGilGaladReviveSlot
   32    = Command_RadialBack
End

CommandSet ArmenelosFortressCommandSetLevel4
      InitialVisible = 5
    1    = Command_SelectPowerfulSummonArnor
    2    = Command_SelectRevivablesArmenelosFortress
    3    = Command_SelectSpellArmenelosFortress
    4    = Command_SelectUnitsArmenelosFortress
    5    = Command_UpgradeFirstAgeFortressLevel5_Arnor
    6    = Command_SummonNumenorArmy

    7    = Command_RadialBack
    8    = Command_ArmenelosFortressLeadership
    9    = Command_ArmenelosFortressBanner
   10    = Command_ArmenelosFortressFountein
   11    = Command_ArmenelosFortressFire
   12    = Command_ArmenelosFortressWhiteTree

   13    = Command_ConstructNumenorCrossbowHorde
   14    = Command_ConstructNumenorGuardHorde
   15    = Command_ConstructNumenorWarriorHorde
   16    = Command_RadialBack

   17    = Command_FakeRingHeroReviveSlot
   18    = Command_FakeCreateAHeroReviveSlot
   19    = Command_FakeHeroReviveSlot1
   20    = Command_FakeHeroReviveSlot2
   21    = Command_FakeHeroReviveSlot3
   22    = Command_GenericReviveSlot4
   23    = Command_FakeHeroReviveSlot5
   24    = Command_FakeHeroReviveSlot6
   25    = Command_FakeHeroReviveSlot7
   26    = Command_GenericReviveSlot8
   27    = Command_GenericReviveSlot9
   28    = Command_FakeHeroReviveSlot10
   29    = Command_FakeHeroReviveSlot11
   30    = Command_FakeHeroReviveSlot12
   31    = Command_FakeGilGaladReviveSlot
   32    = Command_RadialBack
End

CommandSet ArmenelosFortressCommandSetLevel5
 InitialVisible = 4
    1    = Command_SelectPowerfulSummonArnor
    2    = Command_SelectRevivablesArmenelosFortress
    3    = Command_SelectSpellArmenelosFortress
    4    = Command_SelectUnitsArmenelosFortress
    6    = Command_SummonNumenorArmy

    7    = Command_RadialBack
    8    = Command_ArmenelosFortressLeadership
    9    = Command_ArmenelosFortressBanner
   10    = Command_ArmenelosFortressFountein
   11    = Command_ArmenelosFortressFire
   12    = Command_ArmenelosFortressWhiteTree

   13    = Command_ConstructNumenorCrossbowHorde
   14    = Command_ConstructNumenorGuardHorde
   15    = Command_ConstructNumenorWarriorHorde
   16    = Command_RadialBack

   17    = Command_FakeRingHeroReviveSlot
   18    = Command_FakeCreateAHeroReviveSlot
   19    = Command_FakeHeroReviveSlot1
   20    = Command_FakeHeroReviveSlot2
   21    = Command_FakeHeroReviveSlot3
   22    = Command_GenericReviveSlot4
   23    = Command_FakeHeroReviveSlot5
   24    = Command_FakeHeroReviveSlot6
   25    = Command_FakeHeroReviveSlot7
   26    = Command_GenericReviveSlot8
   27    = Command_GenericReviveSlot9
   28    = Command_FakeHeroReviveSlot10
   29    = Command_FakeHeroReviveSlot11
   30    = Command_FakeHeroReviveSlot12
   31    = Command_FakeGilGaladReviveSlot
   32    = Command_RadialBack
End

CommandSet TaniquetilFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonRohan
    2    = Command_SelectRevivablesTaniquetilFortress
    3    = Command_SelectSpellsTaniquetilFortress
    4    = Command_SelectUnitsTaniquetilFortress
    5    = Command_UpgradeTaniquetilFortressLevel2
    6    = Command_SummonValinorEonwe

    7    = Command_RadialBack
    8    = Command_TaniquetilFortressLeadeship
    9    = Command_TaniquetilFortressExtinguishFire
   ;10    = Command_TaniquetilFortressRebuild
   11    = Command_TaniquetilFortressSummonEagle


   12    = Command_ConstructTaniquetilGuardHorde
   13    = Command_ConstructTaniquetilWatcherHorde
   14    = Command_ConstructTaniquetilCaptian
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeEorlReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_FakeHeroReviveSlot8
       27    = Command_FakeHeroReviveSlot9
       28    = Command_GenericReviveSlot10
       29    = Command_GenericReviveSlot11
       30    = Command_GenericReviveSlot12
       31    = Command_FakeHammerHandReviveSlot
       32    = Command_RadialBack
End

CommandSet TaniquetilFortressCommandSetLevel2
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonRohan
    2    = Command_SelectRevivablesTaniquetilFortress
    3    = Command_SelectSpellsTaniquetilFortress
    4    = Command_SelectUnitsTaniquetilFortress
    5    = Command_UpgradeTaniquetilFortressLevel3
    6    = Command_SummonValinorEonwe

    7    = Command_RadialBack
    8    = Command_TaniquetilFortressLeadeship
    9    = Command_TaniquetilFortressExtinguishFire
   ;10    = Command_TaniquetilFortressRebuild
   11    = Command_TaniquetilFortressSummonEagle


   12    = Command_ConstructTaniquetilGuardHorde
   13    = Command_ConstructTaniquetilWatcherHorde
   14    = Command_ConstructTaniquetilCaptian
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeEorlReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_FakeHeroReviveSlot8
       27    = Command_FakeHeroReviveSlot9
       28    = Command_GenericReviveSlot10
       29    = Command_GenericReviveSlot11
       30    = Command_GenericReviveSlot12
       31    = Command_FakeHammerHandReviveSlot
       32    = Command_RadialBack
End

CommandSet TaniquetilFortressCommandSetLevel3
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonRohan
    2    = Command_SelectRevivablesTaniquetilFortress
    3    = Command_SelectSpellsTaniquetilFortress
    4    = Command_SelectUnitsTaniquetilFortress
    5    = Command_UpgradeTaniquetilFortressLevel4
    6    = Command_SummonValinorEonwe

    7    = Command_RadialBack
    8    = Command_TaniquetilFortressLeadeship
    9    = Command_TaniquetilFortressExtinguishFire
   ;10    = Command_TaniquetilFortressRebuild
   11    = Command_TaniquetilFortressSummonEagle


   12    = Command_ConstructTaniquetilGuardHorde
   13    = Command_ConstructTaniquetilWatcherHorde
   14    = Command_ConstructTaniquetilCaptian
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeEorlReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_FakeHeroReviveSlot8
       27    = Command_FakeHeroReviveSlot9
       28    = Command_GenericReviveSlot10
       29    = Command_GenericReviveSlot11
       30    = Command_GenericReviveSlot12
       31    = Command_FakeHammerHandReviveSlot
       32    = Command_RadialBack
End

CommandSet TaniquetilFortressCommandSetLevel4
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonRohan
    2    = Command_SelectRevivablesTaniquetilFortress
    3    = Command_SelectSpellsTaniquetilFortress
    4    = Command_SelectUnitsTaniquetilFortress
    5    = Command_UpgradeTaniquetilFortressLevel5
    6    = Command_SummonValinorEonwe

    7    = Command_RadialBack
    8    = Command_TaniquetilFortressLeadeship
    9    = Command_TaniquetilFortressExtinguishFire
   ;10    = Command_TaniquetilFortressRebuild
   11    = Command_TaniquetilFortressSummonEagle


   12    = Command_ConstructTaniquetilGuardHorde
   13    = Command_ConstructTaniquetilWatcherHorde
   14    = Command_ConstructTaniquetilCaptian
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeEorlReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_FakeHeroReviveSlot8
       27    = Command_FakeHeroReviveSlot9
       28    = Command_GenericReviveSlot10
       29    = Command_GenericReviveSlot11
       30    = Command_GenericReviveSlot12
       31    = Command_FakeHammerHandReviveSlot
       32    = Command_RadialBack

End

CommandSet TaniquetilFortressCommandSetLevel5
    InitialVisible = 4
    1    = Command_SelectPowerfulSummonRohan
    2    = Command_SelectRevivablesTaniquetilFortress
    3    = Command_SelectSpellsTaniquetilFortress
    4    = Command_SelectUnitsTaniquetilFortress
    6    = Command_SummonValinorEonwe

    7    = Command_RadialBack
    8    = Command_TaniquetilFortressLeadeship
    9    = Command_TaniquetilFortressExtinguishFire
   10    = Command_TaniquetilFortressRebuild
   11    = Command_TaniquetilFortressSummonEagle


   12    = Command_ConstructTaniquetilGuardHorde
   13    = Command_ConstructTaniquetilWatcherHorde
   14    = Command_ConstructTaniquetilCaptian
   15    = Command_ConstructTaniquetilExpeditionaryHorde

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeEorlReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_FakeHeroReviveSlot8
       27    = Command_FakeHeroReviveSlot9
       28    = Command_GenericReviveSlot10
       29    = Command_GenericReviveSlot11
       30    = Command_GenericReviveSlot12
       31    = Command_FakeHammerHandReviveSlot
       32    = Command_RadialBack
End


CommandSet DorthonionFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonGondor
    2    = Command_SelectRevivablesDorthonionFortress
    3    = Command_SelectDorthonionFortressUpgrades
    4    = Command_SelectUnitsDorthonionFortress
    5    = Command_UpgradeFirstAgeFortressLevel2_Gondor
    
    6    = Command_SummonValinorManwe

    7    = Command_RadialBack
    8    = Command_SpecialLeadershipEagleBonus
    9    = Command_SpecialLeadershipHealingBonus
    10   = Command_SpecialLeadershipResistanceBonus
    11   = Command_SpecialLeadershipHeroBonus

   12    = Command_ConstructEdainOutlawBarahirEliteHorde
   13    = Command_BuildNargothrondHammerHordeFort
   14    = Command_ConstructEdainOutlawBarahirHorde
   15    = Command_ConstructValinorEagle
   16    = Command_RadialBack

     17    = Command_FakeRingHeroReviveSlot
     18    = Command_FakeCreateAHeroReviveSlot
     19    = Command_FakeHeroReviveSlot1
     20    = Command_FakeHeroReviveSlot2
     21    = Command_FakeHeroReviveSlot3
     22    = Command_FakeHeroReviveSlot4
     23    = Command_FakeHeroReviveSlot5
     24    = Command_FakeHeroReviveSlot6
     25    = Command_FakeHeroReviveSlot7
     26    = Command_GenericReviveSlot8
     27    = Command_GenericReviveSlot9
     28    = Command_GenericReviveSlot10
     29    = Command_FinrodReviveSlot
     30    = Command_FakeHeroReviveSlot12
     31    = Command_RadialBack
End

CommandSet DorthonionFortressCommandSetLevel2
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonGondor
    2    = Command_SelectRevivablesDorthonionFortress
    3    = Command_SelectDorthonionFortressUpgrades
    4    = Command_SelectUnitsDorthonionFortress
    5    = Command_UpgradeFirstAgeFortressLevel3_Gondor
    
    6    = Command_SummonValinorManwe

    7    = Command_RadialBack
    8    = Command_SpecialLeadershipEagleBonus
    9    = Command_SpecialLeadershipHealingBonus
    10   = Command_SpecialLeadershipResistanceBonus
    11   = Command_SpecialLeadershipHeroBonus

   12    = Command_ConstructEdainOutlawBarahirEliteHorde
   13    = Command_BuildNargothrondHammerHordeFort
   14    = Command_ConstructEdainOutlawBarahirHorde
   15    = Command_ConstructValinorEagle
   16    = Command_RadialBack

     17    = Command_FakeRingHeroReviveSlot
     18    = Command_FakeCreateAHeroReviveSlot
     19    = Command_FakeHeroReviveSlot1
     20    = Command_FakeHeroReviveSlot2
     21    = Command_FakeHeroReviveSlot3
     22    = Command_FakeHeroReviveSlot4
     23    = Command_FakeHeroReviveSlot5
     24    = Command_FakeHeroReviveSlot6
     25    = Command_FakeHeroReviveSlot7
     26    = Command_GenericReviveSlot8
     27    = Command_GenericReviveSlot9
     28    = Command_GenericReviveSlot10
     29    = Command_FinrodReviveSlot
     30    = Command_FakeHeroReviveSlot12
     31    = Command_RadialBack
End

CommandSet DorthonionFortressCommandSetLevel3
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonGondor
    2    = Command_SelectRevivablesDorthonionFortress
    3    = Command_SelectDorthonionFortressUpgrades
    4    = Command_SelectUnitsDorthonionFortress
    5    = Command_UpgradeFirstAgeFortressLevel4_Gondor
    
    6    = Command_SummonValinorManwe

    7    = Command_RadialBack
    8    = Command_SpecialLeadershipEagleBonus
    9    = Command_SpecialLeadershipHealingBonus
    10   = Command_SpecialLeadershipResistanceBonus
    11   = Command_SpecialLeadershipHeroBonus

   12    = Command_ConstructEdainOutlawBarahirEliteHorde
   13    = Command_BuildNargothrondHammerHordeFort
   14    = Command_ConstructEdainOutlawBarahirHorde
   15    = Command_ConstructValinorEagle
   16    = Command_RadialBack

     17    = Command_FakeRingHeroReviveSlot
     18    = Command_FakeCreateAHeroReviveSlot
     19    = Command_FakeHeroReviveSlot1
     20    = Command_FakeHeroReviveSlot2
     21    = Command_FakeHeroReviveSlot3
     22    = Command_FakeHeroReviveSlot4
     23    = Command_FakeHeroReviveSlot5
     24    = Command_FakeHeroReviveSlot6
     25    = Command_FakeHeroReviveSlot7
     26    = Command_GenericReviveSlot8
     27    = Command_GenericReviveSlot9
     28    = Command_GenericReviveSlot10
     29    = Command_FinrodReviveSlot
     30    = Command_FakeHeroReviveSlot12
     31    = Command_RadialBack
End

CommandSet DorthonionFortressCommandSetLevel4
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonGondor
    2    = Command_SelectRevivablesDorthonionFortress
    3    = Command_SelectDorthonionFortressUpgrades
    4    = Command_SelectUnitsDorthonionFortress
    5    = Command_UpgradeFirstAgeFortressLevel5_Gondor
    
    6    = Command_SummonValinorManwe

    7    = Command_RadialBack
    8    = Command_SpecialLeadershipEagleBonus
    9    = Command_SpecialLeadershipHealingBonus
    10   = Command_SpecialLeadershipResistanceBonus
    11   = Command_SpecialLeadershipHeroBonus

   12    = Command_ConstructEdainOutlawBarahirEliteHorde
   13    = Command_BuildNargothrondHammerHordeFort
   14    = Command_ConstructEdainOutlawBarahirHorde
   15    = Command_ConstructValinorEagle
   16    = Command_RadialBack

     17    = Command_FakeRingHeroReviveSlot
     18    = Command_FakeCreateAHeroReviveSlot
     19    = Command_FakeHeroReviveSlot1
     20    = Command_FakeHeroReviveSlot2
     21    = Command_FakeHeroReviveSlot3
     22    = Command_FakeHeroReviveSlot4
     23    = Command_FakeHeroReviveSlot5
     24    = Command_FakeHeroReviveSlot6
     25    = Command_FakeHeroReviveSlot7
     26    = Command_GenericReviveSlot8
     27    = Command_GenericReviveSlot9
     28    = Command_GenericReviveSlot10
     29    = Command_FinrodReviveSlot
     30    = Command_FakeHeroReviveSlot12
     31    = Command_RadialBack
End

CommandSet DorthonionFortressCommandSetLevel5
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonGondor
    2    = Command_SelectRevivablesDorthonionFortress
    3    = Command_SelectDorthonionFortressUpgrades
    4    = Command_SelectUnitsDorthonionFortress
    
    6    = Command_SummonValinorManwe

    7    = Command_RadialBack
    8    = Command_SpecialLeadershipEagleBonus
    9    = Command_SpecialLeadershipHealingBonus
    10   = Command_SpecialLeadershipResistanceBonus
    11   = Command_SpecialLeadershipHeroBonus

   12    = Command_ConstructEdainOutlawBarahirEliteHorde
   13    = Command_BuildNargothrondHammerHordeFort
   14    = Command_ConstructEdainOutlawBarahirHorde
   15    = Command_ConstructValinorEagle
   16    = Command_RadialBack

     17    = Command_FakeRingHeroReviveSlot
     18    = Command_FakeCreateAHeroReviveSlot
     19    = Command_FakeHeroReviveSlot1
     20    = Command_FakeHeroReviveSlot2
     21    = Command_FakeHeroReviveSlot3
     22    = Command_FakeHeroReviveSlot4
     23    = Command_FakeHeroReviveSlot5
     24    = Command_FakeHeroReviveSlot6
     25    = Command_FakeHeroReviveSlot7
     26    = Command_GenericReviveSlot8
     27    = Command_GenericReviveSlot9
     28    = Command_GenericReviveSlot10
     29    = Command_FinrodReviveSlot
     30    = Command_FakeHeroReviveSlot12
     31    = Command_RadialBack
End

CommandSet TolinGaurhothFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonIsengard
    2    = Command_SelectRevivablesTolinGaurhothFortress
    3    = Command_SelectUpgradesTolinGaurhothFortress
    4    = Command_SelectUnitsTolinGaurhothFortress
    5    = Command_UpgradeTolinGaurhothFortressLevel2
    

    6    = Command_TolinGaurhothLeadership
    7    = Command_TolinGaurhothVampireCloud
    8    = Command_TolinGaurhothFlammingMunitions
    9    = Command_TolinGaurhothSorcery
   10    = Command_RadialBack

   11    = Command_ConstructTolinGaurhothVampiresHorde
   12    = Command_ConstructTolinGaurhothWolfHorde
   13    = Command_ConstructTolinGaurhothWereWolf
   14    = Command_ConstructTaurnuFuinGaurd
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_FakeHeroReviveSlot9
       27    = Command_FakeUldorReviveSlot
       28    = Command_GenericReviveSlot11
       29    = Command_GenericReviveSlot12
       30    = Command_FakeHeroReviveSlot13
       31    = Command_GenericReviveSlot14
       32    = Command_RadialBack

    33  = Command_SummonTolinGaurhothTarMairon
End

CommandSet TolinGaurhothFortressCommandSetLevel2
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonIsengard
    2    = Command_SelectRevivablesTolinGaurhothFortress
    3    = Command_SelectUpgradesTolinGaurhothFortress
    4    = Command_SelectUnitsTolinGaurhothFortress
    5    = Command_UpgradeTolinGaurhothFortressLevel3
    

    6    = Command_TolinGaurhothLeadership
    7    = Command_TolinGaurhothVampireCloud
    8    = Command_TolinGaurhothFlammingMunitions
    9    = Command_TolinGaurhothSorcery
   10    = Command_RadialBack

   11    = Command_ConstructTolinGaurhothVampiresHorde
   12    = Command_ConstructTolinGaurhothWolfHorde
   13    = Command_ConstructTolinGaurhothWereWolf
   14    = Command_ConstructTaurnuFuinGaurd
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_FakeHeroReviveSlot9
       27    = Command_FakeUldorReviveSlot
       28    = Command_GenericReviveSlot11
       29    = Command_GenericReviveSlot12
       30    = Command_FakeHeroReviveSlot13
       31    = Command_GenericReviveSlot14
       32    = Command_RadialBack

    33  = Command_SummonTolinGaurhothTarMairon
End


CommandSet TolinGaurhothFortressCommandSetLevel3
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonIsengard
    2    = Command_SelectRevivablesTolinGaurhothFortress
    3    = Command_SelectUpgradesTolinGaurhothFortress
    4    = Command_SelectUnitsTolinGaurhothFortress
    5    = Command_UpgradeTolinGaurhothFortressLevel4
    

    6    = Command_TolinGaurhothLeadership
    7    = Command_TolinGaurhothVampireCloud
    8    = Command_TolinGaurhothFlammingMunitions
    9    = Command_TolinGaurhothSorcery
   10    = Command_RadialBack

   11    = Command_ConstructTolinGaurhothVampiresHorde
   12    = Command_ConstructTolinGaurhothWolfHorde
   13    = Command_ConstructTolinGaurhothWereWolf
   14    = Command_ConstructTaurnuFuinGaurd
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_FakeHeroReviveSlot9
       27    = Command_FakeUldorReviveSlot
       28    = Command_GenericReviveSlot11
       29    = Command_GenericReviveSlot12
       30    = Command_FakeHeroReviveSlot13
       31    = Command_GenericReviveSlot14
       32    = Command_RadialBack

    33  = Command_SummonTolinGaurhothTarMairon
End


CommandSet TolinGaurhothFortressCommandSetLevel4
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonIsengard
    2    = Command_SelectRevivablesTolinGaurhothFortress
    3    = Command_SelectUpgradesTolinGaurhothFortress
    4    = Command_SelectUnitsTolinGaurhothFortress
    5    = Command_UpgradeTolinGaurhothFortressLevel5
    

    6    = Command_TolinGaurhothLeadership
    7    = Command_TolinGaurhothVampireCloud
    8    = Command_TolinGaurhothFlammingMunitions
    9    = Command_TolinGaurhothSorcery
   10    = Command_RadialBack

   11    = Command_ConstructTolinGaurhothVampiresHorde
   12    = Command_ConstructTolinGaurhothWolfHorde
   13    = Command_ConstructTolinGaurhothWereWolf
   14    = Command_ConstructTaurnuFuinGaurd
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_FakeHeroReviveSlot9
       27    = Command_FakeUldorReviveSlot
       28    = Command_GenericReviveSlot11
       29    = Command_GenericReviveSlot12
       30    = Command_FakeHeroReviveSlot13
       31    = Command_GenericReviveSlot14
       32    = Command_RadialBack

    33  = Command_SummonTolinGaurhothTarMairon
End


CommandSet TolinGaurhothFortressCommandSetLevel5
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonIsengard
    2    = Command_SelectRevivablesTolinGaurhothFortress
    3    = Command_SelectUpgradesTolinGaurhothFortress
    4    = Command_SelectUnitsTolinGaurhothFortress
    

    6    = Command_TolinGaurhothLeadership
    7    = Command_TolinGaurhothVampireCloud
    8    = Command_TolinGaurhothFlammingMunitions
    9    = Command_TolinGaurhothSorcery
   10    = Command_RadialBack

   11    = Command_ConstructTolinGaurhothVampiresHorde
   12    = Command_ConstructTolinGaurhothWolfHorde
   13    = Command_ConstructTolinGaurhothWereWolf
   14    = Command_ConstructTaurnuFuinGaurd
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_FakeHeroReviveSlot9
       27    = Command_FakeUldorReviveSlot
       28    = Command_GenericReviveSlot11
       29    = Command_GenericReviveSlot12
       30    = Command_FakeHeroReviveSlot13
       31    = Command_GenericReviveSlot14
       32    = Command_RadialBack

    33  = Command_SummonTolinGaurhothTarMairon
End

CommandSet AngbandFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonMordor
    2    = Command_SelectRevivablesAngbandFortress
    3    = Command_SelectUpgradesAngbandFortress
    4    = Command_SelectUnitsAngbandFortress
    5    = Command_UpgradeAngbandFortressLevel2
   
    6    = Command_SummonAngbandMelkor
    
    7    = Command_RadialBack
    8    = Command_LeadershipAngbandFortressLavaMoat
    9    = Command_LeadershipAngbandFortressMines
   10    = Command_LeadershipAngbandFortressPikes
   11    = Command_LeadershipAngbandFortressTowersSpire

   12    = Command_ConstructAngbandIronWorm
   13    = Command_ConstructAngbandFireDrake
   14    = Command_ConstructAngbandDragon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_GenericReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_FakeHeroReviveSlot13
	   31    = Command_GenericReviveSlot14
       32    = Command_RadialBack
End

CommandSet AngbandFortressCommandSetLevel2
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonMordor
    2    = Command_SelectRevivablesAngbandFortress
    3    = Command_SelectUpgradesAngbandFortress
    4    = Command_SelectUnitsAngbandFortress
    5    = Command_UpgradeAngbandFortressLevel3
   
    6    = Command_SummonAngbandMelkor
    
    7    = Command_RadialBack
    8    = Command_LeadershipAngbandFortressLavaMoat
    9    = Command_LeadershipAngbandFortressMines
   10    = Command_LeadershipAngbandFortressPikes
   11    = Command_LeadershipAngbandFortressTowersSpire

   12    = Command_ConstructAngbandIronWorm
   13    = Command_ConstructAngbandFireDrake
   14    = Command_ConstructAngbandDragon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_GenericReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_FakeHeroReviveSlot13
	   31    = Command_GenericReviveSlot14
       32    = Command_RadialBack
End

CommandSet AngbandFortressCommandSetLevel3
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonMordor
    2    = Command_SelectRevivablesAngbandFortress
    3    = Command_SelectUpgradesAngbandFortress
    4    = Command_SelectUnitsAngbandFortress
    5    = Command_UpgradeAngbandFortressLevel4
   
    6    = Command_SummonAngbandMelkor
    
    7    = Command_RadialBack
    8    = Command_LeadershipAngbandFortressLavaMoat
    9    = Command_LeadershipAngbandFortressMines
   10    = Command_LeadershipAngbandFortressPikes
   11    = Command_LeadershipAngbandFortressTowersSpire

   12    = Command_ConstructAngbandIronWorm
   13    = Command_ConstructAngbandFireDrake
   14    = Command_ConstructAngbandDragon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_GenericReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_FakeHeroReviveSlot13
	   31    = Command_GenericReviveSlot14
       32    = Command_RadialBack
End

CommandSet AngbandFortressCommandSetLevel4
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonMordor
    2    = Command_SelectRevivablesAngbandFortress
    3    = Command_SelectUpgradesAngbandFortress
    4    = Command_SelectUnitsAngbandFortress
    5    = Command_UpgradeAngbandFortressLevel5
   
    6    = Command_SummonAngbandMelkor
    
    7    = Command_RadialBack
    8    = Command_LeadershipAngbandFortressLavaMoat
    9    = Command_LeadershipAngbandFortressMines
   10    = Command_LeadershipAngbandFortressPikes
   11    = Command_LeadershipAngbandFortressTowersSpire

   12    = Command_ConstructAngbandIronWorm
   13    = Command_ConstructAngbandFireDrake
   14    = Command_ConstructAngbandDragon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_GenericReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_FakeHeroReviveSlot13
	   31    = Command_GenericReviveSlot14
       32    = Command_RadialBack
End

CommandSet AngbandFortressCommandSetLevel5
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonMordor
    2    = Command_SelectRevivablesAngbandFortress
    3    = Command_SelectUpgradesAngbandFortress
    4    = Command_SelectUnitsAngbandFortress
   
    6    = Command_SummonAngbandMelkor
    
    7    = Command_RadialBack
    8    = Command_LeadershipAngbandFortressLavaMoat
    9    = Command_LeadershipAngbandFortressMines
   10    = Command_LeadershipAngbandFortressPikes
   11    = Command_LeadershipAngbandFortressTowersSpire

   12    = Command_ConstructAngbandIronWorm
   13    = Command_ConstructAngbandFireDrake
   14    = Command_ConstructAngbandDragon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_FakeHeroReviveSlot7
       25    = Command_FakeHeroReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_GenericReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_FakeHeroReviveSlot13
	   31    = Command_GenericReviveSlot14
       32    = Command_RadialBack
End

CommandSet UnderworldPortalCommandSet
    InitialVisible = 6
    1    = Command_SelectPowerfulSummonAngmar
    2    = Command_SelectRevivablesUnderworldPortal
    3    = Command_SelectSpellUnderworldPortal
    4    = Command_SelectUnitsUnderworldPortal
    5    = Command_ConstructAngmarLichkonig
    6    = Command_UpgradeUnderworldPortalFortressLevel2

    7    = Command_UnderworldLeadership
    8    = Command_UnderworldWeapon
    9    = Command_UnderworldSnowRain
   10    = Command_UnderworldFrozen
   11    = Command_RadialBack

   12    = Command_ConstructUnderworldCollector
   13    = Command_ConstructUnderworldDragon
   14    = Command_ConstructUnderworldDeamon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_GenericReviveSlot7
       25    = Command_GenericReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_FakeHeroReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_RadialBack

    31   = Command_SummonAvatharUngoliant
    32   = Command_RadialBack
End

CommandSet UnderworldPortalFortressCommandSetLevel2
    InitialVisible = 6
    1    = Command_SelectPowerfulSummonAngmar
    2    = Command_SelectRevivablesUnderworldPortal
    3    = Command_SelectSpellUnderworldPortal
    4    = Command_SelectUnitsUnderworldPortal
    5    = Command_ConstructAngmarLichkonig
    6    = Command_UpgradeUnderworldPortalFortressLevel3

    7    = Command_UnderworldLeadership
    8    = Command_UnderworldWeapon
    9    = Command_UnderworldSnowRain
   10    = Command_UnderworldFrozen
   11    = Command_RadialBack

   12    = Command_ConstructUnderworldCollector
   13    = Command_ConstructUnderworldDragon
   14    = Command_ConstructUnderworldDeamon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_GenericReviveSlot7
       25    = Command_GenericReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_FakeHeroReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_RadialBack

    31   = Command_SummonAvatharUngoliant
    32   = Command_RadialBack
End

CommandSet UnderworldPortalFortressCommandSetLevel3
    InitialVisible = 6
    1    = Command_SelectPowerfulSummonAngmar
    2    = Command_SelectRevivablesUnderworldPortal
    3    = Command_SelectSpellUnderworldPortal
    4    = Command_SelectUnitsUnderworldPortal
    5    = Command_ConstructAngmarLichkonig
    6    = Command_UpgradeUnderworldPortalFortressLevel4

    7    = Command_UnderworldLeadership
    8    = Command_UnderworldWeapon
    9    = Command_UnderworldSnowRain
   10    = Command_UnderworldFrozen
   11    = Command_RadialBack

   12    = Command_ConstructUnderworldCollector
   13    = Command_ConstructUnderworldDragon
   14    = Command_ConstructUnderworldDeamon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_GenericReviveSlot7
       25    = Command_GenericReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_FakeHeroReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_RadialBack

    31   = Command_SummonAvatharUngoliant
    32   = Command_RadialBack
End

CommandSet UnderworldPortalFortressCommandSetLevel4
    InitialVisible = 6
    1    = Command_SelectPowerfulSummonAngmar
    2    = Command_SelectRevivablesUnderworldPortal
    3    = Command_SelectSpellUnderworldPortal
    4    = Command_SelectUnitsUnderworldPortal
    5    = Command_ConstructAngmarLichkonig
    6    = Command_UpgradeUnderworldPortalFortressLevel5

    7    = Command_UnderworldLeadership
    8    = Command_UnderworldWeapon
    9    = Command_UnderworldSnowRain
   10    = Command_UnderworldFrozen
   11    = Command_RadialBack

   12    = Command_ConstructUnderworldCollector
   13    = Command_ConstructUnderworldDragon
   14    = Command_ConstructUnderworldDeamon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_GenericReviveSlot7
       25    = Command_GenericReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_FakeHeroReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_RadialBack

    31   = Command_SummonAvatharUngoliant
    32   = Command_RadialBack
End

CommandSet UnderworldPortalFortressCommandSetLevel5
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonAngmar
    2    = Command_SelectRevivablesUnderworldPortal
    3    = Command_SelectSpellUnderworldPortal
    4    = Command_SelectUnitsUnderworldPortal
    5    = Command_ConstructAngmarLichkonig

    7    = Command_UnderworldLeadership
    8    = Command_UnderworldWeapon
    9    = Command_UnderworldSnowRain
   10    = Command_UnderworldFrozen
   11    = Command_RadialBack

   12    = Command_ConstructUnderworldCollector
   13    = Command_ConstructUnderworldDragon
   14    = Command_ConstructUnderworldDeamon
   15    = Command_RadialBack

       16    = Command_FakeRingHeroReviveSlot
       17    = Command_FakeCreateAHeroReviveSlot
       18    = Command_FakeHeroReviveSlot1
       19    = Command_FakeHeroReviveSlot2
       20    = Command_FakeHeroReviveSlot3
       21    = Command_FakeHeroReviveSlot4
       22    = Command_FakeHeroReviveSlot5
       23    = Command_FakeHeroReviveSlot6
       24    = Command_GenericReviveSlot7
       25    = Command_GenericReviveSlot8
       26    = Command_GenericReviveSlot9
       27    = Command_FakeHeroReviveSlot10
       28    = Command_FakeHeroReviveSlot11
       29    = Command_FakeHeroReviveSlot12
       30    = Command_RadialBack

   31   = Command_SummonAvatharUngoliant
   32   = Command_RadialBack
End




CommandSet FormenosFortressCommandSet
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonImladris
    2    = Command_SelectRevivablesFormenosFortress
    3    = Command_SelectLibraryFormenos
    4    = Command_SelectUnitsFormenos
    5    = Command_UpgradeFormenosFortressLevel2
    
    6    = Command_SummonValinorTulkas
    7    = Command_RadialBack
    
    8    = Command_FormenosLeadership
    9    = Command_FormenosTengwarScripture
   10    = Command_FormenosRecepies
   11    = Command_FormenosBuildingEnchant
   12    = Command_FormenosPalantir

   13    = Command_ConstructFormenosArcherHorde
   14    = Command_ConstructFormenosGuardHorde
   15    = Command_ConstructFormenosEliteSwordHorde
   16    = Command_RadialBack

       17    = Command_FakeRingHeroReviveSlot
       18    = Command_FakeCreateAHeroReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_GenericReviveSlot8
       27    = Command_GenericReviveSlot9
       28    = Command_FakeGwaihirReviveSlot
       29    = Command_FakeHeroReviveSlot11
       30    = Command_FakeHeroReviveSlot12
	   31    = Command_FakeHeroReviveSlot13
       32    = Command_RadialBack
End

CommandSet FormenosFortressCommandSetLevel2
   InitialVisible = 5
    1    = Command_SelectPowerfulSummonImladris
    2    = Command_SelectRevivablesFormenosFortress
    3    = Command_SelectLibraryFormenos
    4    = Command_SelectUnitsFormenos
    5    = Command_UpgradeFormenosFortressLevel3
    
    6    = Command_SummonValinorTulkas
    7    = Command_RadialBack
    
    8    = Command_FormenosLeadership
    9    = Command_FormenosTengwarScripture
   10    = Command_FormenosRecepies
   11    = Command_FormenosBuildingEnchant
   12    = Command_FormenosPalantir

   13    = Command_ConstructFormenosArcherHorde
   14    = Command_ConstructFormenosGuardHorde
   15    = Command_ConstructFormenosEliteSwordHorde
   16    = Command_RadialBack

       17    = Command_FakeRingHeroReviveSlot
       18    = Command_FakeCreateAHeroReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_GenericReviveSlot8
       27    = Command_GenericReviveSlot9
       28    = Command_FakeGwaihirReviveSlot
       29    = Command_FakeHeroReviveSlot11
       30    = Command_FakeHeroReviveSlot12
	   31    = Command_FakeHeroReviveSlot13
       32    = Command_RadialBack
End

CommandSet FormenosFortressCommandSetLevel3
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonImladris
    2    = Command_SelectRevivablesFormenosFortress
    3    = Command_SelectLibraryFormenos
    4    = Command_SelectUnitsFormenos
    5    = Command_UpgradeFormenosFortressLevel4
    
    6    = Command_SummonValinorTulkas
    7    = Command_RadialBack
    
    8    = Command_FormenosLeadership
    9    = Command_FormenosTengwarScripture
   10    = Command_FormenosRecepies
   11    = Command_FormenosBuildingEnchant
   12    = Command_FormenosPalantir

   13    = Command_ConstructFormenosArcherHorde
   14    = Command_ConstructFormenosGuardHorde
   15    = Command_ConstructFormenosEliteSwordHorde
   16    = Command_RadialBack

       17    = Command_FakeRingHeroReviveSlot
       18    = Command_FakeCreateAHeroReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_GenericReviveSlot8
       27    = Command_GenericReviveSlot9
       28    = Command_FakeGwaihirReviveSlot
       29    = Command_FakeHeroReviveSlot11
       30    = Command_FakeHeroReviveSlot12
	   31    = Command_FakeHeroReviveSlot13
       32    = Command_RadialBack
End

CommandSet FormenosFortressCommandSetLevel4
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonImladris
    2    = Command_SelectRevivablesFormenosFortress
    3    = Command_SelectLibraryFormenos
    4    = Command_SelectUnitsFormenos
    5    = Command_UpgradeFormenosFortressLevel5
    
    6    = Command_SummonValinorTulkas
    7    = Command_RadialBack
    
    8    = Command_FormenosLeadership
    9    = Command_FormenosTengwarScripture
   10    = Command_FormenosRecepies
   11    = Command_FormenosBuildingEnchant
   12    = Command_FormenosPalantir

   13    = Command_ConstructFormenosArcherHorde
   14    = Command_ConstructFormenosGuardHorde
   15    = Command_ConstructFormenosEliteSwordHorde
   16    = Command_RadialBack

       17    = Command_FakeRingHeroReviveSlot
       18    = Command_FakeCreateAHeroReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_GenericReviveSlot8
       27    = Command_GenericReviveSlot9
       28    = Command_FakeGwaihirReviveSlot
       29    = Command_FakeHeroReviveSlot11
       30    = Command_FakeHeroReviveSlot12
	   31    = Command_FakeHeroReviveSlot13
       32    = Command_RadialBack
End

CommandSet FormenosFortressCommandSetLevel5
    InitialVisible = 5
    1    = Command_SelectPowerfulSummonImladris
    2    = Command_SelectRevivablesFormenosFortress
    3    = Command_SelectLibraryFormenos
    4    = Command_SelectUnitsFormenos
        
    6    = Command_SummonValinorTulkas
    7    = Command_RadialBack
    
    8    = Command_FormenosLeadership
    9    = Command_FormenosTengwarScripture
   10    = Command_FormenosRecepies
   11    = Command_FormenosBuildingEnchant
   12    = Command_FormenosPalantir

   13    = Command_ConstructFormenosArcherHorde
   14    = Command_ConstructFormenosGuardHorde
   15    = Command_ConstructFormenosEliteSwordHorde
   16    = Command_RadialBack

       17    = Command_FakeRingHeroReviveSlot
       18    = Command_FakeCreateAHeroReviveSlot
       19    = Command_FakeHeroReviveSlot1
       20    = Command_FakeHeroReviveSlot2
       21    = Command_FakeHeroReviveSlot3
       22    = Command_FakeHeroReviveSlot4
       23    = Command_FakeHeroReviveSlot5
       24    = Command_FakeHeroReviveSlot6
       25    = Command_FakeHeroReviveSlot7
       26    = Command_GenericReviveSlot8
       27    = Command_GenericReviveSlot9
       28    = Command_FakeGwaihirReviveSlot
       29    = Command_FakeHeroReviveSlot11
       30    = Command_FakeHeroReviveSlot12
	   31    = Command_FakeHeroReviveSlot13
       32    = Command_RadialBack
End

CommandSet LorienGardenCommandSet
    1   = Command_LeadershipMallornSprouts
    2   = Command_LeadershipDiscountGaladrim
    3   = Command_LeadershipDiscountUpgrades
    4   = Command_PurchaseUpgradeBundnisWaldelben_New
	5   = Command_PurchaseGardenUpgradeGrandHarvest
    6   = Command_Sell
End

CommandSet AngmarMorgramirCommandSetMod
    1    = Command_ToggleStance
    2    = Command_SpecialAbilityMorgomirEdikt
    3    = Command_SpecialAbilityMorgomirsDunklerPakt
    4    = Command_SpecialAbilityRankeschmied
    5    = Command_SpecialAbilityGesetzderStarke 
    6    = Command_SpecialAbilityMorgomirIntrige
    12    = Command_CaptureBuilding
    13    = Command_AttackMove
    14    = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet AngmarHallofTwilightCommandSet
 InitialVisible = 8
      ;1 = Command_SelectRevivablesHallTwilight
      2 = Command_DarkPowersRising
      3 = Command_ConstructAngmarNecromancerHorde
      4 = Command_TechnologyAngmarSoulFreezeEnabled
      5 = Command_TechnologyAngmarWellOfSoulsEnabled
      6 = Command_Sell
      7 = Command_TechnologyAngmarCorpseRainEnabled
      8 = Command_Upgrade_AngmarHallofTwilightLevel2

      ;9 = Command_PurchaseTechnologyGulzarLebensschild
     ;10 = Command_PurchaseTechnologyGulzardasSeelenopfer
     ;11 = Command_PurchaseTechnologyGulzarSeelenwanderung
     ;12 = Command_PurchaseTechnologyGulzarSchattenschleier
     ;13 = Command_PurchaseTechnologyGulzarFlammendeVergeltung
     ;14 = Command_PurchaseTechnologyFluchesHexenmeisters
     ;15 = Command_PurchaseTechnologyGulzarMorgulseuche
     ;16 = Command_PurchaseTechnologyGulzarDunklesRitual
     ;17 = Command_RadialBack

     ;18 = Command_ConstructAngmarGulzar
     19 = Command_RadialBack
End

CommandSet AngmarHallofTwilightCommandSetLevel2
 InitialVisible = 8
      ;1 = Command_SelectRevivablesHallTwilight
      2 = Command_DarkPowersRising
      3 = Command_ConstructAngmarNecromancerHorde
      4 = Command_TechnologyAngmarSoulFreezeEnabled
      5 = Command_TechnologyAngmarWellOfSoulsEnabled2
      6 = Command_Sell
      7 = Command_TechnologyAngmarCorpseRainEnabled
      8 = Command_Upgrade_AngmarHallofTwilightLevel3

      ;9 = Command_PurchaseTechnologyGulzarLebensschild
     ;10 = Command_PurchaseTechnologyGulzardasSeelenopfer
     ;11 = Command_PurchaseTechnologyGulzarSeelenwanderung
     ;12 = Command_PurchaseTechnologyGulzarSchattenschleier
     ;13 = Command_PurchaseTechnologyGulzarFlammendeVergeltung
     ;14 = Command_PurchaseTechnologyFluchesHexenmeisters
     ;15 = Command_PurchaseTechnologyGulzarMorgulseuche
     ;16 = Command_PurchaseTechnologyGulzarDunklesRitual
     ;17 = Command_RadialBack

     ;18 = Command_ConstructAngmarGulzar
     19 = Command_RadialBack
End

CommandSet AngmarHallofTwilightCommandSetLevel3
 InitialVisible = 7
      ;1 = Command_SelectRevivablesHallTwilight
      2 = Command_DarkPowersRising
      3 = Command_ConstructAngmarNecromancerHorde
      4 = Command_TechnologyAngmarSoulFreezeEnabled
      5 = Command_TechnologyAngmarWellOfSoulsEnabled2
      6 = Command_Sell
      7 = Command_TechnologyAngmarCorpseRainEnabled2

     ;9 = Command_PurchaseTechnologyGulzarLebensschild
     ;10 = Command_PurchaseTechnologyGulzardasSeelenopfer
     ;11 = Command_PurchaseTechnologyGulzarSeelenwanderung
     ;12 = Command_PurchaseTechnologyGulzarSchattenschleier
     ;13 = Command_PurchaseTechnologyGulzarFlammendeVergeltung
     ;14 = Command_PurchaseTechnologyFluchesHexenmeisters
     ;15 = Command_PurchaseTechnologyGulzarMorgulseuche
     ;16 = Command_PurchaseTechnologyGulzarDunklesRitual
     ;17 = Command_RadialBack

     ;18 = Command_ConstructAngmarGulzar
     18 = Command_RadialBack
End

CommandSet MordorSiegeWorksCommandSetLevelCirithUngol
      1    = Command_MordorSiegeWorksSauron
      2    = Command_ConstructMordorBatteringRam
      3    = Command_ConstructMordorTrollcatapult
      4    = Command_ConstructMordorSiegeTowerEdain
      5    = Command_ConstructMordorWarGreatBeast
      6    = Command_Sell
      7    = Command_ConstructMordorGrondMod
      8    = Command_PurchaseTechnologyMordorForgedBlades
      9    = Command_PurchaseTechnologyMordorHeavyArmor
End

CommandSet  MordorHaradrimSchwerterCommandSet
    1       = Command_ToggleStance
    2       = Command_ToggleFormationMarschformation
    3       = Command_PurchaseUpgradeMordorHaradBasicTraining
    4       = Command_PurchaseUpgradeMordorHaradArmor
    5       = Command_PurchaseUpgradeMordorHaradBlades
    6       = Command_PurchaseUpgradeEvilmenShield
    12      = Command_CaptureBuilding
    13      = Command_AttackMove
    14      = Command_EvilStop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet MenoftheEastFortressCommandSet2
            InitialVisible = 17
        1   = Command_TogglePalantir2_MOTEFort
        2   = Command_FakeCreateAHeroReviveSlot
        3   = Command_FakeHeroReviveSlot1
        4   = Command_FakeHeroReviveSlot2
        5   = Command_FakeHeroReviveSlot3
        6   = Command_FakeHeroReviveSlot4
        7   = Command_FakeHeroReviveSlot5
        8   = Command_FakeHeroReviveSlot6
        9   = Command_FakeHeroReviveSlot7
        10  = Command_FakeHeroReviveSlot8
        11  = Command_FakeHeroReviveSlot9
        12  = Command_FakeHeroReviveSlot10
        13  = Command_FakeHeroReviveSlot11
        14  = Command_GenericReviveSlot12
        15  = Command_GenericReviveSlot13
        16  = Command_FakeHeroReviveSlot14
        17  = Command_FakeRingHeroReviveSlot
        18  = Command_TogglePalantir2_MOTEFort
End

CommandSet EvilmenSuladanCommandSet
    1    = Command_ToggleStance
    2    = Command_ToggleMountedSuladan
    3    = Command_SpecialAbilitySuladanPorter
    4    = Command_SpecialAbilitySuladanHorn
    5    = Command_SpecialAbilitySuladanGloriousCharge
    6    = Command_SpecialAbilitySuladanNiedertrampeln
    12    = Command_CaptureBuilding
    13    = Command_AttackMove
    14    = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet EvilmenSuladanCommandSetNew
    1    = Command_ToggleStance
    2    = Command_ToggleMountedSuladan
    3    = Command_SpecialAbilityBladeOfMadrat
    4    = Command_SpecialAbilityLordOfTheSands
    5    = Command_SpecialAbilityFlankingManeuver
    6    = Command_SpecialAbilitySuladanGloriousCharge
    12    = Command_CaptureBuilding
    13    = Command_AttackMove
    14    = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet HaradBadHarkanCommandSet
    1    = Command_ToggleStance
    2    = Command_ToggleBadharkanWeapon
    3    = Command_SpecialAbilitySalemeGiftfalle
    4    = Command_SpecialAbilityHunterAmbush
    5    = Command_SpecialAbilityPiercingThrows
    6    = Command_SpecialAbilityAncientSpear
    12    = Command_CaptureBuilding
    13    = Command_AttackMove
    14    = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet HaradBadHarkanCommandSet_Ambush
    1    = Command_ToggleStance
    2    = Command_SpecialAbilitySetupAmbush
    3    = Command_SpecialAbilityActivateAmbush
    12    = Command_CaptureBuilding
    13    = Command_AttackMove
    14    = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet HaradPorterSummonedCommandSet
    1 = Command_EvilStop
    2 = Command_PorterExtinguishFire
    3 = Command_Repair
    4 = Command_PorterConstructHaradForge
    5 = Command_SummonedPorterConstructHaradBarracks
    6 = Command_SummonedPorterConstructHaradOasis
    7 = Command_SummonedPorterConstructHaradMumakilPen
    8 = Command_ConstructMordorTavern
End

CommandSet HaradBarracksCommandSet
        2    = Command_ConstructEvilmenHaradSwordHorde
        3    = Command_ConstructHaradrimSpearmanHordeMod
        4    = Command_ConstructHaradHaradrimArcherHordeBarracks
        5    = Command_ConstructMordorHaradrimLancerModHordeBarracks
        7    = Command_ConstructEvilmenKhandSoldierHorde
        8    = Command_UpgradeHaradBarracksLevel2
        9    = Command_Sell
End

CommandSet HaradBarracksCommandSetLevel2
        2    = Command_ConstructEvilmenHaradSwordHorde
        3    = Command_ConstructHaradrimSpearmanHordeMod
        4    = Command_ConstructHaradHaradrimArcherHordeBarracks
        5    = Command_ConstructMordorHaradrimLancerModHordeBarracks
        7    = Command_ConstructEvilmenKhandSoldierHorde
        6    = Command_UpgradeHaradBarracksLevel3
        7    = Command_Sell
End

CommandSet HaradBarracksCommandSetLevel3
        2    = Command_ConstructEvilmenHaradSwordHorde
        3    = Command_ConstructHaradrimSpearmanHordeMod
        4    = Command_ConstructHaradHaradrimArcherHordeBarracks
        5    = Command_ConstructMordorHaradrimLancerModHordeBarracks
        7    = Command_ConstructEvilmenKhandSoldierHorde
        6    = Command_Sell
End

CommandSet BilboCommandSet1
    1    = Command_ToggleStance
    2    = Command_SpecialAbilityBilboVerstecken
    3    = Command_ToggleFrodoWeapon
    4    = Command_SpecialAbilityAdventure
    5    = Command_SpecialAbilityBilboMasterburgler
    6    = Command_SpecialAbilityRiddles
    12   = Command_CaptureBuilding
    13   = Command_AttackMove
    14   = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet BilboCommandSet2
    1    = Command_ToggleStance
    2    = Command_SpecialAbilityBilboVerstecken
    3    = Command_ToggleBilboWeapon
    4    = Command_SpecialAbilityTreacheryOfTheRing
    5    = Command_SpecialAbilityBilboGuardian
    6    = Command_GiveArkenstone
    12   = Command_CaptureBuilding
    13   = Command_AttackMove
    14   = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet BilboCommandSet3
    1    = Command_ToggleStance
    2    = Command_ToggleBilboWeapon
    3    = Command_SpecialAbilityBilboMasterburgler
    4    = Command_SpecialAbilityRiddles
    5    = Command_BilboMeisterdieb
    6    = Command_PurchaseUpgradeDwarvenMithrilMailHeroes
    12   = Command_CaptureBuilding
    13   = Command_AttackMove
    14   = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End


CommandSet DwarvenNoriEreborCommandSet
    1      = Command_ToggleStance
    2      = Command_SpecialAbilityZwergischerWohlstand
    3      = Command_SpecialAbilityZwielichtigerGeselle
    4      = Command_SpecialAbilityNoriSummonDori
    5      = Command_SpecialAbilityNoriMesserwurf
    6      = Command_SpecialAbilityNoriHinterhalt
    12      = Command_CaptureBuilding
    13      = Command_AttackMove
    14      = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End

CommandSet DwarvenBarracksDiplomacyCommandSet
      InitialVisible = 5
      1     = Command_SelectRevivablesDwarvenBarracksKampagne_Erebor2
      2     = Command_SelectRevivablesDwarvenBarracksKampagne_Eisenberge2
      3     = Command_SelectRevivablesDwarvenBarracksKampagne_EredLuin2
      4     = Command_SelectAglarondUnits
      5     = Command_Sell

      6     = Command_ConstructDwarvenGuardianEreborHorde
      7     = Command_ConstructDwarvenPhalanxLangbarteHorde
      8     = Command_ConstructDwarvenAxeThrowerHordeEdain
      9     = Command_PurchaseTechnologyDwarvenKriegsmaske_Erebor
     10     = Command_ConstructDwarvenArkenguardHorde
     11     = Command_RadialBack

     12     = Command_ConstructDwarvenGuardianIronHillsHorde
     13     = Command_ConstructDwarvenPhalanxIronHillsHorde
     14     = Command_ConstructDwarvenBowHorde
     15     = Command_PurchaseTechnologyDwarvenMasterAxes
     16     = Command_ConstructDwarvenIronBreakerHorde
     17     = Command_RadialBack

     18     = Command_ConstructDwarvenGuardianBreitschulternHorde
     19     = Command_ConstructDwarvenPhalanxBreitschulternHorde
     20     = Command_ConstructDwarvenBowHorde_Gefecht
     21     = Command_PurchaseTechnologyDwarvenSiegeHammer
     22     = Command_ConstructDwarvenUnburntHorde
     23     = Command_RadialBack

     24     = Command_ConstructAglarondHunterHorde
     25     = Command_ConstructAglarondPikeHorde
     26     = Command_ConstructAglarondCavalaryHorde
     27     = Command_RadialBack
End

CommandSet HaradSouthWatcherHordeCommandSet
    1     = Command_ToggleStance
    2     = Command_SpecialAbilityMahudRaserei 
    3       = Command_PurchaseUpgradeMordorHaradBasicTraining ;
    4       = Command_PurchaseUpgradeMordorHaradArmor
    5       = Command_PurchaseUpgradeMordorHaradBlades
    6     = Command_PurchaseUpgradeEvilmenShield
    7     = Command_ToggleFormationEvilMenHaradrimSoldier ;Command_ToggleFormationOrksNebelberge
    12  = Command_CaptureBuilding
    13  = Command_AttackMove
    14  = Command_Stop
    16      = Command_SetStanceBattle
    17      = Command_SetStanceAggressive
    18      = Command_SetStanceHoldGround
End
