CommandButton Command_SelectPowerfulSummonAngmar
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseUnderworldPortalSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectEvilFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectEvilFASummon
  Radial                  = Yes
  CommandRangeStart       = 30
  CommandRangeCount       = 3
End

CommandButton Command_SelectPowerfulSummonMordor
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseAngbandFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectEvilFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectEvilFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonGoblins
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseAngbandThangorodrimSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectEvilFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectEvilFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonIsengard
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseTolinGaurhothFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectEvilFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectEvilFASummon
  Radial                  = Yes
  CommandRangeStart       = 31
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonlothlorien
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseMenegrothFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 31
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonDwarves
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseBelegostFortresSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 31
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonArnor
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseArmenelosFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonImladris
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseFormenosFortresSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonRohan
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseTaniquetilFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectPowerfulSummonGondor
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUPurchaseDorthonionFortressSpellTechnology
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectGoodFASummon
  DescriptLabel           = CONTROLBAR:ToolTipSelectSelectGoodFASummon
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 2
End

CommandButton Command_SelectRevivablesMenegrothFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesMenegrothFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesMenegrothFortress
  Radial                  = Yes
  CommandRangeStart       = 16
  CommandRangeCount       = 17
End

CommandButton Command_SelectUpgradesMenegrothFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUpgradesMenegrothFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUpgradesMenegrothFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUpgradesMenegrothFortress
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 6
End

CommandButton Command_SelectUnitsMenegrothFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsMenegrothFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsMenegrothFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsMenegrothFortress
  Radial                  = Yes
  CommandRangeStart       = 11
  CommandRangeCount       = 5
End

CommandButton Command_SelectRevivablesBelegostFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesBelegostFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesBelegostFortress
  Radial                  = Yes
  CommandRangeStart       = 7
  CommandRangeCount       = 24
End


CommandButton Command_SelectSpellBelegostFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectSpellBelegostFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectSpellBelegostFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectSpellBelegostFortress
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 4
End


CommandButton Command_SelectUnitsBelegostFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsBelegostFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsBelegostFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsBelegostFortress
  Radial                  = Yes
  CommandRangeStart       = 4
  CommandRangeCount       = 4
End

CommandButton Command_SelectRevivablesArmenelosFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesDorthonionFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesDorthonionFortress
  Radial                  = Yes
  CommandRangeStart       = 16
  CommandRangeCount       = 16
End


CommandButton Command_SelectSpellArmenelosFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectSpellArmenelos
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectSpellArmenelosFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectSpellArmenelosFortress
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 6
End


CommandButton Command_SelectUnitsArmenelosFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsArmenelos
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsArmenelos
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsArmenelos
  Radial                  = Yes
  CommandRangeStart       = 12
  CommandRangeCount       = 4
End

CommandButton Command_SelectRevivablesTaniquetilFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesTaniquetilFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesTaniquetilFortress
  Radial                  = Yes
  CommandRangeStart       = 15
  CommandRangeCount       = 18
End


CommandButton Command_SelectSpellsTaniquetilFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectSpellsTaniquetilFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectSpellsTaniquetilFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectSpellsTaniquetilFortress
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsTaniquetilFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsTaniquetilFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsTaniquetilFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsTaniquetilFortress
  Radial                  = Yes
  CommandRangeStart       = 11
  CommandRangeCount       = 4
End

CommandButton Command_SelectRevivablesDorthonionFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesDorthonionFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesDorthonionFortress
  Radial                  = Yes
  CommandRangeStart       = 15
  CommandRangeCount       = 14
End


CommandButton Command_SelectDorthonionFortressUpgrades
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectDorthonionFortressUpgrades
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectDorthonionFortressUpgrades
  DescriptLabel           = CONTROLBAR:ToolTipSelectDorthonionFortressUpgrades
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsDorthonionFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsDorthonionFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsDorthonionFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsDorthonionFortress
  Radial                  = Yes
  CommandRangeStart       = 11
  CommandRangeCount       = 5
End

CommandButton Command_SelectRevivablesTolinGaurhothFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_EvilHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesTolinGaurhothFortress
  DescriptLabel           = CONTROLBAR:ToolTipCommandSelectRevivablesTolinGaurhothFortress
  Radial                  = Yes
  CommandRangeStart       = 15
  CommandRangeCount       = 17
End


CommandButton Command_SelectUpgradesTolinGaurhothFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUpgradesTolinGaurhothFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUpgradesTolinGaurhothFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUpgradesTolinGaurhothFortress
  Radial                  = Yes
  CommandRangeStart       = 5
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsTolinGaurhothFortress 
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUnitsTolinGaurhothFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsTolinGaurhothFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsTolinGaurhothFortress
  Radial                  = Yes
  CommandRangeStart       = 10
  CommandRangeCount       = 5
End

CommandButton Command_SelectRevivablesAngbandFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_EvilHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesAngbandFortress
  DescriptLabel           = CONTROLBAR:ToolTipCommandSelectRevivablesAngbandFortress
  Radial                  = Yes
  CommandRangeStart       = 15
  CommandRangeCount       = 17
End


CommandButton Command_SelectUpgradesAngbandFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUpgradesAngbandFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUpgradesAngbandFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUpgradesAngbandFortress
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsAngbandFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUnitsAngbandFortress
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsAngbandFortress
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsAngbandFortress
  Radial                  = Yes
  CommandRangeStart       = 11
  CommandRangeCount       = 4
End

CommandButton Command_SelectRevivablesUnderworldPortal
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_EvilHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesUnderworldPortal
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesUnderworldPortal
  Radial                  = Yes
  CommandRangeStart       = 15
  CommandRangeCount       = 15
End


CommandButton Command_SelectSpellUnderworldPortal
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectSpellUnderworldPortal
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectSpellUnderworldPortal
  DescriptLabel           = CONTROLBAR:ToolTipSelectSpellUnderworldPortal
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsUnderworldPortal
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUnitsUnderworldPortal
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsUnderworldPortal
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsUnderworldPortal
  Radial                  = Yes
  CommandRangeStart       = 11
  CommandRangeCount       = 4
End

CommandButton Command_SelectRevivablesAngbandThangorodrim
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_EvilHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesAngbandThangorodrim
  DescriptLabel           = CONTROLBAR:ToolTipSelectRevivablesAngbandThangorodrim
  Radial                  = Yes
  CommandRangeStart       = 13
  CommandRangeCount       = 17
End


CommandButton Command_SelectTechnologyBalrog
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectTechnologyBalrog
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectTechnologyBalrog
  DescriptLabel           = CONTROLBAR:ToolTipSelectTechnologyBalrog
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 5
End


CommandButton Command_SelectUnitsAngbandThangorodrim
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BUSelectUnitsAngbandThangorodrim
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsAngbandThangorodrim
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsAngbandThangorodrim
  Radial                  = Yes
  CommandRangeStart       = 8
  CommandRangeCount       = 5
End

CommandButton Command_SelectRevivablesFormenosFortress
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = UCCommon_GoodHeroes
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectRevivablesFormenosFortress
  DescriptLabel           = CONTROLBAR:ToolTipCommandSelectRevivablesFormenosFortress
  Radial                  = Yes
  CommandRangeStart       = 16
  CommandRangeCount       = 16
End


CommandButton Command_SelectLibraryFormenos
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectLibraryFormenos
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectLibraryFormenosHouse
  DescriptLabel           = CONTROLBAR:ToolTipSelectLibraryFormenosHouse
  Radial                  = Yes
  CommandRangeStart       = 6
  CommandRangeCount       = 6
End


CommandButton Command_SelectUnitsFormenos
  Command                 = PUSH_VISIBLE_COMMAND_RANGE
  ButtonImage             = BDSelectUnitsFormenos
  ButtonBorderType        = SYSTEM
  TextLabel               = CONTROLBAR:SelectUnitsFormenos
  DescriptLabel           = CONTROLBAR:ToolTipSelectUnitsFormenos
  Radial                  = Yes
  CommandRangeStart       = 12
  CommandRangeCount       = 4
End

CommandButton Command_LeadershipDiscountGaladrim
  Command               = SPECIAL_POWER
  SpecialPower          = SpecialAbilityFakeLeadership
  Options               = NONPRESSABLE NEED_UPGRADE
  ButtonImage           = UPGaladhrim
  ButtonBorderType      = ACTION
  RadiusCursorType      = TrainingRadiusCursor
  TextLabel             = CONTROLBAR:LeadershipDiscountGaladrim
  DescriptLabel         = CONTROLBAR:ToolTipLeadershipDiscountGaladrim
  InPalantir            = Yes
  Radial                = No
  NeededUpgrade         = Upgrade_StructureLevel2
End

CommandButton Command_SpecialAbilityMorgomirEdikt
  Command           = SPECIAL_POWER
  SpecialPower      = SpecialAbilityFakeLeadership
  Options           = NONPRESSABLE
  TextLabel         = CONTROLBAR:SpecialAbilityMorgomirEdikt
  ButtonImage       = HSMorgomirEdikt
  ButtonBorderType  = ACTION
  DescriptLabel     = CONTROLBAR:ToolTipSpecialAbilityMorgomirEdikt
  InPalantir        = Yes
End

CommandButton Command_ConstructUnderworldDragon
  Command                 = UNIT_BUILD
  Object                  = UnderworldDragon
  Options                 = CANCELABLE NEED_UPGRADE
  NeededUpgrade           = Upgrade_FirstAgeFortressLevel2
  ButtonImage             = HIUnderworldDragon
  ButtonBorderType        = BUILD
  TextLabel               = CONTROLBAR:BuildUnderworldDragon
  DescriptLabel           = CONTROLBAR:ToolTipBuildUnderworldDragon
  Radial                  = Yes
  InPalantir              = Yes
  IsClickable             = Yes
  ShowProductionCount     = Yes
End

CommandButton Command_ConstructUnderworldDeamon
  Command                 = UNIT_BUILD
  NeededUpgrade           = Upgrade_FirstAgeFortressLevel3
  Object                  = UnderworldDeamon
  Options                 = CANCELABLE NEED_UPGRADE
  ButtonImage             = HIUnderworldDeamon
  ButtonBorderType        = BUILD
  TextLabel               = CONTROLBAR:BuildUnderworldDeamon
  DescriptLabel           = CONTROLBAR:ToolTipBuildUnderworldDeamon
  Radial                  = Yes
  InPalantir              = Yes
  IsClickable             = Yes
  ShowProductionCount     = Yes
End

CommandButton Command_MordorSiegeWorksSauron
  Command               = SPECIAL_POWER
  SpecialPower          = SpecialAbilityFakeLeadership
  Options               = NONPRESSABLE
  ButtonImage           = SBEvil_HerrderErde
  ButtonBorderType      = ACTION
  RadiusCursorType      = TrainingRadiusCursor
  TextLabel             = CONTROLBAR:SauronInfluence
  DescriptLabel         = CONTROLBAR:ToolTipSauronInfluence
  InPalantir            = Yes
  Radial                = Yes
End

CommandButton Command_PurchaseUpgradeMordorHaradBasicTraining
    Command                = OBJECT_UPGRADE
    Options                = NEED_UPGRADE OK_FOR_MULTI_SELECT CANCELABLE
    Upgrade                = Upgrade_BasicTraining
    NeededUpgrade          = Upgrade_TechnologyHaradBasicTraining
    TextLabel              = CONTROLBAR:PurchaseUpgradeMordorBasicTraining
    ConflictingLabel       = CONTROLBAR:BatallionAreadyHasUpgrade
    ButtonImage            = BIHaradBannerButton
    ButtonBorderType       = UPGRADE
    DescriptLabel          = CONTROLBAR:ToolTipPurchaseUpgradeMordorBasicTraining
    InPalantir             = Yes
    LacksPrerequisiteLabel = TOOLTIP:LackMordorBasicTraining
End

CommandButton Command_PurchaseUpgradeMordorHaradBlades
    Command                  = OBJECT_UPGRADE
    TextLabel                = CONTROLBAR:PurchaseUpgradeIsengardForgedBlades
    Options                  = NEED_UPGRADE OK_FOR_MULTI_SELECT CANCELABLE
    Upgrade                  = Upgrade_ForgedBlades
    NeededUpgrade            = Upgrade_TechnologyHaradForgedBlades
    ButtonImage              = BIHaradForgedBlades
    ButtonBorderType         = UPGRADE
    DescriptLabel            = CONTROLBAR:ToolTipPurchaseUpgradeMordorForgedBlades
    InPalantir               = Yes
    LacksPrerequisiteLabel   = TOOLTIP:LackMordorForgedBlades
End

CommandButton Command_PurchaseUpgradeMordorHaradFireArrows
    Command                = OBJECT_UPGRADE
    TextLabel              = CONTROLBAR:FireArrowUpgrade
    Options                = NEED_UPGRADE OK_FOR_MULTI_SELECT CANCELABLE
    Upgrade                = Upgrade_FireArrows
    NeededUpgrade          = Upgrade_TechnologyHaradFireArrows
    ButtonImage            = BIHaradFireArrows                      ;BRRohanFeuerpfeil
    ButtonBorderType       = UPGRADE
    DescriptLabel          = CONTROLBAR:ToolTipPurchaseUpgradeMordorFireArrows
    InPalantir             = Yes
    LacksPrerequisiteLabel = TOOLTIP:LackMordorHaradFireArrow
End

CommandButton Command_TogglePalantir1_MOTEFort
   Command = TOGGLE_WEAPONSET
   FlagsUsedForToggle = WEAPONSET_TOGGLE_2
   TextLabel = CONTROLBAR:OldCommandsetMOTE
   ButtonImage = ChangeCommandSet
   ButtonBorderType = ACTION
   DescriptLabel = CONTROLBAR:ToolTipOldCommandsetMOTE
   InPalantir = Yes
   Radial     = Yes
End

CommandButton Command_TogglePalantir2_MOTEFort
    Command = TOGGLE_WEAPONSET
    FlagsUsedForToggle = WEAPONSET_TOGGLE_1
    TextLabel = CONTROLBAR:NewCommandsetMOTE
    ButtonImage = RestoreCommandSet
    ButtonBorderType = ACTION
    DescriptLabel = CONTROLBAR:ToolTipNewCommandsetMOTE
    InPalantir = Yes
    Radial     = Yes
    CommandRangeStart       = 1
    CommandRangeCount       = 17
End

CommandButton Command_SpecialAbilitySuladanPorter
  Command           = SPECIAL_POWER
  SpecialPower      = SpecialAbilitySuladanPorter
  TextLabel         = CONTROLBAR:SpecialAbilitySuladanPorter
  ButtonImage       = BIHaradOasis
  Options           = NEED_TARGET_POS CONTEXTMODE_COMMAND
  RadiusCursorType  = FatamorganaRadiusCursor
  CursorName        = Bombard
  InvalidCursorName = GenericInvalid
  ButtonBorderType  = ACTION
  DescriptLabel     = CONTROLBAR:ToolTipSpecialAbilitySuladanPorter
  InPalantir        = Yes
End

CommandButton Command_SummonedPorterConstructHaradBarracks
  Command          = DOZER_CONSTRUCT
  Object           = HaradBarracks
  TextLabel        = CONTROLBAR:ConstructHaradBarracks
  ButtonImage      = UIHaradFortress
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipHaradBarracks
  Radial           = Yes
End


CommandButton Command_SummonedPorterConstructHaradMumakilPen
  Command          = DOZER_CONSTRUCT
  Object           = HaradMumakilPen
  TextLabel        = CONTROLBAR:ConstructMordorMumakilPen
  ButtonImage      = BMMumakilPen
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:ToolTipMordorMumakilPen
  Radial           = Yes
End

CommandButton Command_SummonedPorterConstructHaradOasis
  Command          = DOZER_CONSTRUCT
  Object           = HaradOasis
  TextLabel        = CONTROLBAR:BuildHaradOasis
  ButtonImage      = BIHaradOasis
  DescriptLabel    = CONTROLBAR:ToolTipMordorMumakilPen
  ButtonBorderType = BUILD
  DescriptLabel    = CONTROLBAR:BuildHaradOasisDescription
  Radial           = Yes
End


CommandButton Command_SpecialAbilitySuladanCorsairs
  Command           = SPECIAL_POWER
  SpecialPower      = SpecialAbilityUmbarReinforcements
  TextLabel         = CONTROLBAR:SuladanCorsairs
  ButtonImage       = HSUrukAxe
  Options           = NEED_TARGET_POS CONTEXTMODE_COMMAND OK_FOR_MULTI_SELECT OK_FOR_MULTI_EXECUTE
  RadiusCursorType  = scUglukLV10
  CursorName        = Bombard
  InvalidCursorName = GenericInvalid
  ButtonBorderType  = ACTION
  DescriptLabel     = CONTROLBAR:ToolTipSuladanCorsairs
  AutoAbility       = Yes
  InPalantir        = Yes
End

CommandButton Command_SpecialAbilitySuladanGloriousCharge
  Command                 = SPECIAL_POWER
  SpecialPower            = SpecialAbilitySuladanGloriousCharge
  Options                 = OK_FOR_MULTI_SELECT OK_FOR_MULTI_EXECUTE
  TextLabel               = CONTROLBAR:SuladanChargeofGlory
  ButtonImage             = BRFactionHarad
  RadiusCursorType        = TrainingRadiusCursor
  ButtonBorderType        = ACTION
  DescriptLabel           = CONTROLBAR:ToolTipSuladanChargeofGlory
  InPalantir              = Yes
  AutoAbility             = Yes
End

CommandButton Command_SpecialAbilitySuladanHorn
  Command                  = SPECIAL_POWER
  SpecialPower             = SpecialAbilitySharkuManEater
  TextLabel                = CONTROLBAR:SuladanHorn
  ButtonImage              = BIMahudHornOfHarad
  ButtonBorderType         = ACTION
  DescriptLabel            = CONTROLBAR:ToolTipSuladanHorn
  InPalantir               = Yes
  AutoAbility              = Yes
  PresetRange              = 60.0
    DisableOnModelCondition = MOUNTED
End

CommandButton Command_ToggleFormationRhunschwerter
  Command                 = HORDE_TOGGLE_FORMATION
  Options                 = TOGGLE_IMAGE_ON_FORMATION OK_FOR_MULTI_SELECT OK_FOR_MULTI_EXECUTE
  ButtonImage             = BIRedDoubleLineUp BIRedMarchformation
  ButtonBorderType        = ACTION
  TextLabel               = CONTROLBAR:ToggleShieldWallFormation    CONTROLBAR:ToggleLineFormation
  DescriptLabel           = CONTROLBAR:ToolTipToggleRhunschwerterLineToShieldWallFormation    CONTROLBAR:ToolTipToggleTowerGuardShieldWallToLineFormation
  InPalantir              = Yes
  DoubleClick             = Yes
End

CommandButton Command_ConstructMordorHaradrimLancerModHordeBarracks
    Command                = UNIT_BUILD
    Object                 = MordorHaradrimLancerModHorde
    Options                = CANCELABLE NEED_UPGRADE
    NeededUpgrade          = Upgrade_EvilMenEasterlingBarracksLevel2
    TextLabel              = CONTROLBAR:ConstructMordorHaradrimLancerHorde
    ButtonImage            = HSHaradrimLancer
    ButtonBorderType       = BUILD
    DescriptLabel          = CONTROLBAR:ToolTipBuildMordorHaradrimLancerHordeBarracks
    Radial                 = Yes
    InPalantir             = Yes
    ShowProductionCount    = Yes
    LacksPrerequisiteLabel = TOOLTIP:Lacklevel2Haradrimbarracks
End

CommandButton Command_ConstructHaradHaradrimArcherHordeBarracks
    Command                = UNIT_BUILD
    Object                 = HaradHaradrimArcherHorde
    Options                = CANCELABLE NEED_UPGRADE
    NeededUpgrade          = Upgrade_EvilMenEasterlingBarracksLevel2
    TextLabel              = CONTROLBAR:ConstructMordorHaradrimArcherHorde
    ButtonImage            = UIHaradrimArcher ;BRHaradHaradrimArcher
    ButtonBorderType       = BUILD
    DescriptLabel          = CONTROLBAR:ToolTipBuildMordorHaradrimArcherHordeBarracks
    Radial                 = Yes
    InPalantir             = Yes
    ShowProductionCount    = Yes
    LacksPrerequisiteLabel = TOOLTIP:Lacklevel2Haradrimbarracks
End

CommandButton Command_RhunEquipment
  Command               = SPECIAL_POWER
  SpecialPower          = SpecialAbilityFakeLeadership
  Options               = NONPRESSABLE
  ButtonImage           = HSRhunSchwert
  ButtonBorderType      = ACTION
  RadiusCursorType      = TrainingRadiusCursor
  TextLabel             = CONTROLBAR:RhunEquipment
  DescriptLabel         = CONTROLBAR:ToolTipRhunEquipment
  InPalantir            = Yes
End

CommandButton Command_CorsairsPillage
  Command               = SPECIAL_POWER
  SpecialPower          = SpecialAbilityFakeLeadership
  Options               = NONPRESSABLE
  ButtonImage           = SBEvil_Plus100CommandPoints
  ButtonBorderType      = ACTION
  RadiusCursorType      = TrainingRadiusCursor
  TextLabel             = CONTROLBAR:CorsairsPillage
  DescriptLabel         = CONTROLBAR:ToolTipCorsairsPillage
  InPalantir            = Yes
End

CommandButton Command_SpecialAbilitySalemeGftigeKlinge
    Command            = SPECIAL_POWER
    SpecialPower        = SpecialAbilityDurmarthFluchklinge
    Options            = NEED_TARGET_ENEMY_OBJECT
    TextLabel        = CONTROLBAR:SalemeGiftigeKlingen
    DescriptLabel        = CONTROLBAR:ToolTipSalemeGiftigeKlingen
    ButtonImage        = HSSalemeGiftigeKlinge
    InvalidCursorName    = GenericInvalid
    CursorName        = EvilAbilityObj
    ButtonBorderType    = ACTION
    InPalantir        = Yes
    AutoAbility        = Yes
End

CommandButton Command_BerenHunt
  Command           = SPECIAL_POWER
  SpecialPower      = SpecialAbilityDieJagd
  Options           = NEED_TARGET_ENEMY_OBJECT
  TextLabel         = CONTROLBAR:SpecialAbilityBerenHunt
  ButtonImage       = HSBerenDisguise
  CursorName        = Bombard
  ButtonBorderType  = ACTION
  DescriptLabel     = CONTROLBAR:ToolTipSpecialAbilityBerenHunt
  InvalidCursorName = GenericInvalid
  InPalantir        = Yes
  DisableOnModelCondition = HERO
  AutoAbility       = Yes
  PresetRange       = 200.0
End


CommandButton Command_BuildNargothrondHammerHordeFort
  Command                 = UNIT_BUILD
  Object                  = NargothrondHammerHorde
  Options                 = CANCELABLE NEED_UPGRADE
  ButtonImage             = HPNargothrondHammer
  ButtonBorderType        = BUILD
  TextLabel               = CONTROLBAR:BuildNargothrondHammerHorde
  DescriptLabel           = CONTROLBAR:ToolTipNargothrondHammerHorde2
  Radial                  = Yes
  InPalantir              = Yes
  IsClickable             = Yes
  ShowProductionCount     = Yes
  NeededUpgrade           = Upgrade_FirstAgeFortressLevel2
End

CommandButton Command_SpecialAbilityTreacheryOfTheRing
    Command            = SPECIAL_POWER
    SpecialPower        = SpecialAbilityTreacheryOfTheRingNew
    TextLabel        = CONTROLBAR:TreacheryOfTheRing
    ButtonImage        = HSBilboTreacheryOfTheRing
    InvalidCursorName    = GenericInvalid
    ButtonBorderType    = ACTION
    DescriptLabel        = CONTROLBAR:ToolTipTreacheryOfTheRing
    InPalantir            = Yes

    AutoAbility        = Yes
    PresetRange        = 50.0
    UnitSpecificSound    = BilboNew_RingReturned BilboRingMode
        DisableOnModelCondition = WEAPONSET_TOGGLE_1
End

CommandButton Command_SpecialAbilityAdventure
    Command            = SPECIAL_POWER
    SpecialPower        = SpecialAbilityAdventure
    TextLabel        = CONTROLBAR:BilboAdventure
    ButtonImage        = HPBilboYoung
    InvalidCursorName    = GenericInvalid
    ButtonBorderType    = ACTION
    DescriptLabel        = CONTROLBAR:ToolTipBilboAdventure
    InPalantir            = Yes

    AutoAbility        = Yes
    PresetRange        = 50.0
    UnitSpecificSound    = BilboNew_RingReturned BilboRingMode
        DisableOnModelCondition = WEAPONSET_TOGGLE_1
End

CommandButton Command_SpecialAbilityBilboMasterburgler
  Command                 = SPECIAL_POWER
  SpecialPower            = SpecialAbilityTindomielBeauty
  Options                 = UNMOUNTED_ONLY
  ButtonImage             = UPTomBertBil
  ButtonBorderType        = ACTION
  TextLabel               = CONTROLBAR:Masterburgler
  DescriptLabel           = CONTROLBAR:ToolTipMasterburgler
  InPalantir              = Yes
  AutoDelay               = 30.0
  PresetRange             = 50.0
End

CommandButton Command_SpecialAbilityRiddles
  Command                 = SPECIAL_POWER
  SpecialPower            = SpecialAbilityBilboRiddles
  Options                 = NEED_TARGET_ENEMY_OBJECT
  TextLabel               = CONTROLBAR:SpecialAbilityBilboRiddles
  ButtonImage             = HPGollumRingdieb
  CursorName              = Bombard
  ButtonBorderType        = ACTION
  DescriptLabel           = CONTROLBAR:ToolTipSpecialAbilityBilboRiddles
  InvalidCursorName       = GenericInvalid
  InPalantir              = Yes
  AutoAbility             = Yes
  PresetRange             = 200.0
End 

CommandButton Command_ToggleBilboWeapon
    Command                    =    TOGGLE_WEAPONSET
    Options                    =    TOGGLE_IMAGE_ON_WEAPONSET
    FlagsUsedForToggle        =   WEAPONSET_TOGGLE_1
    TextLabel               =    CONTROLBAR:tooltipCommand_ToggleZapfenThrow CONTROLBAR:UseSword
    ButtonImage             =    HSGandalfTannenzapfen HSFrodoSting
    ButtonBorderType        =    ACTION
    DescriptLabel           =    CONTROLBAR:ToolTipThrowZapfen CONTROLBAR:ToolTipUseSword
    InPalantir                =    Yes
End

CommandButton Command_SpecialAbilityBilboGuardian
  Command                 = SPECIAL_POWER
  SpecialPower            = SpecialAbilityBilboGuardian
  Options                 = NEED_TARGET_ALLY_OBJECT
  TextLabel               = CONTROLBAR:SpecialAbilityBilboGuardian
  ButtonImage             = HSDefilerWargsprung
  CursorName              = Bombard
  ButtonBorderType        = ACTION
  DescriptLabel           = CONTROLBAR:ToolTipSpecialAbilityBilboGuardian
  InvalidCursorName       = GenericInvalid
  InPalantir              = Yes
  AutoAbility             = Yes
  PresetRange             = 200.0
End 

CommandButton Command_GiveArkenstone
  Command                     = SPECIAL_POWER
  SpecialPower                = SpecialAbilityBilboArkenstone
  Options                     = NEED_TARGET_ALLY_OBJECT
  TextLabel                   = CONTROLBAR:SpecialAbilityBilboArkenstone
  CursorName                  = Defector
  InvalidCursorName           = GenericInvalid
  ButtonImage                 = HSGlanzdesArkensteins
  ButtonBorderType            = ACTION
  DescriptLabel               = CONTROLBAR:ToolTipSpecialAbilityBilboArkenstone
  InPalantir            = Yes
  AutoAbility            = Yes
End

CommandButton Command_SpecialAbilityCompanyPalantir1
    Command            = TOGGLE_WEAPONSET
    Options            = TOGGLE_IMAGE_ON_WEAPONSET
    FlagsUsedForToggle = WEAPONSET_HERO_MODE
    TextLabel          = CONTROLBAR:TogglePalantir1_MOS
    ButtonImage        = ChangeCommandSet
    ButtonBorderType   = ACTION
    DescriptLabel      = CONTROLBAR:ToolTipTogglePalantir1_MOS
    InPalantir         = Yes
End

CommandButton Command_SpecialAbilityCompanyPalantir2
    Command            = TOGGLE_WEAPONSET
    Options            = TOGGLE_IMAGE_ON_WEAPONSET
    FlagsUsedForToggle = MOUNTED
    TextLabel          = CONTROLBAR:TogglePalantir2_MOS
    ButtonImage        = RestoreCommandSet
    ButtonBorderType   = ACTION
    DescriptLabel      = CONTROLBAR:ToolTipTogglePalantir2_MOS
    InPalantir         = Yes
End


CommandButton Command_SpecialAbilityNoriSummonDori
  Command     = SPECIAL_POWER
  SpecialPower    = SpecialAbilityZuSülzeZerquetschen
  TextLabel   = CONTROLBAR:SpecialAbilityNoriSummonDori
  DescriptLabel   = CONTROLBAR:ToolTipSpecialAbilityNoriSummonDori
  ButtonImage   = HSDoriundNori
  ButtonBorderType  = ACTION
  InPalantir    = Yes
  AutoAbility   = Yes
End

CommandButton Command_DiplomacyGimli
  Command                     = SPECIAL_POWER
  SpecialPower                = SpecialAbilityGimliDiplomacy
  Options                     = NEED_TARGET_ALLY_OBJECT
  TextLabel                   = CONTROLBAR:SpecialAbilityGimliDiplomacy
  CursorName                  = Defector
  InvalidCursorName           = GenericInvalid
  ButtonImage                 = HSSelectUnitsAglarond
  ButtonBorderType            = ACTION
  DescriptLabel               = CONTROLBAR:ToolTipSpecialAbilityGimliDiplomacy
  InPalantir            = Yes
  AutoAbility            = Yes
End

CommandButton Command_ArveduiFavour
  Command                     = SPECIAL_POWER
  SpecialPower                = SpecialAbilityArveduiFavour
  Options                     = NEED_TARGET_ALLY_OBJECT
  TextLabel                   = CONTROLBAR:SpecialAbilityFavourArvedui
  CursorName                  = Defector
  InvalidCursorName           = GenericInvalid
  ButtonImage                 = HSArveduiFavour
  ButtonBorderType            = ACTION
  DescriptLabel               = CONTROLBAR:ToolTipSpecialAbilityFavourArvedui
  InPalantir            = Yes
  AutoAbility            = Yes
End

CommandButton Command_SpecialAbilityMahudRaserei 
    Command                 = SPECIAL_POWER
    SpecialPower            = SpecialAbilityMahudRaserei 
    Options                 = OK_FOR_MULTI_SELECT OK_FOR_MULTI_EXECUTE
    TextLabel               = CONTROLBAR:SpecialAbilityMahudRaserei
    ButtonImage             = _uHaradMhdFiMahudRaserei
    RadiusCursorType        = TrainingRadiusCursor    
    ButtonBorderType        = ACTION
    DescriptLabel           = CONTROLBAR:TooltipSpecialAbilityMahudRaserei
    InPalantir    = Yes
	AutoAbility   = Yes
End

CommandButton Command_SpecialAbilityMahudGuardMumak
  Command                   = SPECIAL_POWER 
  SpecialPower              = SpecialAbilityMahudGuardMumak
  Options                   = NEED_TARGET_ALLY_OBJECT ; CONTEXTMODE_COMMAND
  TextLabel                 = CONTROLBAR:GuardMumakMahud
  CursorName                = Defector
  InvalidCursorName         = GenericInvalid 
  ButtonImage               = _uHaradMhdFiMahudGuardMumak
  ButtonBorderType          = ACTION 
  DescriptLabel             = CONTROLBAR:TooltipGuardMumakMahud
  InPalantir      = Yes
  AutoAbility     = Yes  
  DisableOnModelCondition = USER_74
End

CommandButton Command_ToggleFormationEvilMenHaradrimSoldier
    Command            = HORDE_TOGGLE_FORMATION                ; Gondor Soldier
    Options            = TOGGLE_IMAGE_ON_FORMATION OK_FOR_MULTI_SELECT
    ButtonImage        = UCFormation_Block UCFormation_Line
    ButtonBorderType    = ACTION 
    TextLabel        = CONTROLBAR:ToggleFormationHaradSouthWatcher         CONTROLBAR:ToggleFormationBackHaradSouthWatcher
    DescriptLabel        = CONTROLBAR:ToolTipToggleFormationHaradSouthWatcher  CONTROLBAR:ToolTipToggleFormationBackHaradSouthWatcher
    InPalantir        = Yes
    DoubleClick        = Yes
    UnitSpecificSound    = HaradrimVoiceWedgeFormation HaradrimVoiceLineFormation
    DisableOnModelCondition = USER_74
End

CommandButton Command_ConstructHaradSouthWatcherHorde
    Command                 = UNIT_BUILD
    Object                  = HaradSouthWatcherHorde
    Options                 = CANCELABLE
    TextLabel               = CONTROLBAR:ConstructHaradMahudFighterHorde
    ButtonImage             = __uMuhadButton ;UISouthWatcher
    ButtonBorderType        = ACTION ;BUILD
    DescriptLabel           = CONTROLBAR:ToolTipConstructHaradMahudFighterHorde
    Radial                  = Yes
    InPalantir              = Yes
    ShowProductionCount     = Yes 
    DisableOnModelCondition = USER_74
End

CommandButton Command_PorterConstructEvilMenMarketPlace
    Command                = DOZER_CONSTRUCT
    Object                = EvilMenMarketplace
    TextLabel            = CONTROLBAR:ConstructMenMarketPlace
    ButtonImage            = BGMarketplace
    ButtonBorderType    = BUILD
    DescriptLabel        = CONTROLBAR:ToolTipConstructMenMarketPlace
    Radial                = Yes
End