

#define EXPANDABLE_HORDE_HP_ADD_LVL2                15
#define EXPANDABLE_HORDE_HP_ADD_LVL3                15
#define EXPANDABLE_HORDE_HP_ADD_LVL4                15
#define EXPANDABLE_HORDE_HP_ADD_LVL5                15

#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL2            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL3            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL4            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL5            2


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAP_HORDE_HP_ADD_LVL2                30
#define CHEAP_HORDE_HP_ADD_LVL3                30
#define CHEAP_HORDE_HP_ADD_LVL4                30
#define CHEAP_HORDE_HP_ADD_LVL5                30

#define CHEAP_HORDE_DAMAGE_ADD_LVL2            3
#define CHEAP_HORDE_DAMAGE_ADD_LVL3            3
#define CHEAP_HORDE_DAMAGE_ADD_LVL4            3
#define CHEAP_HORDE_DAMAGE_ADD_LVL5            3

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASIC_HORDE_HP_ADD_LVL2                40
#define BASIC_HORDE_HP_ADD_LVL3                40
#define BASIC_HORDE_HP_ADD_LVL4                40
#define BASIC_HORDE_HP_ADD_LVL5                40

#define BASIC_HORDE_DAMAGE_ADD_LVL2            4
#define BASIC_HORDE_DAMAGE_ADD_LVL3            4
#define BASIC_HORDE_DAMAGE_ADD_LVL4            4
#define BASIC_HORDE_DAMAGE_ADD_LVL5            4

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define BASIC10_HORDE_HP_ADD_LVL2                60
#define BASIC10_HORDE_HP_ADD_LVL3                60
#define BASIC10_HORDE_HP_ADD_LVL4                60
#define BASIC10_HORDE_HP_ADD_LVL5                60

#define BASIC10_HORDE_DAMAGE_ADD_LVL2            5
#define BASIC10_HORDE_DAMAGE_ADD_LVL3            5
#define BASIC10_HORDE_DAMAGE_ADD_LVL4            5
#define BASIC10_HORDE_DAMAGE_ADD_LVL5            5

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR15_HORDE_HP_ADD_LVL2                65
#define REGULAR15_HORDE_HP_ADD_LVL3                65
#define REGULAR15_HORDE_HP_ADD_LVL4                65
#define REGULAR15_HORDE_HP_ADD_LVL5                65

#define REGULAR15_HORDE_DAMAGE_ADD_LVL2            7
#define REGULAR15_HORDE_DAMAGE_ADD_LVL3            7
#define REGULAR15_HORDE_DAMAGE_ADD_LVL4            7
#define REGULAR15_HORDE_DAMAGE_ADD_LVL5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR5_HORDE_HP_ADD_LVL2                0
#define REGULAR5_HORDE_HP_ADD_LVL3                180
#define REGULAR5_HORDE_HP_ADD_LVL4                180
#define REGULAR5_HORDE_HP_ADD_LVL5                180

#define REGULAR5_HORDE_DAMAGE_ADD_LVL2            0
#define REGULAR5_HORDE_DAMAGE_ADD_LVL3            10
#define REGULAR5_HORDE_DAMAGE_ADD_LVL4            10
#define REGULAR5_HORDE_DAMAGE_ADD_LVL5            10

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR_HORDE_HP_ADD_LVL2                90
#define REGULAR_HORDE_HP_ADD_LVL3                90
#define REGULAR_HORDE_HP_ADD_LVL4                90
#define REGULAR_HORDE_HP_ADD_LVL5                90

#define REGULAR_HORDE_DAMAGE_ADD_LVL2            8
#define REGULAR_HORDE_DAMAGE_ADD_LVL3            8
#define REGULAR_HORDE_DAMAGE_ADD_LVL4            8
#define REGULAR_HORDE_DAMAGE_ADD_LVL5            8

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED_HORDE_HP_ADD_LVL2                100
#define ADVANCED_HORDE_HP_ADD_LVL3                100
#define ADVANCED_HORDE_HP_ADD_LVL4                100
#define ADVANCED_HORDE_HP_ADD_LVL5                100

#define ADVANCED_HORDE_DAMAGE_ADD_LVL2            11
#define ADVANCED_HORDE_DAMAGE_ADD_LVL3            11
#define ADVANCED_HORDE_DAMAGE_ADD_LVL4            11
#define ADVANCED_HORDE_DAMAGE_ADD_LVL5            11

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED5_HORDE_HP_ADD_LVL2                1
#define ADVANCED5_HORDE_HP_ADD_LVL3                200
#define ADVANCED5_HORDE_HP_ADD_LVL4                200
#define ADVANCED5_HORDE_HP_ADD_LVL5                200

#define ADVANCED5_HORDE_DAMAGE_ADD_LVL2            1
#define ADVANCED5_HORDE_DAMAGE_ADD_LVL3            13
#define ADVANCED5_HORDE_DAMAGE_ADD_LVL4            13
#define ADVANCED5_HORDE_DAMAGE_ADD_LVL5            13

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED3_HORDE_HP_ADD_LVL2                300
#define ADVANCED3_HORDE_HP_ADD_LVL3                300
#define ADVANCED3_HORDE_HP_ADD_LVL4                300
#define ADVANCED3_HORDE_HP_ADD_LVL5                300

#define ADVANCED3_HORDE_DAMAGE_ADD_LVL2            15
#define ADVANCED3_HORDE_DAMAGE_ADD_LVL3            15
#define ADVANCED3_HORDE_DAMAGE_ADD_LVL4            15
#define ADVANCED3_HORDE_DAMAGE_ADD_LVL5            15

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED8_HORDE_HP_ADD_LVL2                125
#define ADVANCED8_HORDE_HP_ADD_LVL3                125
#define ADVANCED8_HORDE_HP_ADD_LVL4                125
#define ADVANCED8_HORDE_HP_ADD_LVL5                125

#define ADVANCED8_HORDE_DAMAGE_ADD_LVL2            12
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL3            12
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL4            12
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL5            12

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITE_HORDE_HP_ADD_LVL2                300
#define ELITE_HORDE_HP_ADD_LVL3                300
#define ELITE_HORDE_HP_ADD_LVL4                300
#define ELITE_HORDE_HP_ADD_LVL5                300
#define ELITE_HORDE_HP_ADD_LVL6                300
#define ELITE_HORDE_HP_ADD_LVL7                300
#define ELITE_HORDE_HP_ADD_LVL8                300
#define ELITE_HORDE_HP_ADD_LVL9                300
#define ELITE_HORDE_HP_ADD_LVL10               300


#define ELITE_HORDE_DAMAGE_ADD_LVL2            15
#define ELITE_HORDE_DAMAGE_ADD_LVL3            15
#define ELITE_HORDE_DAMAGE_ADD_LVL4            15
#define ELITE_HORDE_DAMAGE_ADD_LVL5            15
#define ELITE_HORDE_DAMAGE_ADD_LVL6            15
#define ELITE_HORDE_DAMAGE_ADD_LVL7            15
#define ELITE_HORDE_DAMAGE_ADD_LVL8            15
#define ELITE_HORDE_DAMAGE_ADD_LVL9            15
#define ELITE_HORDE_DAMAGE_ADD_LVL10           15

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define VETERANS_HORDE_HP_ADD_LVL2                225
#define VETERANS_HORDE_HP_ADD_LVL3                225
#define VETERANS_HORDE_HP_ADD_LVL4                225
#define VETERANS_HORDE_HP_ADD_LVL5                225
#define VETERANS_HORDE_HP_ADD_LVL6                225
#define VETERANS_HORDE_HP_ADD_LVL7                225
#define VETERANS_HORDE_HP_ADD_LVL8                225
#define VETERANS_HORDE_HP_ADD_LVL9                225
#define VETERANS_HORDE_HP_ADD_LVL10               225
#define VETERANS_HORDE_HP_ADD_LVL11               225
#define VETERANS_HORDE_HP_ADD_LVL12               225
#define VETERANS_HORDE_HP_ADD_LVL13               225
#define VETERANS_HORDE_HP_ADD_LVL14               225
#define VETERANS_HORDE_HP_ADD_LVL15               225
#define VETERANS_HORDE_HP_ADD_LVL16               225
#define VETERANS_HORDE_HP_ADD_LVL17               225
#define VETERANS_HORDE_HP_ADD_LVL18               225
#define VETERANS_HORDE_HP_ADD_LVL19               225
#define VETERANS_HORDE_HP_ADD_LVL20               225


#define VETERANS_HORDE_DAMAGE_ADD_LVL2            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL3            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL4            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL5            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL6            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL7            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL8            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL9            14
#define VETERANS_HORDE_DAMAGE_ADD_LVL10           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL11           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL12           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL13           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL14           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL15           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL16           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL17           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL18           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL19           14
#define VETERANS_HORDE_DAMAGE_ADD_LVL20           14


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITE_10_HORDE_HP_ADD_LVL2                150
#define ELITE_10_HORDE_HP_ADD_LVL3                150
#define ELITE_10_HORDE_HP_ADD_LVL4                150
#define ELITE_10_HORDE_HP_ADD_LVL5                150
#define ELITE_10_HORDE_HP_ADD_LVL6                150
#define ELITE_10_HORDE_HP_ADD_LVL7                150
#define ELITE_10_HORDE_HP_ADD_LVL8                150
#define ELITE_10_HORDE_HP_ADD_LVL9                150
#define ELITE_10_HORDE_HP_ADD_LVL10               150


#define ELITE_10_HORDE_DAMAGE_ADD_LVL2            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL3            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL4            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL5            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL6            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL7            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL8            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL9            9
#define ELITE_10_HORDE_DAMAGE_ADD_LVL10           9

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITE3_HORDE_HP_ADD_LVL2                420
#define ELITE3_HORDE_HP_ADD_LVL3                420
#define ELITE3_HORDE_HP_ADD_LVL4                420
#define ELITE3_HORDE_HP_ADD_LVL5                420
#define ELITE3_HORDE_HP_ADD_LVL6                420
#define ELITE3_HORDE_HP_ADD_LVL7                420
#define ELITE3_HORDE_HP_ADD_LVL8                420
#define ELITE3_HORDE_HP_ADD_LVL9                420
#define ELITE3_HORDE_HP_ADD_LVL10               420


#define ELITE3_HORDE_DAMAGE_ADD_LVL2            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL3            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL4            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL5            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL6            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL7            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL8            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL9            16
#define ELITE3_HORDE_DAMAGE_ADD_LVL10           16

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAP_CHAMPION_HORDE_HP_ADD_LVL2                300
#define CHEAP_CHAMPION_HORDE_HP_ADD_LVL3                300
#define CHEAP_CHAMPION_HORDE_HP_ADD_LVL4                300
#define CHEAP_CHAMPION_HORDE_HP_ADD_LVL5                300

#define CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL2            30
#define CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL3            30
#define CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL4            30
#define CHEAP_CHAMPION_HORDE_DAMAGE_ADD_LVL5            30

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR_CHAMPION_HORDE_HP_ADD_LVL2                200
#define REGULAR_CHAMPION_HORDE_HP_ADD_LVL3                200
#define REGULAR_CHAMPION_HORDE_HP_ADD_LVL4                200
#define REGULAR_CHAMPION_HORDE_HP_ADD_LVL5                200

#define REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL2            35
#define REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL3            35
#define REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL4            35
#define REGULAR_CHAMPION_HORDE_DAMAGE_ADD_LVL5            35

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL2                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL3                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL4                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL5                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL6                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL7                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL8                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL9                100
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL10               100


#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL2            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL3            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL4            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL5            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL6            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL7            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL8            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL9            20
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL10           20


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10               400


#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9            25
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10           25


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASICCAV_HORDE_HP_ADD_LVL2                60
#define BASICCAV_HORDE_HP_ADD_LVL3                60
#define BASICCAV_HORDE_HP_ADD_LVL4                60
#define BASICCAV_HORDE_HP_ADD_LVL5                60

#define BASICCAV_HORDE_DAMAGE_ADD_LVL2            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL3            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL4            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL5            7
;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define REGULARCAV_HORDE_HP_ADD_LVL2                60
#define REGULARCAV_HORDE_HP_ADD_LVL3                60
#define REGULARCAV_HORDE_HP_ADD_LVL4                60
#define REGULARCAV_HORDE_HP_ADD_LVL5                60

#define REGULARCAV_HORDE_DAMAGE_ADD_LVL2            7
#define REGULARCAV_HORDE_DAMAGE_ADD_LVL3            7
#define REGULARCAV_HORDE_DAMAGE_ADD_LVL4            7
#define REGULARCAV_HORDE_DAMAGE_ADD_LVL5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ARCHERCAV_HORDE_DAMAGE_ADD_LVL2            7
#define ARCHERCAV_HORDE_DAMAGE_ADD_LVL3            7
#define ARCHERCAV_HORDE_DAMAGE_ADD_LVL4            7
#define ARCHERCAV_HORDE_DAMAGE_ADD_LVL5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ADVANCEDCAV_HORDE_HP_ADD_LVL2               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL3               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL4               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL5               110

#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL2            9
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL3            9
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL4            9
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL5            9

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ADVANCEDCAV5_HORDE_HP_ADD_LVL2               1
#define ADVANCEDCAV5_HORDE_HP_ADD_LVL3               110
#define ADVANCEDCAV5_HORDE_HP_ADD_LVL4               110
#define ADVANCEDCAV5_HORDE_HP_ADD_LVL5               110

#define ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL2            1
#define ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL3            12
#define ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL4            12
#define ADVANCEDCAV5_HORDE_DAMAGE_ADD_LVL5            12

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ELITE_CAVALRY_HORDE_HP_ADD_LVL2               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL3               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL4               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL5               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL6               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL7               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL8               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL9               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL10              350


#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL2            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL3            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL4            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL5            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL6            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL7            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL8            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL9            15
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL10           15


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAPBEASTS_HORDE_HP_ADD_LVL2               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL3               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL4               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL5               40

#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL2            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL3            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL4            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL5            5

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASICBEASTS_HORDE_HP_ADD_LVL2               60
#define BASICBEASTS_HORDE_HP_ADD_LVL3               60
#define BASICBEASTS_HORDE_HP_ADD_LVL4               60
#define BASICBEASTS_HORDE_HP_ADD_LVL5               60

#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL2            7
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL3            8
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL4            8
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL5            8

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAPMONSTER_HORDE_HP_ADD_LVL2               40
#define CHEAPMONSTER_HORDE_HP_ADD_LVL3               40
#define CHEAPMONSTER_HORDE_HP_ADD_LVL4               40
#define CHEAPMONSTER_HORDE_HP_ADD_LVL5               40

#define CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL2            7
#define CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL3            8
#define CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL4            8
#define CHEAPMONSTER_HORDE_DAMAGE_ADD_LVL5            8

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASICMONSTER_HORDE_HP_ADD_LVL2               120
#define BASICMONSTER_HORDE_HP_ADD_LVL3               120
#define BASICMONSTER_HORDE_HP_ADD_LVL4               120
#define BASICMONSTER_HORDE_HP_ADD_LVL5               120

#define BASICMONSTER_HORDE_DAMAGE_ADD_LVL2            9
#define BASICMONSTER_HORDE_DAMAGE_ADD_LVL3            10
#define BASICMONSTER_HORDE_DAMAGE_ADD_LVL4            10
#define BASICMONSTER_HORDE_DAMAGE_ADD_LVL5            10

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULARMONSTER_HORDE_HP_ADD_LVL2               200
#define REGULARMONSTER_HORDE_HP_ADD_LVL3               200
#define REGULARMONSTER_HORDE_HP_ADD_LVL4               200
#define REGULARMONSTER_HORDE_HP_ADD_LVL5               200

#define REGULARMONSTER_HORDE_DAMAGE_ADD_LVL2            15
#define REGULARMONSTER_HORDE_DAMAGE_ADD_LVL3            20
#define REGULARMONSTER_HORDE_DAMAGE_ADD_LVL4            20
#define REGULARMONSTER_HORDE_DAMAGE_ADD_LVL5            20

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCEDMONSTER_HORDE_HP_ADD_LVL2               400
#define ADVANCEDMONSTER_HORDE_HP_ADD_LVL3               400
#define ADVANCEDMONSTER_HORDE_HP_ADD_LVL4               400
#define ADVANCEDMONSTER_HORDE_HP_ADD_LVL5               400

#define ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL2            30
#define ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL3            35
#define ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL4            35
#define ADVANCEDMONSTER_HORDE_DAMAGE_ADD_LVL5            35

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITEMONSTER_HORDE_HP_ADD_LVL2               500
#define ELITEMONSTER_HORDE_HP_ADD_LVL3               500
#define ELITEMONSTER_HORDE_HP_ADD_LVL4               500
#define ELITEMONSTER_HORDE_HP_ADD_LVL5               500
#define ELITEMONSTER_HORDE_HP_ADD_LVL6               550
#define ELITEMONSTER_HORDE_HP_ADD_LVL7               550
#define ELITEMONSTER_HORDE_HP_ADD_LVL8               550
#define ELITEMONSTER_HORDE_HP_ADD_LVL9               550
#define ELITEMONSTER_HORDE_HP_ADD_LVL10              550

#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL2            50
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL3            55
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL4            55
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL5            55
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL6            55
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL7            60
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL8            60
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL9            60
#define ELITEMONSTER_HORDE_DAMAGE_ADD_LVL10           60
;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------









