

#define EXPANDABLE_HORDE_HP_ADD_LVL2                15
#define EXPANDABLE_HORDE_HP_ADD_LVL3                15
#define EXPANDABLE_HORDE_HP_ADD_LVL4                15
#define EXPANDABLE_HORDE_HP_ADD_LVL5                15

#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL2            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL3            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL4            2
#define EXPANDABLE_HORDE_DAMAGE_ADD_LVL5            2


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAP_HORDE_HP_ADD_LVL2                30
#define CHEAP_HORDE_HP_ADD_LVL3                30
#define CHEAP_HORDE_HP_ADD_LVL4                30
#define CHEAP_HORDE_HP_ADD_LVL5                30

#define CHEAP_HORDE_DAMAGE_ADD_LVL2            4
#define CHEAP_HORDE_DAMAGE_ADD_LVL3            4
#define CHEAP_HORDE_DAMAGE_ADD_LVL4            4
#define CHEAP_HORDE_DAMAGE_ADD_LVL5            4

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASIC_HORDE_HP_ADD_LVL2                40
#define BASIC_HORDE_HP_ADD_LVL3                40
#define BASIC_HORDE_HP_ADD_LVL4                40
#define BASIC_HORDE_HP_ADD_LVL5                40

#define BASIC_HORDE_DAMAGE_ADD_LVL2            6
#define BASIC_HORDE_DAMAGE_ADD_LVL3            6
#define BASIC_HORDE_DAMAGE_ADD_LVL4            6
#define BASIC_HORDE_DAMAGE_ADD_LVL5            6

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR15_HORDE_HP_ADD_LVL2                65
#define REGULAR15_HORDE_HP_ADD_LVL3                65
#define REGULAR15_HORDE_HP_ADD_LVL4                65
#define REGULAR15_HORDE_HP_ADD_LVL5                65

#define REGULAR15_HORDE_DAMAGE_ADD_LVL2            10
#define REGULAR15_HORDE_DAMAGE_ADD_LVL3            10
#define REGULAR15_HORDE_DAMAGE_ADD_LVL4            10
#define REGULAR15_HORDE_DAMAGE_ADD_LVL5            10

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define REGULAR_HORDE_HP_ADD_LVL2                90
#define REGULAR_HORDE_HP_ADD_LVL3                90
#define REGULAR_HORDE_HP_ADD_LVL4                90
#define REGULAR_HORDE_HP_ADD_LVL5                90

#define REGULAR_HORDE_DAMAGE_ADD_LVL2            13
#define REGULAR_HORDE_DAMAGE_ADD_LVL3            13
#define REGULAR_HORDE_DAMAGE_ADD_LVL4            13
#define REGULAR_HORDE_DAMAGE_ADD_LVL5            13

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED_HORDE_HP_ADD_LVL2                100
#define ADVANCED_HORDE_HP_ADD_LVL3                100
#define ADVANCED_HORDE_HP_ADD_LVL4                100
#define ADVANCED_HORDE_HP_ADD_LVL5                100

#define ADVANCED_HORDE_DAMAGE_ADD_LVL2            20
#define ADVANCED_HORDE_DAMAGE_ADD_LVL3            20
#define ADVANCED_HORDE_DAMAGE_ADD_LVL4            20
#define ADVANCED_HORDE_DAMAGE_ADD_LVL5            20

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ADVANCED8_HORDE_HP_ADD_LVL2                125
#define ADVANCED8_HORDE_HP_ADD_LVL3                125
#define ADVANCED8_HORDE_HP_ADD_LVL4                125
#define ADVANCED8_HORDE_HP_ADD_LVL5                125

#define ADVANCED8_HORDE_DAMAGE_ADD_LVL2            25
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL3            25
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL4            25
#define ADVANCED8_HORDE_DAMAGE_ADD_LVL5            25

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITE_HORDE_HP_ADD_LVL2                300
#define ELITE_HORDE_HP_ADD_LVL3                300
#define ELITE_HORDE_HP_ADD_LVL4                300
#define ELITE_HORDE_HP_ADD_LVL5                300
#define ELITE_HORDE_HP_ADD_LVL6                300
#define ELITE_HORDE_HP_ADD_LVL7                300
#define ELITE_HORDE_HP_ADD_LVL8                300
#define ELITE_HORDE_HP_ADD_LVL9                300
#define ELITE_HORDE_HP_ADD_LVL10               300


#define ELITE_HORDE_DAMAGE_ADD_LVL2            35
#define ELITE_HORDE_DAMAGE_ADD_LVL3            35
#define ELITE_HORDE_DAMAGE_ADD_LVL4            35
#define ELITE_HORDE_DAMAGE_ADD_LVL5            35
#define ELITE_HORDE_DAMAGE_ADD_LVL6            35
#define ELITE_HORDE_DAMAGE_ADD_LVL7            35
#define ELITE_HORDE_DAMAGE_ADD_LVL8            35
#define ELITE_HORDE_DAMAGE_ADD_LVL9            35
#define ELITE_HORDE_DAMAGE_ADD_LVL10           35

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define ELITE3_HORDE_HP_ADD_LVL2                420
#define ELITE3_HORDE_HP_ADD_LVL3                420
#define ELITE3_HORDE_HP_ADD_LVL4                420
#define ELITE3_HORDE_HP_ADD_LVL5                420
#define ELITE3_HORDE_HP_ADD_LVL6                420
#define ELITE3_HORDE_HP_ADD_LVL7                420
#define ELITE3_HORDE_HP_ADD_LVL8                420
#define ELITE3_HORDE_HP_ADD_LVL9                420
#define ELITE3_HORDE_HP_ADD_LVL10               420


#define ELITE3_HORDE_DAMAGE_ADD_LVL2            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL3            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL4            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL5            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL6            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL7            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL8            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL9            50
#define ELITE3_HORDE_DAMAGE_ADD_LVL10           50

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL2                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL3                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL4                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL5                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL6                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL7                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL8                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL9                200
#define FIRST_AGE_REGULARINFANTRY_HORDE_HP_ADD_LVL10               200


#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL2            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL3            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL4            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL5            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL6            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL7            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL8            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL9            30
#define FIRST_AGE_REGULARINFANTRY_HORDE_DAMAGE_ADD_LVL10           30


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL2                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL3                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL4                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL5                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL6                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL7                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL8                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL9                400
#define FIRST_AGE_ELITEINFANTRY_HORDE_HP_ADD_LVL10               400


#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL2            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL3            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL4            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL5            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL6            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL7            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL8            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL9            60
#define FIRST_AGE_ELITEINFANTRY_HORDE_DAMAGE_ADD_LVL10           60


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASICCAV_HORDE_HP_ADD_LVL2                60
#define BASICCAV_HORDE_HP_ADD_LVL3                60
#define BASICCAV_HORDE_HP_ADD_LVL4                60
#define BASICCAV_HORDE_HP_ADD_LVL5                60

#define BASICCAV_HORDE_DAMAGE_ADD_LVL2            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL3            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL4            7
#define BASICCAV_HORDE_DAMAGE_ADD_LVL5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ADVANCEDCAV_HORDE_HP_ADD_LVL2               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL3               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL4               110
#define ADVANCEDCAV_HORDE_HP_ADD_LVL5               110

#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL2            20
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL3            20
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL4            20
#define ADVANCEDCAV_HORDE_DAMAGE_ADD_LVL5            20

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define ELITE_CAVALRY_HORDE_HP_ADD_LVL2               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL3               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL4               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL5               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL6               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL7               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL8               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL9               350
#define ELITE_CAVALRY_HORDE_HP_ADD_LVL10              350


#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL2            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL3            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL4            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL5            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL6            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL7            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL8            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL9            35
#define ELITE_CAVALRY_HORDE_DAMAGE_ADD_LVL10           35


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define CHEAPBEASTS_HORDE_HP_ADD_LVL2               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL3               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL4               40
#define CHEAPBEASTS_HORDE_HP_ADD_LVL5               40

#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL2            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL3            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL4            5
#define CHEAPBEASTS_HORDE_DAMAGE_ADD_LVL5            5

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define BASICBEASTS_HORDE_HP_ADD_LVL2               60
#define BASICBEASTS_HORDE_HP_ADD_LVL3               60
#define BASICBEASTS_HORDE_HP_ADD_LVL4               60
#define BASICBEASTS_HORDE_HP_ADD_LVL5               60

#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL2            7
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL3            8
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL4            8
#define BASICBEASTS_HORDE_DAMAGE_ADD_LVL5            8

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
