

#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_1          1
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_2         20
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_3        30
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_4        60
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_5        110

#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_1            1
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_2            2
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_3            3
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_4            3
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_5            4

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_CHEAP_HORDE_1          1
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_2         40
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_3         85
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_4        145
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_5        230

#define EXPERIENCE_AWARD_CHEAP_HORDE_1            2
#define EXPERIENCE_AWARD_CHEAP_HORDE_2            3
#define EXPERIENCE_AWARD_CHEAP_HORDE_3            4
#define EXPERIENCE_AWARD_CHEAP_HORDE_4            5
#define EXPERIENCE_AWARD_CHEAP_HORDE_5            6

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_BASIC_HORDE_1          1
#define EXPERIENCE_REQUIRED_BASIC_HORDE_2         50
#define EXPERIENCE_REQUIRED_BASIC_HORDE_3        110
#define EXPERIENCE_REQUIRED_BASIC_HORDE_4        185
#define EXPERIENCE_REQUIRED_BASIC_HORDE_5        280

#define EXPERIENCE_AWARD_BASIC_HORDE_1            3
#define EXPERIENCE_AWARD_BASIC_HORDE_2            4
#define EXPERIENCE_AWARD_BASIC_HORDE_3            5
#define EXPERIENCE_AWARD_BASIC_HORDE_4            6
#define EXPERIENCE_AWARD_BASIC_HORDE_5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_1          1
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_2         70
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_3        140
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_4        230
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_5        335

#define EXPERIENCE_AWARD_REGULAR_15_HORDE_1            4
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_2            5
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_3            6
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_4            7
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_5            8


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_HORDE_1          1
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_2         70
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_3        140
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_4        230
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_5        335

#define EXPERIENCE_AWARD_REGULAR_HORDE_1            6
#define EXPERIENCE_AWARD_REGULAR_HORDE_2            7
#define EXPERIENCE_AWARD_REGULAR_HORDE_3            8
#define EXPERIENCE_AWARD_REGULAR_HORDE_4            9
#define EXPERIENCE_AWARD_REGULAR_HORDE_5           10


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_1          1
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_2        130
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_3        165
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_4        300
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_5        450

#define EXPERIENCE_AWARD_ADVANCED_HORDE_1            8
#define EXPERIENCE_AWARD_ADVANCED_HORDE_2            9
#define EXPERIENCE_AWARD_ADVANCED_HORDE_3            9
#define EXPERIENCE_AWARD_ADVANCED_HORDE_4           10
#define EXPERIENCE_AWARD_ADVANCED_HORDE_5           12


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_1          1
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_2        130
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_3        165
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_4        300
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_5        450

#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_1            9
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_2           10
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_3           11
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_4           12
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_5           13

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ELITE_HORDE_1          1
#define EXPERIENCE_REQUIRED_ELITE_HORDE_2        100
#define EXPERIENCE_REQUIRED_ELITE_HORDE_3        225
#define EXPERIENCE_REQUIRED_ELITE_HORDE_4        375
#define EXPERIENCE_REQUIRED_ELITE_HORDE_5        550
#define EXPERIENCE_REQUIRED_ELITE_HORDE_6        650
#define EXPERIENCE_REQUIRED_ELITE_HORDE_7        775
#define EXPERIENCE_REQUIRED_ELITE_HORDE_8        925
#define EXPERIENCE_REQUIRED_ELITE_HORDE_9       1200
#define EXPERIENCE_REQUIRED_ELITE_HORDE_10      1500



#define EXPERIENCE_AWARD_ELITE_HORDE_1           20
#define EXPERIENCE_AWARD_ELITE_HORDE_2           25
#define EXPERIENCE_AWARD_ELITE_HORDE_3           30
#define EXPERIENCE_AWARD_ELITE_HORDE_4           35
#define EXPERIENCE_AWARD_ELITE_HORDE_5           40
#define EXPERIENCE_AWARD_ELITE_HORDE_6           45
#define EXPERIENCE_AWARD_ELITE_HORDE_7           50
#define EXPERIENCE_AWARD_ELITE_HORDE_8           55
#define EXPERIENCE_AWARD_ELITE_HORDE_9           60
#define EXPERIENCE_AWARD_ELITE_HORDE_10          65


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_1           28
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_2           30
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_3           42
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_4           49
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_5           56
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_6           63
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_7           70
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_8           77
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_9           84
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_10          90

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_1          1
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_2        150
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_3        350
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_4        470
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_5        750
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_6       1050
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_7       1380
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_8       1720
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_9       2120
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_10      2570



#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_1           15
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_2           20
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_3           22
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_4           25
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_5           30
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_6           33
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_7           35
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_8           40
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_9           45
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_10          50


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_1           30
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_2           40
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_3           45
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_4           50
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_5           60
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_6           65
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_7           70
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_8           80
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_9           90
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_10         100

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_1          1
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_2         75
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_3        165
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_4        270
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_5        390

#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_1            5
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_2            6
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_3            7
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_4            8
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_5            9


;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_1          1
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_2        100
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_3        200
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_4        300
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_5        450

#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_1            8
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_2            9
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_3           10
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_4           11
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_5           12


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_1          1
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_2        150
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_3        230
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_4        350
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_5        500

#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_1           10
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_2           11
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_3           11
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_4           12
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_5           13

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_1          1
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_2        120
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_3        250
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_4        400
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_5        600
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_6        700
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_7        800
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_8        950
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_9       1300
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_10      1600

#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_1           25
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_2           30
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_3           35
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_4           40
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_5           45
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_6           50
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_7           55
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_8           60
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_9           65
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_10          70


;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_1          1
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_2         50
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_3        110
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_4        170
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_5        280

#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_1            3
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_2            4
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_3            5
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_4            6
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_1          1
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_2         75
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_3        165
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_4        250
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_5        400

#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_1            4
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_2            6
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_3            7
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_4            8
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_5            9

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------