

#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_1        1
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_2        30
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_3        40
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_4        80
#define EXPERIENCE_REQUIRED_EXPANDABLE_HORDE_5        140

#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_1            1
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_2            2
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_3            2
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_4            3
#define EXPERIENCE_AWARD_EXPANDABLE_HORDE_5            3

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_CHEAP_HORDE_1        1
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_2        60
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_3        100
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_4        170
#define EXPERIENCE_REQUIRED_CHEAP_HORDE_5        250

#define EXPERIENCE_AWARD_CHEAP_HORDE_1            4
#define EXPERIENCE_AWARD_CHEAP_HORDE_2            4
#define EXPERIENCE_AWARD_CHEAP_HORDE_3            5
#define EXPERIENCE_AWARD_CHEAP_HORDE_4            5
#define EXPERIENCE_AWARD_CHEAP_HORDE_5            6

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_BASIC_HORDE_1        1
#define EXPERIENCE_REQUIRED_BASIC_HORDE_2        80
#define EXPERIENCE_REQUIRED_BASIC_HORDE_3        140
#define EXPERIENCE_REQUIRED_BASIC_HORDE_4        230
#define EXPERIENCE_REQUIRED_BASIC_HORDE_5        340

#define EXPERIENCE_AWARD_BASIC_HORDE_1            5
#define EXPERIENCE_AWARD_BASIC_HORDE_2            5
#define EXPERIENCE_AWARD_BASIC_HORDE_3            6
#define EXPERIENCE_AWARD_BASIC_HORDE_4            7
#define EXPERIENCE_AWARD_BASIC_HORDE_5            7

#define EXPERIENCE_AWARD_BASIC_10_HORDE_1            6
#define EXPERIENCE_AWARD_BASIC_10_HORDE_2            6
#define EXPERIENCE_AWARD_BASIC_10_HORDE_3            7
#define EXPERIENCE_AWARD_BASIC_10_HORDE_4            7
#define EXPERIENCE_AWARD_BASIC_10_HORDE_5            8

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_2        110
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_3        190
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_4        290
#define EXPERIENCE_REQUIRED_REGULAR_15_HORDE_5        400

#define EXPERIENCE_AWARD_REGULAR_15_HORDE_1            7
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_2            7
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_3            8
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_4            8
#define EXPERIENCE_AWARD_REGULAR_15_HORDE_5            9


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_2        70
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_3        140
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_4        230
#define EXPERIENCE_REQUIRED_REGULAR_HORDE_5        335

#define EXPERIENCE_AWARD_REGULAR_HORDE_1            8
#define EXPERIENCE_AWARD_REGULAR_HORDE_2            8
#define EXPERIENCE_AWARD_REGULAR_HORDE_3            9
#define EXPERIENCE_AWARD_REGULAR_HORDE_4            9
#define EXPERIENCE_AWARD_REGULAR_HORDE_5            10


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_5_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_5_HORDE_2        7000
#define EXPERIENCE_REQUIRED_REGULAR_5_HORDE_3        7200
#define EXPERIENCE_REQUIRED_REGULAR_5_HORDE_4        7290
#define EXPERIENCE_REQUIRED_REGULAR_5_HORDE_5        7400

#define EXPERIENCE_AWARD_REGULAR_5_HORDE_1            10
#define EXPERIENCE_AWARD_REGULAR_5_HORDE_2            12
#define EXPERIENCE_AWARD_REGULAR_5_HORDE_3            14
#define EXPERIENCE_AWARD_REGULAR_5_HORDE_4            16
#define EXPERIENCE_AWARD_REGULAR_5_HORDE_5            18


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_2        190
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_3        250
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_4        400
#define EXPERIENCE_REQUIRED_ADVANCED_HORDE_5        520

#define EXPERIENCE_AWARD_ADVANCED_HORDE_1           9
#define EXPERIENCE_AWARD_ADVANCED_HORDE_2           9
#define EXPERIENCE_AWARD_ADVANCED_HORDE_3           10
#define EXPERIENCE_AWARD_ADVANCED_HORDE_4           10
#define EXPERIENCE_AWARD_ADVANCED_HORDE_5           11


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_3_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_3_HORDE_2        180
#define EXPERIENCE_REQUIRED_ADVANCED_3_HORDE_3        200
#define EXPERIENCE_REQUIRED_ADVANCED_3_HORDE_4        300
#define EXPERIENCE_REQUIRED_ADVANCED_3_HORDE_5        450

#define EXPERIENCE_AWARD_ADVANCED_3_HORDE_1            16
#define EXPERIENCE_AWARD_ADVANCED_3_HORDE_2            18
#define EXPERIENCE_AWARD_ADVANCED_3_HORDE_3            20
#define EXPERIENCE_AWARD_ADVANCED_3_HORDE_4            22
#define EXPERIENCE_AWARD_ADVANCED_3_HORDE_5            24


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_5_HORDE_1       1
#define EXPERIENCE_REQUIRED_ADVANCED_5_HORDE_2       7130
#define EXPERIENCE_REQUIRED_ADVANCED_5_HORDE_3       7230
#define EXPERIENCE_REQUIRED_ADVANCED_5_HORDE_4       7400
#define EXPERIENCE_REQUIRED_ADVANCED_5_HORDE_5       7550

#define EXPERIENCE_AWARD_ADVANCED_5_HORDE_1            16
#define EXPERIENCE_AWARD_ADVANCED_5_HORDE_2            18
#define EXPERIENCE_AWARD_ADVANCED_5_HORDE_3            20
#define EXPERIENCE_AWARD_ADVANCED_5_HORDE_4            22
#define EXPERIENCE_AWARD_ADVANCED_5_HORDE_5            24


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_2        130
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_3        165
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_4        300
#define EXPERIENCE_REQUIRED_ADVANCED_8_HORDE_5        450

#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_1           10
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_2           10
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_3           11
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_4           11
#define EXPERIENCE_AWARD_ADVANCED_8_HORDE_5           12

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ELITE_HORDE_1        1
#define EXPERIENCE_REQUIRED_ELITE_HORDE_2        100
#define EXPERIENCE_REQUIRED_ELITE_HORDE_3        225
#define EXPERIENCE_REQUIRED_ELITE_HORDE_4        375
#define EXPERIENCE_REQUIRED_ELITE_HORDE_5        550
#define EXPERIENCE_REQUIRED_ELITE_HORDE_6        650
#define EXPERIENCE_REQUIRED_ELITE_HORDE_7        775
#define EXPERIENCE_REQUIRED_ELITE_HORDE_8        925
#define EXPERIENCE_REQUIRED_ELITE_HORDE_9       1200
#define EXPERIENCE_REQUIRED_ELITE_HORDE_10      1500



#define EXPERIENCE_AWARD_ELITE_HORDE_1           30
#define EXPERIENCE_AWARD_ELITE_HORDE_2           35
#define EXPERIENCE_AWARD_ELITE_HORDE_3           40
#define EXPERIENCE_AWARD_ELITE_HORDE_4           45
#define EXPERIENCE_AWARD_ELITE_HORDE_5           50
#define EXPERIENCE_AWARD_ELITE_HORDE_6           55
#define EXPERIENCE_AWARD_ELITE_HORDE_7           60
#define EXPERIENCE_AWARD_ELITE_HORDE_8           65
#define EXPERIENCE_AWARD_ELITE_HORDE_9           70
#define EXPERIENCE_AWARD_ELITE_HORDE_10          75


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_1        1
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_2        100
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_3        225
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_4        375
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_5        550
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_6        650
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_7        775
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_8        925
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_9       1200
#define EXPERIENCE_REQUIRED_ELITE_10_HORDE_10      1500



#define EXPERIENCE_AWARD_ELITE_10_HORDE_1           15
#define EXPERIENCE_AWARD_ELITE_10_HORDE_2           17
#define EXPERIENCE_AWARD_ELITE_10_HORDE_3           20
#define EXPERIENCE_AWARD_ELITE_10_HORDE_4           23
#define EXPERIENCE_AWARD_ELITE_10_HORDE_5           25
#define EXPERIENCE_AWARD_ELITE_10_HORDE_6           27
#define EXPERIENCE_AWARD_ELITE_10_HORDE_7           30
#define EXPERIENCE_AWARD_ELITE_10_HORDE_8           33
#define EXPERIENCE_AWARD_ELITE_10_HORDE_9           36
#define EXPERIENCE_AWARD_ELITE_10_HORDE_10          39


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_VETERANS_HORDE_1       1
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_2       250
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_3       400
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_4       550
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_5       700
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_6       850
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_7       1000
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_8       1150
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_9       1300
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_10      1450
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_11      1700
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_12      1950
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_13      2100
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_14      2250
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_15      2250
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_16      2400
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_17      2550
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_18      2700
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_19      2850
#define EXPERIENCE_REQUIRED_VETERANS_HORDE_20      3000



#define EXPERIENCE_AWARD_VETERANS_HORDE_1           30
#define EXPERIENCE_AWARD_VETERANS_HORDE_2           34
#define EXPERIENCE_AWARD_VETERANS_HORDE_3           40
#define EXPERIENCE_AWARD_VETERANS_HORDE_4           42
#define EXPERIENCE_AWARD_VETERANS_HORDE_5           46
#define EXPERIENCE_AWARD_VETERANS_HORDE_6           50
#define EXPERIENCE_AWARD_VETERANS_HORDE_7           54
#define EXPERIENCE_AWARD_VETERANS_HORDE_8           58
#define EXPERIENCE_AWARD_VETERANS_HORDE_9           62
#define EXPERIENCE_AWARD_VETERANS_HORDE_10          66
#define EXPERIENCE_AWARD_VETERANS_HORDE_11          70 
#define EXPERIENCE_AWARD_VETERANS_HORDE_12          74
#define EXPERIENCE_AWARD_VETERANS_HORDE_13          78
#define EXPERIENCE_AWARD_VETERANS_HORDE_14          82
#define EXPERIENCE_AWARD_VETERANS_HORDE_15          86
#define EXPERIENCE_AWARD_VETERANS_HORDE_16          90
#define EXPERIENCE_AWARD_VETERANS_HORDE_17          94
#define EXPERIENCE_AWARD_VETERANS_HORDE_18          98
#define EXPERIENCE_AWARD_VETERANS_HORDE_19          102
#define EXPERIENCE_AWARD_VETERANS_HORDE_20          106

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_1        1
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_2        100
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_3        225
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_4        375
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_5        550
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_6        650
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_7        775
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_8        925
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_9       1200
#define EXPERIENCE_REQUIRED_ELITE_TRIO_HORDE_10      1500

#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_1           38
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_2           40
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_3           52
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_4           59
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_5           66
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_6           73
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_7           80
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_8           87
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_9           94
#define EXPERIENCE_AWARD_ELITE_TRIO_HORDE_10          100

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_1        1
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_2        150
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_3        200
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_4        250
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_5        300
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_6        400
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_7        500
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_8        600
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_9        700
#define EXPERIENCE_REQUIRED_CHEAP_CHAMPION_HORDE_10       800

#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_1           70
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_2           80
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_3           90
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_4           100
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_5           110
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_6           120
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_7           130
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_8           140
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_9           150
#define EXPERIENCE_AWARD_CHEAP_CHAMPION_HORDE_10          160

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_2        200
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_3        300
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_4        400
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_5        500
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_6        600
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_7        700
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_8        800
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_9        900
#define EXPERIENCE_REQUIRED_REGULAR_CHAMPION_HORDE_10       1000

#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_1           80
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_2           90
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_3           100
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_4           110
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_5           120
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_6           130
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_7           140
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_8          	150
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_9           160
#define EXPERIENCE_AWARD_REGULAR_CHAMPION_HORDE_10          170

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_1        1
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_2        150
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_3        350
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_4        470
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_5        750
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_6       1050
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_7       1380
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_8       1720
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_9       2120
#define EXPERIENCE_REQUIRED_FIRST_AGE_REGULAR_HORDE_10      2570



#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_1           30
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_2           35
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_3           37
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_4           40
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_5           45
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_6           48
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_7           50
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_8           55
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_9           60
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_HORDE_10          75


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_1           30
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_2           40
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_3           45
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_4           50
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_5           60
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_6           65
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_7           70
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_8           80
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_9           90
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_HORDE_10         100

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_1           80
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_2           90
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_3           100
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_4           120
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_5           130
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_6           140
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_7           160
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_8           170
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_9           190
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_FLYING_HORDE_10          230

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_1           90
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_2           120
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_3           130
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_4           140
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_5           160
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_6           180
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_7           200
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_8           230
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_9           260
#define EXPERIENCE_AWARD_FIRST_AGE_BETTER_FLYING_HORDE_10          300

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_1           100
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_2           130
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_3           170
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_4           210
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_5           250
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_6           290
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_7           320
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_8           350
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_9           370
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_FLYING_HORDE_10          400

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_1           100
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_2           120
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_3           130
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_4           140
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_5           160
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_6           180
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_7           200
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_8           230
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_9           260
#define EXPERIENCE_AWARD_FIRST_AGE_ELITE_MONSTER_HORDE_10          300

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_1           120
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_2           120
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_3           130
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_4           140
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_5           160
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_6           200
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_7           250
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_8           300
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_9           350
#define EXPERIENCE_AWARD_FIRST_AGE_LEGENDARY_MONSTER_HORDE_10          400

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_1           80
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_2           90
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_3           100
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_4           120
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_5           130
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_6           140
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_7           160
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_8           190
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_9           220
#define EXPERIENCE_AWARD_FIRST_AGE_REGULAR_BEASTS_HORDE_10          250

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_1           130
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_2           150
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_3           180
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_4           220
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_5           250
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_6           300
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_7           350
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_8           400
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_9           450
#define EXPERIENCE_AWARD_FIRST_AGE_BEST_BEASTS_HORDE_10          500

;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_1        1
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_2        75
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_3        165
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_4        270
#define EXPERIENCE_REQUIRED_BASIC_CAV_HORDE_5        390

#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_1            5
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_2            6
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_3            7
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_4            8
#define EXPERIENCE_AWARD_BASIC_CAV_HORDE_5            9


;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_2        100
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_3        200
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_4        300
#define EXPERIENCE_REQUIRED_REGULAR_CAV_HORDE_5        450

#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_1            8
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_2            9
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_3           10
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_4           11
#define EXPERIENCE_AWARD_REGULAR_CAV_HORDE_5           12


;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_2        150
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_3        230
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_4        350
#define EXPERIENCE_REQUIRED_ADVANCED_CAV_HORDE_5        500

#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_1           10
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_2           11
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_3           11
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_4           12
#define EXPERIENCE_AWARD_ADVANCED_CAV_HORDE_5           13

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ADVANCED_5_CAV_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_5_CAV_HORDE_2        150
#define EXPERIENCE_REQUIRED_ADVANCED_5_CAV_HORDE_3        230
#define EXPERIENCE_REQUIRED_ADVANCED_5_CAV_HORDE_4        350
#define EXPERIENCE_REQUIRED_ADVANCED_5_CAV_HORDE_5        500

#define EXPERIENCE_AWARD_ADVANCED_5_CAV_HORDE_1           20
#define EXPERIENCE_AWARD_ADVANCED_5_CAV_HORDE_2           22
#define EXPERIENCE_AWARD_ADVANCED_5_CAV_HORDE_3           22
#define EXPERIENCE_AWARD_ADVANCED_5_CAV_HORDE_4           24
#define EXPERIENCE_AWARD_ADVANCED_5_CAV_HORDE_5           26

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_1        1
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_2        120
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_3        250
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_4        400
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_5        600
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_6        700
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_7        800
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_8        950
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_9       1300
#define EXPERIENCE_REQUIRED_ELITE_CAVALRY_HORDE_10      1600

#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_1           25
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_2           30
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_3           35
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_4           40
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_5           45
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_6           50
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_7           55
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_8           60
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_9           65
#define EXPERIENCE_AWARD_ELITE_CAVALRY_HORDE_10          70


;------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_1        1
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_2        50
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_3        110
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_4        170
#define EXPERIENCE_REQUIRED_CHEAP_BEASTS_HORDE_5        280

#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_1            3
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_2            4
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_3            5
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_4            6
#define EXPERIENCE_AWARD_CHEAP_BEASTS_HORDE_5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_1        1
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_2        75
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_3        165
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_4        250
#define EXPERIENCE_REQUIRED_BASIC_BEASTS_HORDE_5        400

#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_1            4
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_2            6
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_3            7
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_4            8
#define EXPERIENCE_AWARD_BASIC_BEASTS_HORDE_5            9

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_CHEAP_MONSTER_HORDE_1        1
#define EXPERIENCE_REQUIRED_CHEAP_MONSTER_HORDE_2        50
#define EXPERIENCE_REQUIRED_CHEAP_MONSTER_HORDE_3        110
#define EXPERIENCE_REQUIRED_CHEAP_MONSTER_HORDE_4        170
#define EXPERIENCE_REQUIRED_CHEAP_MONSTER_HORDE_5        280

#define EXPERIENCE_AWARD_CHEAP_MONSTER_HORDE_1            3
#define EXPERIENCE_AWARD_CHEAP_MONSTER_HORDE_2            4
#define EXPERIENCE_AWARD_CHEAP_MONSTER_HORDE_3            5
#define EXPERIENCE_AWARD_CHEAP_MONSTER_HORDE_4            6
#define EXPERIENCE_AWARD_CHEAP_MONSTER_HORDE_5            7

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_BASIC_MONSTER_HORDE_1        1
#define EXPERIENCE_REQUIRED_BASIC_MONSTER_HORDE_2        75
#define EXPERIENCE_REQUIRED_BASIC_MONSTER_HORDE_3        165
#define EXPERIENCE_REQUIRED_BASIC_MONSTER_HORDE_4        250
#define EXPERIENCE_REQUIRED_BASIC_MONSTER_HORDE_5        400

#define EXPERIENCE_AWARD_BASIC_MONSTER_HORDE_1            10
#define EXPERIENCE_AWARD_BASIC_MONSTER_HORDE_2            20
#define EXPERIENCE_AWARD_BASIC_MONSTER_HORDE_3            30
#define EXPERIENCE_AWARD_BASIC_MONSTER_HORDE_4            40
#define EXPERIENCE_AWARD_BASIC_MONSTER_HORDE_5            50

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_REGULAR_MONSTER_HORDE_1        1
#define EXPERIENCE_REQUIRED_REGULAR_MONSTER_HORDE_2        150
#define EXPERIENCE_REQUIRED_REGULAR_MONSTER_HORDE_3        320
#define EXPERIENCE_REQUIRED_REGULAR_MONSTER_HORDE_4        400
#define EXPERIENCE_REQUIRED_REGULAR_MONSTER_HORDE_5        500

#define EXPERIENCE_AWARD_REGULAR_MONSTER_HORDE_1            110
#define EXPERIENCE_AWARD_REGULAR_MONSTER_HORDE_2            120
#define EXPERIENCE_AWARD_REGULAR_MONSTER_HORDE_3            130
#define EXPERIENCE_AWARD_REGULAR_MONSTER_HORDE_4            140
#define EXPERIENCE_AWARD_REGULAR_MONSTER_HORDE_5            150

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#define EXPERIENCE_REQUIRED_ADVANCED_MONSTER_HORDE_1        1
#define EXPERIENCE_REQUIRED_ADVANCED_MONSTER_HORDE_2        200
#define EXPERIENCE_REQUIRED_ADVANCED_MONSTER_HORDE_3        400
#define EXPERIENCE_REQUIRED_ADVANCED_MONSTER_HORDE_4        600
#define EXPERIENCE_REQUIRED_ADVANCED_MONSTER_HORDE_5        800

#define EXPERIENCE_AWARD_ADVANCED_MONSTER_HORDE_1            160
#define EXPERIENCE_AWARD_ADVANCED_MONSTER_HORDE_2            170
#define EXPERIENCE_AWARD_ADVANCED_MONSTER_HORDE_3            180
#define EXPERIENCE_AWARD_ADVANCED_MONSTER_HORDE_4            190
#define EXPERIENCE_AWARD_ADVANCED_MONSTER_HORDE_5            200

;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_1        1
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_2        250
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_3        500
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_4        750
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_5        900
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_6		 1100
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_7		 1300
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_8		 1500
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_9		 1650
#define EXPERIENCE_REQUIRED_ELITE_MONSTER_HORDE_10		 1800

#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_1            200
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_2            210
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_3            220
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_4            230
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_5            240
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_6            250
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_7            260
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_8            270
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_9            280
#define EXPERIENCE_AWARD_ELITE_MONSTER_HORDE_10           290 
;---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------









